### ISSUE TITLE
Unable to execute.

### ISSUE THREAD

**Issue by debanjansen48** [ccsb-scripps/AutoDock-Vina#10]
issued the following comand
#vina12 i renamed and put it in the folder
#the config file contains receptor ligand info 

"receptor=rec.pdbqt
ligand=lig.pdbqt
center_x =  27.898
center_y =  5.175
center_z = 59.160
size_x = 25
size_y = 25
size_z = 25
exhaustiveness=50"

./vina12 --config config.txt --maps rec.*.map --scoring vinardo  --out lig_out.pdbqt --cpu 8
Command line parse error: too many positional options have been specified on the command line

**Comment by diogomart** [comment]
Hi,

try changing `--maps rec.*.map` to `--maps rec`

**Comment by debanjansen48** [comment]
**lower_isomer-2/Vina12$** ./vina12 --config config.txt --maps rec --scoring vinardo --out lig_out.pdbqt --cpu 8
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see http://vina.scripps.edu for more information.      #
#################################################################

ERROR: Cannot specify both receptor and affinity maps at the same time, --flex argument is allowed with receptor or maps.

**Comment by atillack** [comment]
@debanjansen48 You almost have it working :-) The `1iep_receptor_vina_box.txt` example config file only contains the parameters for the search box but not the ligand which you would need to specify in this example (i.e. `--ligand 1iep_ligand.pdbqt`).

Here is our writeup for this example:
[https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#running-autodock-vina](https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#running-autodock-vina)

**Comment by BJWiley233** [comment]
I am having a prefix map issue.  How in the "Hello World" does this not work?

```
% ls Q00534_fill.*.map                                                           
Q00534_fill.A.map       Q00534_fill.HD.map      Q00534_fill.NA.map      Q00534_fill.d.map
Q00534_fill.C.map       Q00534_fill.N.map       Q00534_fill.OA.map      Q00534_fill.e.map
```

```
vina --flex Q00534_fill.BL00010001_ligand_conect.fixed.out_flex.pdbqt --ligand trilaciclib.pdbqt --maps Q00534_fill --scoring vina --exhaustiveness 32 --out Q00534_fill_flex_trilaciclib_vina_out.pdbqt

Scoring function : vina
Flex receptor: Q00534_fill.BL00010001_ligand_conect.fixed.out_flex.pdbqt
Ligand: trilaciclib.pdbqt
Exhaustiveness: 32
CPU: 0
Verbosity: 1

Reading Vina maps ... 
ERROR: No *.map files with prefix "Q00534_fill"
```

**Comment by BJWiley233** [comment]
I added some debug print lines to print out the atom type and file name.  This atom types don't match those normally from any sort of run `Usage: prepare_receptor4.py -r filename`.  Is there a new ` prepare_receptor` for vina?

```
CHECKING atom type: "C_H"

File name: "Q00534_fill.C_H.map"

CHECKING atom type: "C_P"

File name: "Q00534_fill.C_P.map"

CHECKING atom type: "N_P"

File name: "Q00534_fill.N_P.map"

CHECKING atom type: "N_D"

File name: "Q00534_fill.N_D.map"

CHECKING atom type: "N_A"

File name: "Q00534_fill.N_A.map"

CHECKING atom type: "N_DA"

File name: "Q00534_fill.N_DA.map"

CHECKING atom type: "O_P"

File name: "Q00534_fill.O_P.map"

CHECKING atom type: "O_D"

File name: "Q00534_fill.O_D.map"

CHECKING atom type: "O_A"

File name: "Q00534_fill.O_A.map"

CHECKING atom type: "O_DA"

File name: "Q00534_fill.O_DA.map"

CHECKING atom type: "S_P"

File name: "Q00534_fill.S_P.map"

CHECKING atom type: "P_P"

File name: "Q00534_fill.P_P.map"

CHECKING atom type: "F_H"

File name: "Q00534_fill.F_H.map"

CHECKING atom type: "Cl_H"

File name: "Q00534_fill.Cl_H.map"

CHECKING atom type: "Br_H"

File name: "Q00534_fill.Br_H.map"

CHECKING atom type: "I_H"

File name: "Q00534_fill.I_H.map"

CHECKING atom type: "Si"

File name: "Q00534_fill.Si.map"

CHECKING atom type: "At"

File name: "Q00534_fill.At.map"

CHECKING atom type: "Met_D"

File name: "Q00534_fill.Met_D.map"

CHECKING atom type: "C_H"

File name: "Q00534_fill.C_H.map"

CHECKING atom type: "C_P"

File name: "Q00534_fill.C_P.map"

CHECKING atom type: "W"

File name: "Q00534_fill.W.map"
```

**Comment by BJWiley233** [comment]
OK this only works for ad4 scoring function.  This needs to be added to readthedocs as a warning under https://autodock-vina.readthedocs.io/en/latest/docking_basic.html?highlight=map#a-using-autodock4-forcefield
