### ISSUE TITLE
Flexible docking tutorial : no HD map file after autogrid4

### ISSUE THREAD

**Issue by mandar5335** [ccsb-scripps/AutoDock-Vina#105]
Dear all,
I am trying a flexible docking tutorial. I am facing a problem with the generation of the map files. I am using a file `1fpu_receptorH.pdb` from the data folder and instructions thereby.

after executing vina command:

`vina2021 --flex 1fpu_receptor_flex.pdbqt --ligand 1iep_ligand.pdbqt --maps 1fpu_receptor_rigid --scoring ad4 --exhaustiveness 32 --out 1fpu_ligand_flex_ad4_out.pdbqt `

I get an error: 
`ERROR: Affinity map for atom type HD is not present.`

as autogrid4 has not generated HD map file.
`~/ADFRsuite-1.0/bin/autogrid4 -p 1fpu_receptor_rigid.gpf -l 1fpu_receptor_rigid.glg`

I tried to generate map files from processed PDB 1FPU also, but still, the HD map file was missing. 

Looking forward to the suggestions.

Thanks

**Comment by diogomart** [comment]
Hi, can you post your .gpf file?

**Comment by mandar5335** [comment]
Hi,
Thanks for your reply. Please see .gpf file attached. 
[1fpu_receptor_rigid.gpf.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/8550683/1fpu_receptor_rigid.gpf.zip)

This file is generated using command below:

`~/ADFRsuite-1.0/bin/pythonsh ../autodock_github_clone/AutoDock-Vina/example/autodock_scripts/prepare_gpf.py -l 1iep_ligand.pdbqt -r 1fpu_receptor_rigid.pdbqt -y`

.pdbqt file has HD atom type, but still, .gpf file has no entry for HD atom type.

Thanks.

**Comment by diogomart** [comment]
As you wrote, the .gpf is missing the entry for the HD type. I don't know why that would happen. I can't reproduce it on my end.

Editing the .gpf manually requires adding HD to the `ligand_types` line, and adding a new `map` line for the HD type. The order of the `map` lines must match the order of the atom types in the `ligand_types` line.

**Comment by mandar5335** [comment]
I have tried the same script on another Linux desktop (both machines run Ubunutu 20.04 LTS) and an HD map file is generated.
this is quite unusual. Thanks for your suggestions.
