### ISSUE TITLE
converting pdbqt files back to sdf/mol2

### ISSUE THREAD

**Issue by ccbiozhaw** [ccsb-scripps/AutoDock-Vina#107]
hey. This is not really an issue with the tool itself, but with the output it produces. We find that it can be challenging to convert the result pdbqt files back to sdf or mol2 files. 

This is particularly apparent with aromaticity.  We found that obabel 3+ does not kekulize aromatic bonds, so we rely on obabel 2.4, however aromaticity is not our only issue, as this becomes amplified when dealing with pdbqt files from flexible residue docking.

Do you know of a way to safely perform the conversion from pdbqt back to either mol2 or sdf?

**Comment by diogomart** [comment]
we'll have flexible residues soon, they are being worked on: https://github.com/forlilab/Meeko/commit/f8aeee830d8e486980369fb2e931a8afbe60f9c3
