### ISSUE TITLE
bug in prepare_receptor4.py: -e flag does not have any effect

### ISSUE THREAD

**Issue by rczerminski-valo** [ccsb-scripps/AutoDock-Vina#109]
Yes, I know, `prepare_receptor4.py` is not part of vina...
If there is a better place to report this issue please let me know - so far I was not able to find one.

There is a -e in command line options for `prepare_receptor4.py` supposed to control removal or preservation
of non-standard residues:
```
        [-e]  delete every nonstd residue from any chain
              'True': any residue whose name is not in this list:
                      ['CYS','ILE' ...  'HID', 'HSP', 'HIE', 'HIP', 'CYX', 'CSS']
              will be deleted from any chain. 
              NB: there are no  nucleic acid residue names at all  in the list and no metals. 
             (default is False which means not to do this)
```
**so, by default, non-standard residues should be kept, but apparently they are deleted regardless.**

I tracked it down to `.../CCSBpckgs/AutoDockTools/MoleculePreparation.py` where non-standard residues are deleted
in two different places, one under `delete_single_nonstd_residues` flag which is set by -e option and the other under `remove_nonstdres = 'nonstdres' in cleanup_list`

**Comment by rwxayheee** [comment]
Hi @rczerminski-valo, 

There seem to be two slightly different options to clean up the nonstandard components:

-U
The default option -U nphs_lps_waters_nonstdres keeps the nonstandard residues if they are part of the protein main chains. For example, if you have covalent conjugates or covalently modified residues and these fragments have chain ID = A, they will be kept. The -U nonstdres option removes a chain if composed solely of nonstandard residues. Glycols and metals are often assigned with different chain IDs by PDB. You will see a message like this:
'<chain ID> ' apparently composed of not std residues. Deleting 

-e
If you want to remove the nonstandard components from the main chains, you may use the -e option. You will see a message: 
'Deleting non-standard residues:<chain ID, resname, resnumber>_ from <filename>

**Comment by rczerminski-valo** [comment]
Oh, yes - thank you for this clarification. I see that this is not a bug but a feature, and I just did not quite understand these options properly. Maybe somewhat different wording and option setup could make it clearer for novice users of this software (like me :). For example, keep all residues by default and have (just as an example, and with some suitable short versions) following options:
1. `--remove nonstdres` (to remove non-standard residues anywhere)
2. `--remove_chain nonstdres` (remove chain(s) if composed of non-standard residues, equivalent to current `-U nonstdres`)
3. `--remove_from_main_chain nonstdres`
4. `--remove <list>` (to remove specific residues in comma-separated list)
