### ISSUE TITLE
Batch Functionality - Python

### ISSUE THREAD

**Issue by OphirGenomica** [ccsb-scripps/AutoDock-Vina#11]
How do you use the batch function when docking many ligands in python? The documentation briefly mentions the option of using batch mode for virtual screening, but doesn't seem to explain how to use it.

**Comment by jeeberhardt** [comment]
Hi OphirGenomica,

Good catch! Indeed I forgot to add a tutorial about the batch docking feature in the documentation.. 
Briefly, the batch mode can be used by simply replacing the `--ligand` argument by `--batch`. Here an example with the AutoDock4 scoring function:

`vina  --batch pdbqt_ligands/*.pdbqt --maps 1iep_receptor --scoring ad4 --dir pdbqt_docked`

with `pdbqt_ligand` being the directory containing the input PDBQT files and `pdbqt_docked` where the docking results will be saved. Don't forget to create the `pdbqt_docked` directory before starting the docking calculations.

**Comment by OphirGenomica** [comment]
Thank you!
