### ISSUE TITLE
Autodock4Zn tutorial

### ISSUE THREAD

**Issue by Jameel9** [ccsb-scripps/AutoDock-Vina#111]
Hello sir 

Sorry for any inconvenience caused

I have found the tutorial of docking ligand into a pocket of metalloprotein containing Zn. Is it possible to make some residues flexible while they are coordinating a Zn atom? Or it is just for rigid docking?

If it is possible, then which pdbqt file is to be an input for the zinc_pseudo.py script? The flexible or the rigid one? 

Or the flexibility should be set from the file containing the pseudozinc?

**Comment by diogomart** [comment]
Hi,

The AD4Zn potential works only for rigid zinc atoms.

The residues coordinating zinc can be made flexible with a rigid zinc atom, but I'm not sure that provides any significant flexibility.

Vina can model zinc flexibly as an individual ligand (it supports multiple ligands simultaneously), with either the AD4 or Vina scoring functions. The coordinating residues can be made flexible. I haven't tested this, so I don't know if it works well or what kind of problems may occur.

**Comment by Jameel9** [comment]
Thank you very much for rapid response


It seems interesting that vina can dock multiple ligands simultaneously. But is it possible that Zn atoms will be in coordination with other residues (different from the input stucture)? 
I need Zn atoms to be fixed at a specific location.

**Comment by diogomart** [comment]
If zinc is in the receptor, then it will not move. 

Alternatively, and this is also something i never tried, the Zn could go in one of the flexible residues by manually editing the pdbqts.

**Comment by Jameel9** [comment]
Thank you so much.
Your help is highly appreciated.

**Comment by diogomart** [comment]
I'm happy to help and hope it works for you.
