### ISSUE TITLE
Result difference

### ISSUE THREAD

**Issue by Jooyun1983** [ccsb-scripps/AutoDock-Vina#114]
Hi, I used two types of AutoDock-Vina;

1. release v.1.2.3 in (https://github.com/ccsb-scripps/AutoDock-Vina/releases)
2. download source code in (https://github.com/ccsb-scripps/AutoDock-Vina.git, currently being updated??) and set-up >> It was also version v1.2.3.

The pose result is the same, but there is a difference in the score. Is it right?

**Comment by diogomart** [comment]
The score should be the same if the poses are the same, but the search is stochastic, so maybe the poses differ slightly?
