### ISSUE TITLE
Windows version not working

### ISSUE THREAD

**Issue by YuHsienLin** [ccsb-scripps/AutoDock-Vina#116]
Hi, I downloaded the newest win version, but I can't install in my win10 laptop. I click the exe file, and it pops out a command line interface for one seconds and disappear, nothing happens afterwards. Thank you for your time.

**Comment by diogomart** [comment]
Hi,
Vina is meant to be executed from the command line: the command prompt is opened first, and then the vina file is executed from the prompt.

**Comment by diogomart** [comment]
The installation process consists of downloading the file. That's it. Then you can run the file in the command line.

These links may help:
https://www.techwalla.com/articles/how-to-run-exe-files-in-cmd
https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/
