### ISSUE TITLE
H-bonds

### ISSUE THREAD

**Issue by Celtis-australis** [ccsb-scripps/AutoDock-Vina#117]
Hi!
Great work! I'm relatively new to virtual docking. I was wondering if it could potentially be possible to obtain the number of hydrogen bonds between ligand and protein from vina or if this is something that should be done post-analysis.

Thank you!

**Comment by h-kaede** [comment]
Hi, 
I tried vina docking with --score from the command line, but I got the perse error.
Please tell me how to use the command "--score".

OS windows
AutoDock Vina v1.2.3
Command line parse error: unrecognised option '--score'

Thank you.

**Comment by h-kaede** [comment]
Thank you! 
I got the intermolecular score with the command `--score_only`.

I want to know the terms of the Vina's scoring function.
Are there any good methods for that?

Thank you for your time.

**Comment by h-kaede** [comment]
Thank you so much.
I read those papers with very interest.

Please excuse my lack of explanation. 
I want to know ”the value" of terms calculated by Vina.
"Final Intermolecular Energy" given by `--score_only` is the sum of gauss1, gauss2, H-bond, repulsion and hydrophobic energy.
Could I know the values of each terms?

Thank you.

**Comment by diogomart** [comment]
I understand now. For that you'll need vina 1.1.2. For linux you can get a the executable from the bottom of the [releases page](https://github.com/ccsb-scripps/AutoDock-Vina/releases). For Windows and Mac, and also for Linux, visit https://vina.scripps.edu/downloads/

**Comment by h-kaede** [comment]
I was able to get the terms. I am delighted!
Thank you from the bottom of my heart.

**Comment by diogomart** [comment]
Awesome! :-)
