### ISSUE TITLE
Vinardo FF

### ISSUE THREAD

**Issue by linfranksong** [ccsb-scripps/AutoDock-Vina#12]
Hi,

When I'm trying to use the vinardo ff, it gives following error:

ERROR: Cannot score the pose. Affinity maps were not initialized.

My command: ~/vina_1.2.0_linux_x86_64 --ligand ligand.pdbqt --receptor protein.pdbqt --center_x 15.495 --center_y 2.367 --center_z 15.477 --size_x 20 --size_y 20 --size_z 20  --out vina.pdbqt --score_only --scoring vinardo

Same command works for vina scoring function.

Any help would be appreaciated!

Beset,
Lin

**Comment by ccbiozhaw** [comment]
i was just going to post the same. it doesnt work for me either

**Comment by jeeberhardt** [comment]
Hi Lin and ccbiozhaw,

Sorry small bug. The issue was fixed in the last PR #13. You can now git pull the new version.
Tell me if you have any issues.

Jerome.

**Comment by linfranksong** [comment]
Hi Jerome,

Could you update the binary as well? I was using that for my calculations...

Thanks!
Best,
Lin

**Comment by diogomart** [comment]
Hi Lin,
I just updated the linux binary at https://github.com/ccsb-scripps/AutoDock-Vina/releases/tag/v1.2.0

**Comment by linfranksong** [comment]
Thanks!
