### ISSUE TITLE
Constraint docking support?

### ISSUE THREAD

**Issue by luwei0917** [ccsb-scripps/AutoDock-Vina#121]
It is possible to impose some constraint on the ligand orientation (or ligand-protein interaction) while docking?
Thanks.

**Comment by diogomart** [comment]
With AD-GPU yes: https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Anchored-docking

Please keep in mind that it requires a lot of manual intervention, and hasn't been tested extensively.
