### ISSUE TITLE
[question] The affinity value is too low or too high

### ISSUE THREAD

**Issue by Dr-Yi-Li** [ccsb-scripps/AutoDock-Vina#122]
Dear professor:
I used autodock-vina 1.2.3 to dock my ligand and protein. However, the docking result confused me.  The following is the docking result table. The lowest affinity value is -181 and the highest value is 13660. This situation never happened before. However, I could not search any information about my situation. Could you please introduce what kings of situation may cause this problem?

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -181.5          0          0
   2       -174.5       21.7       26.4
   3       -171.7      21.85      25.76
   4       -101.1      21.85      26.51
   5       -9.643      2.432      5.193
   6        121.9      18.74      25.06
   7        387.9      9.778      19.38
   8        585.7       22.4      27.11
   9    1.366e+04      1.278      2.024

**Comment by diogomart** [comment]
Hi,
Can you post your input files and command line argument for us to try to reproduce this result?

**Comment by Dr-Yi-Li** [comment]
The command line is 
vina --ligand MOL005600.pdbqt --receptor 5liu.pdbqt --config MOL005600_5liu.txt --exhaustiveness=4 --out vina_MOL005600_5liu.pdbqt --seed 10000 > log_MOL005600_5liu.txt

The ligand is MOL005600.pdbqt. I changed the suffix of the ligand from pdbqt to txt for uploading it to upload it to github.
[MOL005600.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/9163799/MOL005600.txt)

The protein is 5liu.pdbqt. I changed the suffix of the ligand from pdbqt to txt for uploading it to upload it to github.
[5liu.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/9163813/5liu.txt)

The config file is MOL005600_5liu.txt
[MOL005600_5liu.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/9163822/MOL005600_5liu.txt)

**Comment by rwxayheee** [comment]
Hi all, 
I have a question relevant to this. If we intend to use the Vina force field in which the hydrogens are completely implicit (?), should the hydroxy groups still be assigned as active torsions in ligand pdbqt? 
Sorry for hijacking the post.. I saw a warning message says in the first line of ligand pdbqt. I was wondering if we can deactivate the hydroxy torsions when working with compounds with many OH groups like this. Any comments/suggestions would be greatly appreciated.

**Comment by diogomart** [comment]
@Dr-Yi-Li I think the weird results happen because the ligand is extremely large at 148 atoms and 47 rotatable bonds. Ligands this large are generally intractable.

@rwxayheee you are right that there is no point in making -OH rotatable. What I don't know is if the search becomes easier after -OH bonds are set rigid. I'll report back if I find something out.

**Comment by diogomart** [comment]
[Meeko](https://github.com/forlilab/Meeko) can use SMARTS to set bonds as **not** rotatable:
```sh
mk_prepare_ligand.py -i molecule.sdf -r "[#6]-[OX2]-[#1]" -b 1 2
```

or from Python
```python
from meeko import MoleculePreparation
from rdkit import Chem

mol = Chem.MolFromMolFile("molecule.sdf", removeHs=False) # probably better to use SDMolSupplier
mkconfig = {"rigidify_bonds_smarts": ["[#6]-[OX2]-[#1]"], "rigidify_bonds_indices": [(0, 1)]} # 0-indexed now
mkprep = MoleculePreparation.from_config(mkconfig)
mkprep.prepare(mol)
print(mkprep.write_pdbqt_string())
```
@Dr-Yi-Li do you have an SDF or MOL file for that molecule?

**Comment by Dr-Yi-Li** [comment]
> @Dr-Yi-Li I think the weird results happen because the ligand is extremely large at 148 atoms and 47 rotatable bonds. Ligands this large are generally intractable.
> 
> @rwxayheee you are right that there is no point in making -OH rotatable. What I don't know is if the search becomes easier after -OH bonds are set rigid. I'll report back if I find something out.

THANKS!

**Comment by Dr-Yi-Li** [comment]
> [Meeko](https://github.com/forlilab/Meeko) can use SMARTS to set bonds as **not** rotatable:
> 
> ```shell
> mk_prepare_ligand.py -i molecule.sdf -r "[#6]-[OX2]-[#1]" -b 1 2
> ```
> 
> or from Python
> 
> ```python
> from meeko import MoleculePreparation
> from rdkit import Chem
> 
> mol = Chem.MolFromMolFile("molecule.sdf", removeHs=False) # probably better to use SDMolSupplier
> mkconfig = {"rigidify_bonds_smarts": ["[#6]-[OX2]-[#1]"], "rigidify_bonds_indices": [(0, 1)]} # 0-indexed now
> mkprep = MoleculePreparation.from_config(mkconfig)
> mkprep.prepare(mol)
> print(mkprep.write_pdbqt_string())
> ```
> 
> @Dr-Yi-Li do you have an SDF or MOL file for that molecule?

**Comment by Dr-Yi-Li** [comment]
I have the sdf molecule for the ligand. I changed the suffix of the ligand to txt to upload here. @diogomart 
[MOL005600.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/9230740/MOL005600.txt)

**Comment by diogomart** [comment]
Thank you for the SDF @Dr-Yi-Li 

@rwxayheee based on a couple dockings, limited to half a million evals `--max_evals 500000` I don't see a big difference between the scores of rigid vs flexible -OH groups. My interpretation is that rigidifying -OH groups does not make a large impact on the search. This may be because hydrogens do not contribute gradients and changing the state variables that rotate -OH does not affect the score. Would have to run more dockings to be sure that there is not an impact, but I'll settle with the "not obviously large" conclusion.

**Comment by rwxayheee** [comment]
> Thank you for the SDF @Dr-Yi-Li
> 
> @rwxayheee based on a couple dockings, limited to half a million evals `--max_evals 500000` I don't see a big difference between the scores of rigid vs flexible -OH groups. My interpretation is that rigidifying -OH groups does not make a large impact on the search. This may be because hydrogens do not contribute gradients and changing the state variables that rotate -OH does not affect the score. Would have to run more dockings to be sure that there is not an impact, but I'll settle with the "not obviously large" conclusion.

Yes that makes sense!! Thank you so much for your time and kind replies!
