### ISSUE TITLE
Question: Units convert from ESU to SI, how to calculate constant 332.06363?

### ISSUE THREAD

**Issue by zhongxiang117** [ccsb-scripps/AutoDock-Vina#125]
Hi, this is a question about how to convert the units between ESU and SI. What is the unit of the partial charges used by PDBQT file? Since their values can directly taken from Gaussian/Openbabel program calculation, I guess its unit is `Statcoulomb` ? Is it correct? And we know `1 statcoulomb = 3.33564E-10 Coulomb`, plus the dielectric constant is `8.8542E-12C^2/(Nm^2)`, thus we can do the math calculation:

```
Pelec = 1/(4*pi*dielectric) * (qiqj) / distance
      = 1/(4*3.14*8.8542E-12) * (3.33564E-10)^2 / 10E-10 * (qiqj)/distance    # now distance is on Angstrom
      = 10.005 * qiqj/distance       # units on distance is Angstrom, full unit is on J
```
Then I am stuck at here, can anyone please provide me some info about am I right, or what part/step am I missing? Should I use Avogadro number? Many thanks in advance!

**Comment by diogomart** [comment]
The PDBQT defines partial charges in terms of the [elementary charge](https://en.wikipedia.org/wiki/Elementary_charge), which is the charge of a proton. The elementary charge is about `1.602E-19 Coulomb`, not `StratCoulomb`.

Keep in mind that the vina scoring function ignores partial charges, so no electrostatic energy is calculated unless you use the AD4 scoring function, and there is a distance dependent dielectric in there.

**Comment by diogomart** [comment]
To get to the 332 constant:

The interaction energy, in `Joules`, of two elementary charges 1 `Angstrom` apart is:
```
e0 = 8.8541878128E-12
q = 1.60217663E-19
distance = 1E-10
energy = 1 / (4 * pi * e0) * q^2 / distance = 2.30707E-18 J
```
To get `kcal/mol`, which is what autodock reports,  multiply by avogadro number, multiply by 1000, and divide by `J/cal` which is 4.184:
```
mol = 6.023E23
2.30707E-18 J * 1000 / 4.184 = 332.11 kcal / mol
```

**Comment by zhongxiang117** [comment]
@diogomart Got it, thank you for your help and clarification.
