### ISSUE TITLE
Sorry, there are no Gasteiger parameters available for atom 6hn3:A:SEC46:SE

### ISSUE THREAD

**Issue by yifeng-li** [ccsb-scripps/AutoDock-Vina#126]
Hi, I am using ADFR to convert the pdb file of the GPX4 protein (PDB ID: 6hn3) to the pdbqt format. Note: This is a selenium-containing enzyme. I met the following issue due to Se. Please help provide instructions to add Se parameters to ADFR.

prepare_receptor -r 6hn3.pdb -A 'hydrogens' -o 6hn3.pdbqt
WARNING! 6hn3 has 226  atoms with alternate locations named ['A', 'B', 'C']!

WARNING! using alternate location A
**Sorry, there are no Gasteiger parameters available for atom 6hn3:A:SEC46:SE**

Thanks,
YL

**Comment by diogomart** [comment]
Hi, this repository is for Vina, you can consider the autodock mailing list: https://autodocksuite.scripps.edu/support/
One option is to pretend that Se is S and hope for the best.

**Comment by yifeng-li** [comment]
Hi, thanks for your reply. The issue is that Se is in the active site. It is an issue for all tools in the autodock suites including Vina as well.

**Comment by diogomart** [comment]
Hi again, sorry i didn't reply quicker. You are right it isn't in Vina. The vdW radius of `S` in Vina is 2.0. For `Si` it's 2.2. For `P` it's 2.1. All vdW radii are defined to 1 decimal. Neither `S`, `Si`, or `P` participate in the H-bond or hydrophobic terms. If you need `Se` to be larger than `S` you can change it to either `Si` or `P`. It's very ugly, and untested, but it should work given the simplicity of the Vina scoring function.

**Comment by yifeng-li** [comment]
> Hi again, sorry i didn't reply quicker. You are right it isn't in Vina. The vdW radius of `S` in Vina is 2.0. For `Si` it's 2.2. For `P` it's 2.1. All vdW radii are defined to 1 decimal. Neither `S`, `Si`, or `P` participate in the H-bond or hydrophobic terms. If you need `Se` to be larger than `S` you can change it to either `Si` or `P`. It's very ugly, and untested, but it should work given the simplicity of the Vina scoring function.

Thanks for this workaround.
