### ISSUE TITLE
1.2.3 installers for Mac and Linux are not archives

### ISSUE THREAD

**Issue by mishaguy** [ccsb-scripps/AutoDock-Vina#127]
Hello,

When I download 1.23 for Mac and Linux from https://github.com/ccsb-scripps/AutoDock-Vina/releases, files come without tgz extensions. Adding tgz or tar.gz to file does not allow to open archive with tar.
How to use these installers?

Thanks,
Misha

**Comment by mishaguy** [comment]
I found out how to open it
thanks

**Comment by mishaguy** [comment]
Sorry, I thought I figured it out by adding gz but clicking on Mac just makes it cpgz.
How to open these files?
thanks

**Comment by diogomart** [comment]
Hi. They are not installers. These files are meant to be executed in the command line.

**Comment by mishaguy** [comment]
Hi Diogo,

Thanks for this.

Can I ask you not related question?
Do you know if there is MGL Tools compiled for Catalina, and higher? For 64 bit Mac.

Best,
Misha

Mikhael Guy
Research Scientist
Science Research Software Core
Yale Center for Research Computing
Yale University
P.O. Box 208107
Sterling Chemistry Laboratory
225 Prospect Street, Rm. 154
New Haven, CT 06520
203.436.8599
For questions related to scientific, analytical and computational software, please e-mail at ***@***.******@***.***>



On Aug 9, 2022, at 1:09 AM, Diogo ***@***.******@***.***>> wrote:



Hi. They are not installers. These files are meant to be executed in the command line.

**Comment by diogomart** [comment]
MGLTools is a collection of tools, I don't know if they all work on Catalina, sorry. The autodock mailing list might know: https://autodocksuite.scripps.edu/support/

**Comment by RomuloBarrosPI** [comment]
@diogomart , using Mac M1 and download the vina_1.2.2_macos_arm64 release, but I can't use it as an executable. Please, am I maybe forgetting something?

**Comment by diogomart** [comment]
@RomuloBarrosPI what error do you get?

**Comment by RomuloBarrosPI** [comment]
> @RomuloBarrosPI what error do you get?

@diogomart , thanks so much for your attention.
 
I get an error message saying there is no application set to opening the document “vina_1.2.2_macos_arm64”.

<img width="293" alt="Captura de Tela 2022-09-09 às 16 28 05" src="https://user-images.githubusercontent.com/33790246/189429964-b66fe2c8-2e70-46f8-ab0f-f200563b1951.png">

So it is like mac is seeing it as a simple document and not as an executable file.

**Comment by diogomart** [comment]
You need to run it from the command line, i.e. `./vina_1.2.2_macos_arm64`. You may need to give permission to execute with the `chmod` command. If you are not familiar with the command line, [this linux tutorial](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview) may help.

**Comment by RomuloBarrosPI** [comment]
This is just awesome. It almost did it! 

I typed this:`chmod 777 ./vina_1.2.2_macos_arm64`, and then `./vina_1.2.2_macos_arm64`. Had to tweak Mac's System Secutiry & Privacy to allow it to run. 

It ran, but I got this error: `'/usr/local/lib/libboost_system.dylib' (no such file)`

<img width="625" alt="Captura de Tela 2022-09-10 às 10 19 54" src="https://user-images.githubusercontent.com/33790246/189485203-4975d0c3-ad6d-46c2-a941-d26ee06df14b.png">

I gonna keep trying.

**Comment by RomuloBarrosPI** [comment]
Wow!! Got it @diogomart ! 

just running `brew install boost` did the job!

Thank you so much for your help! This may also help others with the same problem on a Mac M1 and M2 processors.

<img width="572" alt="Captura de Tela 2022-09-10 às 10 28 32" src="https://user-images.githubusercontent.com/33790246/189485558-b34c612e-981b-4468-9ebb-3aa9e2491551.png">

**Comment by diogomart** [comment]
Awesome!
