### ISSUE TITLE
Question: Is there a way to get the individual terms for the scoring function after docking using python?

### ISSUE THREAD

**Issue by EChung0111** [ccsb-scripps/AutoDock-Vina#128]
If I am correct, autodock vina generates the score of a ligand using the scoring function. Which is a linear equation that takes in several values and multiplies them by a specific weight then adds all the terms of the equation to get the score. Is there a way to get the numeric values of each of the terms used in scoring using the python bindings?

**Comment by diogomart** [comment]
There is no easy way to extract that information in Vina 1.2.*

Each term is multiplied by a weight, but then that is divided by `1 + w_rot * n_rot` where `w_rot` is a weight, and `n_rot` is the number of active rotatable bonds.

**Comment by EChung0111** [comment]
> 

Thank you for the quick reply

**Comment by diogomart** [comment]
Welcome!
