### ISSUE TITLE
How can I get log file in 1.2.x version

### ISSUE THREAD

**Issue by firesky123** [ccsb-scripps/AutoDock-Vina#129]
How can I get log file in 1.2.x version? In 1.1.2 can use **--log** options but in 1.2.x not have this options.

**Comment by diogomart** [comment]
You can redirect the standard output with `>`:
```sh
vina --config dock.conf > output.log
```

**Comment by firesky123** [comment]
Thanks for you and I will try it

**Comment by diogomart** [comment]
Welcome!
