### ISSUE TITLE
How to fix the 'Error: could not open "1.pdbqt" for reading.'

### ISSUE THREAD

**Issue by firesky123** [ccsb-scripps/AutoDock-Vina#130]
I have prepared the following configuration file.
```
receptor = 1.pdbqt
ligand = lig.pdbqt

center_x = 34
center_y = 3
center_z = 25.5

size_x = 86
size_y = 72
size_z = 69

num_modes = 20
energy_range = 5
exhaustiveness = 100
```

And run with the following command in Ubuntu 20.04.4 LTS
`./vina --config ./work/1/conf1.txt --out ./work/1/dock1.pdbqt > ./work/1/dock1.log`
but it is note that **Error: could not open "1.pdbqt" for reading.** But I try to use same commend and config file in Windows, it can be run.
And I try to change the pathway to **receptor = ./work/1/1.pdbqt**  but it not work.

**Comment by JonasLi-19** [comment]
maybe you should prepare the receptor.pdbqt(1.pdbqt) again with AutoDock Tools carefully. Or you could try move this pdbqt to the directory where "vina" is (in case you put the wrong path).

**Comment by diogomart** [comment]
I can't reproduce this issue. Based on @firesky123 description, setting `receptor = work/1/1.pdbqt` should work.
