### ISSUE TITLE
Problems about docking As atoms

### ISSUE THREAD

**Issue by Panzer-vor-08** [ccsb-scripps/AutoDock-Vina#131]
Hi there,
Thank you for providing this powerful and user-friendly tool!

When preparing pdbqt file with mk_prepare_ligand.py, I get an error message: 

> Traceback (most recent call last):
>   File "/home/u20301050178/miniconda3/envs/autodock-vina/bin/mk_prepare_ligand.py", line 290, in <module>
>     pdbqt_string = preparator.write_pdbqt_string()
>   File "/home/u20301050178/miniconda3/envs/autodock-vina/lib/python3.9/site-packages/meeko/preparation.py", line 204, in write_pdbqt_string
>     raise RuntimeError("Molecule not OK, refusing to write PDBQT\n\nLOG:\n%s" % self.log)
> RuntimeError: Molecule not OK, refusing to write PDBQT
> 
> LOG:
> atom number 33 has None type, mol name: BTK_arsenic_inhibitor_1

I checked my sdf file and found that the No.34 atom is As.
Since this script does not work, I generated the ligand-pdbqt file with `openbabel`. Using it as the input of vina, I receive this message:

> PDBQT parsing error: Atom type As is not a valid AutoDock type (atom types are case-sensitive).

 > ATOM     20 AS   UNL     1      -0.143   1.460  -2.321  0.00  0.00    +0.000 As

I also tried qvina-w and received error as well. 
Does that mean autodock is unable to deal with arsenic atoms?

**Comment by diogomart** [comment]
Hi, that's correct, autodock can't handle As

**Comment by Panzer-vor-08** [comment]
> Hi, that's correct, autodock can't handle As

Got it. Thanks for replying so soon!

**Comment by Panzer-vor-08** [comment]
Hi, 
I was able to add parameters in openbabel and MolKit packages for Arsenic manually, thus succeeded in running As-containing molecule in AutoDock4.2.6. I wonder if the same operation can be done for Vina or QVina? Could you please tell me which parameter file is fatal to Vina when reading undefined atoms?

**Comment by diogomart** [comment]
New parameters need to be hard-coded, e.g. https://github.com/ccsb-scripps/AutoDock-Vina/commit/df8ee9d765daa59b8ec5c27b35074b84460a5799

**Comment by Panzer-vor-08** [comment]
> New parameters need to be hard-coded, e.g. [df8ee9d](https://github.com/ccsb-scripps/AutoDock-Vina/commit/df8ee9d765daa59b8ec5c27b35074b84460a5799)

Thanks! I will take a good look at it! : )

**Comment by Panzer-vor-08** [comment]
> New parameters need to be hard-coded, e.g. [df8ee9d](https://github.com/ccsb-scripps/AutoDock-Vina/commit/df8ee9d765daa59b8ec5c27b35074b84460a5799)

I imitated this part of code editing, but the error message did not change. I tried deleting the lines about Si and found that vina was still able to handle Si atoms?

**Comment by diogomart** [comment]
Did you run `make clean` before compiling?
