### ISSUE TITLE
How do a student (who is new to this area) learn to build up a docking programe like AutoDock Vina?

### ISSUE THREAD

**Issue by JonasLi-19** [ccsb-scripps/AutoDock-Vina#132]
Maybe you could show the internal structure of Vina, and some internal codes here in GITHUB to teach us to build more docking programes.

**Comment by EChung0111** [comment]
Hi also a student, what do you mean by building a docking program? Do you mean developing new docking engines, with your own way of finding docked conformers and scoring them with your own scoring function, or do you mean writing a program that lets you do docking with autodock vina to improve your workflow?

**Comment by diogomart** [comment]
Closing as there isn't an issue with the code. The [autodock mailing list](https://autodocksuite.scripps.edu/support/) may be a better source of opinions on this topic.
