### ISSUE TITLE
python function "set_weights()" makes no change to vinardo's gird maps after I reset weights

### ISSUE THREAD

**Issue by Im-2012** [ccsb-scripps/AutoDock-Vina#134]
In my test, function "set_weights()"  will affect the results of vina's grid maps, just like the [users' documents](https://autodock-vina.readthedocs.io/en/latest/vina.html) says, "Set potential weights for vina or ad4 scoring function". However, it makes no change to vinardo's gird maps, can someone help me fix this problem?

**Comment by diogomart** [comment]
The weights have different names, e.g. `weight_gauss1` for vina, but `weight_vinardo_gauss1` for vinardo. Could this be it?
