### ISSUE TITLE
QUESTION: What is the likelihood that the vina python bindings are broken for the new python patch update.

### ISSUE THREAD

**Issue by EChung0111** [ccsb-scripps/AutoDock-Vina#135]
So recently there has been a patch update with python and it affects how int/str conversions work, putting a cap on those conversions to 4300 characters for non-base 2 ints. Is there a decent chance this could affect the python bindings for autodock vina? I would really appreciate an answer as I heavily depend on the autodock vina docking engine in my code

**Comment by diogomart** [comment]
Did you experience issues already? What is the Python version?
I don't think vina ever deals with ints that are large enough to require 4300 characters, so we should be OK.

**Comment by EChung0111** [comment]
no i did not experience any issues just wanted to know before updating python to the newest patch version
