### ISSUE TITLE
output message hiding

### ISSUE THREAD

**Issue by youngyanyoung** [ccsb-scripps/AutoDock-Vina#137]
Hi, I've been trying to use python binding of vina. And here is my question: when I run docking in parallel, is there any way to hide only the docking output message.

**Comment by diogomart** [comment]
Hi, what is it exactly that you want to hide?

**Comment by youngyanyoung** [comment]
> 
Thanks for replying! 
I want to hide the following message: 

Computing Vina grid ... done.
Performing docking (random seed: 1122952847) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -11.48          0          0
   2       -11.44      3.325      4.943
   3       -11.21       4.89      9.929

**Comment by diogomart** [comment]
I never tried this, but setting the verbosity to zero should do it.
```python
from vina import Vina
v = Vina(verbosity=0)
```

**Comment by youngyanyoung** [comment]
It works. Thanks a lot!
