### ISSUE TITLE
MacOS install 

### ISSUE THREAD

**Issue by cs942** [ccsb-scripps/AutoDock-Vina#14]
permissions denied with macos executable: ./vina_1.2.0_macos_x86_64 --help
source not found using miniconda: conda install -c conda-forge -c ccsb-scripps vina

your help with macOS installation would be greatly appreciated

**Comment by etaylorc** [comment]
I have also just received this error. When I received this error with vina 1.1.2, I was able to open the executable using the terminal with control+click, and that would give permissions and allow me to run vina. However, mac thinks that vina is a document, not an executable, so I am unable to run it in the terminal.

**Comment by atillack** [comment]
@cs942 @etaylorc Thanks for letting us know - this is something on our list to fix. Newer macOS versions make things a bit harder.

What works for me on Catalina and Big Sur currently is the following:
- set the file permissions with `chmod 755 ./vina_1.2.0_macos_x86_64`,
- then  try to run the executable with `./vina_1.2.0_macos_x86_64` and click "Cancel" at macOS's warning dialog that the developer cannot be verified
- right after that in System Preferences->Security&Privacy click on "Allow Anyway" for `vina_1.2.0_macos_x86_64`.
- run the executable with `./vina_1.2.0_macos_x86_64` and click on "Open" when asked if you're sure you want to open it and it will now run from then on

**Comment by jeeberhardt** [comment]
Hi cs942,

About conda, only the package for linux is available at this moment. So you want to use `pip` to install the macOS version.

We are still debating about temporarily dropping support for conda and distributing python packages for vina through PyPI only. From what I know,  conda does not allow us to statically link the Boost library (`boost-cpp`) and forced me to freeze the Boost library version to 1.74, which is far from ideal...
