### ISSUE TITLE
Ligand convert problem

### ISSUE THREAD

**Issue by lh12565** [ccsb-scripps/AutoDock-Vina#142]
Hi, I use 'prepare_ligand4.py' to convert small molecules from mol2 to pdbqt. I found some molecules changed their structures after converting to pdbqt, for example:
1.mol2:
![image](https://user-images.githubusercontent.com/24219321/196644046-0d34e446-5153-4c31-bfbb-814fb899d33d.png)
after convert (1.pdbqt):
![image](https://user-images.githubusercontent.com/24219321/196644362-2d5cbaf6-cc15-4b48-a973-915dd4387cf3.png)

I don't know if this will lead to incorrect docking result. Do I need to filter these molecules in the result?
Thanks!

**Comment by diogomart** [comment]
I recommend [meeko](https://github.com/forlilab/Meeko) instead of `prepare_ligand4.py`. The input needs to be 3D and protonated, and SD files are preferred to MOL2.

The PDBQT files do not define bonds, so your 2D pictures could be the drawing program guessing bonds from (2D?) inputs.

**Comment by lh12565** [comment]
> I recommend [meeko](https://github.com/forlilab/Meeko) instead of `prepare_ligand4.py`. The input needs to be 3D and protonated, and SD files are preferred to MOL2.
> 
> The PDBQT files do not define bonds, so your 2D pictures could be the drawing program guessing bonds from (2D?) inputs.

Hi, I convert sdf to mol2 file by obabel like below, then use the prepare_ligand4.py to convert to pdbqt.
```
obabel all.sdf -O all.mol2 --gen3d --AddPolarH --partialcharge MMFF94
obabel all.mol2 -O mol2/single.mol2 -m
cd mol2
for db in {1..2000}
do
pythonsh prepare_ligand4.py  -l single${db}.mol2 -o ../pdbqt/single${db}.pdbqt
done
```
so I use the 3D structure to convert to PDBQT, I don't know why it happened. I will try to use meeko to convert it. Do you have any recommended methods to convert it to 3D and protonated. Could I use obabel to convert it like below, or something else?
```
obabel all.sdf -O all_3d_proton.sdf --gen3d --AddPolarH --partialcharge MMFF94
```
Thanks!

**Comment by diogomart** [comment]
> Do you have any recommended methods to convert it to 3D and protonated. Could I use obabel to convert it like below, or something else?

RDKit's ETKDG followed by UFF minimization does a reasonable job for coordinates. RDKit also adds hydrogens. Here's a Python snippet:
```python
from rdkit import Chem
from rdkit.Chem import rdDistGeom
from rdkit.Chem import rdForceFieldHelpers

mol = Chem.MolFromMol2File("molecule.mol2")
mol_h = Chem.AddHs(mol)
etkdgv3 = rdDistGeom.ETKDGv3()
rdDistGeom.EmbedMolecule(mol_h, etkdgv3)
rdForceFieldHelpers.UFFOptimizeMolecule(mol_h)
print(Chem.MolToMolBlock(mol_h), end='')
```
