### ISSUE TITLE
Ligand converting with hydration adding bad bonds

### ISSUE THREAD

**Issue by tanzibin108** [ccsb-scripps/AutoDock-Vina#144]
Hello,
When I was trying to preparing my ligand by adding water molecules, it added too many waters and some of them are too close. When I open the pdbqt files with chimerax it shows bad bonds between water and water, water and my compound. One possible reason could be that my compound has too many H-bond donors and acceptors. it there a way to limit the numbers of water added so they don't get too close? What about those strange bonds? is it because Chimerax does not interpret bonding correctly? Will this interfere my results?
Thanks
<img width="735" alt="截屏2022-10-23 下午4 16 04" src="https://user-images.githubusercontent.com/95889442/197416113-ca1d09ca-c866-4975-a323-346480dca3d0.png">

**Comment by diogomart** [comment]
Pseudo waters are added to all H-bond sites on the ligand, even if they end up overlapping with the ligand or other waters. There is no option to limit the number of waters. Hydroxyls get 3 waters, ether oxygens get 2, and amines get 3, so this is how it should look like for a molecule with these many H-bond sites.

The PDBQT format does not define bonds, so any depicted bond, real or not, is guessed by the visualization program. Waters do not interact with ligand atoms, nor with other waters.
