### ISSUE TITLE
How to generate a general affinity map (or .dlg file)?

### ISSUE THREAD

**Issue by ale94mleon** [ccsb-scripps/AutoDock-Vina#147]
Hi,
I am working with [MolDrug](https://github.com/ale94mleon/MolDrug) (which is a drug-oriented optimizer on the chemical space). During the optimization steps I am generation new molecules that I do not know what type of atoms they will have.

One of the project is related with a zinc metalloprotein. I was following the [Docking with zinc metalloproteins](https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html#docking-with-zinc-metalloproteins) tutorial. However the step [3. Generating affinity maps](https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html#generating-affinity-maps) will be too time consuming. I am wondering if there is a way to generate only one time the grid maps for all the possible ligand_types of atoms that accept AutoDock and use this grid for all the generated molecules.

Of course, if the new genereated molecule does not have any valid AutoDock atom type we could just not perform the docking.

A lot of thanks in advance.

**Comment by ale94mleon** [comment]
Hi, @diogomart 
Thanks for your quick replay. I have a final question. In the [script](https://github.com/diogomart/write-autogrid-config/blob/main/write-gpf.py), if I got it right, the definition of the atom types for the receptor is:

`supported_atypes = ['HD', 'C', 'A', 'N', 'NA', 'OA', 'F', 'P', 'SA', 'S', Cl', 'Br', 'I', 'Mg', 'Ca', 'Mn', 'Fe', 'Zn', 'H', 'OC']`

And for the ligand is the line inside of the string definition of the `gpf`:

`ligand_types HD C A N NA OA F P SA S Cl Br I H`

I guess that it is not expected that the ligand has metal ions but what about `OC` atom type. What is that atom.?

**Comment by diogomart** [comment]
The `OC` is an experimental type, the preparation tools described in the [docs](https://autodock-vina.readthedocs.io/en/latest/) do not use it. Autogrid will complain about `OC` atoms in the receptor.

> I guess that it is not expected that the ligand has metal ions.

That's correct, this script does not expect metals in the ligand.

**Comment by ale94mleon** [comment]
Thanks again! I will close here
