### ISSUE TITLE
prepare_receptor removes zinc (ZN) from the structure 

### ISSUE THREAD

**Issue by rczerminski-valo** [ccsb-scripps/AutoDock-Vina#148]
prepare_receptor (from ADFRsuite_x86_64Darwin_1.0) removes zinc from the structure - please advise

```
$ ./ADFRsuite_x86_64Darwin_1.0/bin/prepare_receptor -r protein.pdb
'G ' apparently composed of not std residues. Deleting 
$ grep " G " protein.pdb
HETATM 4160 ZN    ZN G   1     -10.017 -36.970 -30.036  1.00 29.52          ZN2+
HETATM 4161 ZN    ZN G   2      -9.524 -33.581 -30.517  1.00 28.82          ZN2+
$ 
```

**Comment by rczerminski-valo** [comment]
Oh, it looks like it should be

`prepare_receptor -r protein.pdb -U -U nphs_lps_waters`

**Comment by diogomart** [comment]
You can fork our GitHub repos, make changes on your public repo, and request that we pull your changes into our repos using the _pull request_ button on the GitHub interface.
