### ISSUE TITLE
batch mode does not work?

### ISSUE THREAD

**Issue by rczerminski-valo** [ccsb-scripps/AutoDock-Vina#15]
> _Support of simultaneous docking of multiple ligands and batch mode for virtual screening_

I am trying to dock multiple ligands using --batch option. My understanding is that input .pdbqt file for this to work should contain multiple ligands following the pattern below:

MODEL 1
... molecule 1 ...
ENDMDL
MODEL 2
... molecule 2 ...
ENDMDL

Maybe my understanding is not correct and some other mechanism should be used or there is a bug, since when I give a .pdbqt file with multiple ligands as an input it fails with "An unknown error occurred" error message.

I attached vina-An-unknown-error-occurred-bug.tar.gz file which should allow to reproduce the issue.
[vina-An-unknown-error-occurred-bug.tar.gz](https://github.com/ccsb-scripps/AutoDock-Vina/files/6909186/vina-An-unknown-error-occurred-bug.tar.gz)

**Comment by jeeberhardt** [comment]
Hi rczerminski-valo,

Sorry about this, the `batch`mode lacks currently some documentation... hopefully this will be fixed very soon. For a quick example about how the `batch` mode works, please look at issue #11. In your example, you can only have one molecule per PDBQT file.

Hope it helps.

Best,
Jerome.

**Comment by rczerminski-valo** [comment]
I see. So, if this is the case, my understanding is that the only difference between --ligand and --batch modes is that --batch requires --dir argument with designated directory to write docked ligand files to - is it correct?

**Comment by jeeberhardt** [comment]
Yep, exact! ;)

**Comment by rczerminski-valo** [comment]
How difficult would it be to modify code to allow for input files with multiple ligands and multi-ligand, multi-pose output files? As far as I can tell this is rather common usage scenario currently accomplished by scripting around vina executable.

**Comment by jeeberhardt** [comment]
I think the greater question here is not about whether or not we could, but if we should.

The PDB format (which is the basis of the PDBQT format) is pretty clear about the use of [`MODEL/ENDMDL`](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#MODEL) keywords:
> The MODEL record specifies the model serial number when multiple models of the same structure are presented in a single coordinate entry, as is often the case with structures determined by NMR.

We are aware that many people are using this trick to generate PDBQT files with multiple ligands (along side all the different flavors of the PDB format...), but multiple issues arise from that 1) how would we differentiate multiple poses of the same ligand from different ligands and 2) more importantly the file won't be in PDB(QT) format anymore so you will face the eventual interoperability issues with other programs.

Jerome.

**Comment by rczerminski-valo** [comment]
Interoperability issues are definitely important, and yes using PDBQT-like format to store multi-ligand, multi-pose output might be not the good way forward. Some other format better suited for this purpose may offer the better solution. I do not know what would be the most suitable one for vina, but some possibilities are, I guess, [SDF](https://en.wikipedia.org/wiki/Chemical_table_file), [CML](https://en.wikipedia.org/wiki/Chemical_Markup_Language)? Do you think any of these would be suitable? or some other format?

**Comment by diogomart** [comment]
Hi Ryszard,
SDF and MOL2 files would be great, but unfortunately it's unlikely we will do it in the near future. There would be a similar problem though, because they don't explicitly distinguish multiple entries as a) conformers of a given molecule or as b) different molecules. So the software reading these files would have to guess based on the molecules names or some other way.

**Comment by rczerminski-valo** [comment]
With SDF one solution might be to have simple and well documented convention (so the "consumer" of these files does not have to guess what is what) in the multi-ligand, multi-pose output there could be records clearly marking different molecules and poses associated with them. For example if we have 2 molecules with 3 poses per molecule we would have 6 MOL records in SDF: with (mseq, pseq) fields = (1,1) (1,2) (1,3) (2,1), (2,2) (2,3)
[...]
>  <mseq>
1
> <pseq>
1
[...]
>  <mseq>
1
> <pseq>
2
[...]

**Comment by rczerminski-valo** [comment]
JSON based format (ideally some agreed upon standard) might be an interesting possibility as well. There is some discussion around this issue here https://github.com/rdkit/rdkit/issues/1137 ... SDF seems however to be the simplest short (or medium) term solution.
