### ISSUE TITLE
Ligand protonation and 3D conformer generation steps prior to PDBQT conversion

### ISSUE THREAD

**Issue by SabrinaMoffit** [ccsb-scripps/AutoDock-Vina#151]
I'd be required to do a high throughput docking for my project. I'm now going through the tutorial on basic docking first to see how Vina works. In the ligand preparation step, I used RDKit to add hydrogens and generate a 3D conformer for the ligand and then converted it to a pdbqt file using Meeko.

My RDKit script is as follows:
```
from rdkit import Chem
from rdkit.Chem import rdDistGeom
from rdkit.Chem import rdForceFieldHelpers

# Providing the ligand's SMILES
smiles_mol = "Cc1ccc(cc1Nc2nccc(n2)c3cccnc3)NC(=O)c4ccc(cc4)CN5CCN(CC5)C"

# Reading the ligand's SMILES
mol = Chem.MolFromSmiles(smiles_mol)

# Adding hydrogens
mol_h = Chem.AddHs(mol)

# Generating conformer using distance geometry and then implementing ETKDG to correct the conformer 
etkdgv3 = rdDistGeom.ETKDGv3()
rdDistGeom.EmbedMolecule(mol_h, etkdgv3)

# Cleaning up the conformer using a force field ie. Universal Force Field (UFF)
rdForceFieldHelpers.UFFOptimizeMolecule(mol_h)

# Generating the conformer
conformer = Chem.MolToMolBlock(mol_h)

# Saving the output to a file called "1iep_ligand.mol"
output = open("1iep_ligand.mol", "w")
output.write(conformer)
output.close()
```
I then used Meeko to convert the RDKIt molecule to PDBQT by running,
`mk_prepare_ligand.py -i ~/Desktop/AutoDock-Vina-develop/1iep_ligand.mol -o ~/Desktop/AutoDock-Vina-develop/QTligand/1iep_ligand.pdbqt  --remove_smiles
`.
However, the output I generated (shown below), `1iep_ligand.pdbqt`, is not exactly the same as the one provided in `example/basic_docking/solution/1iep_ligand.pdbqt`. Is this because the protonation and 3D conformer generation steps differ? Could you please advise on these two steps and include them in the tutorial? Btw, how do I tell if my pdbqt file is good/acceptable for Vina docking?
```
REMARK Flexibility Score: inf
ROOT
ATOM      1  C   UNL     1      -4.721   2.889  -4.100  1.00  0.00     0.046 C 
ATOM      2  C   UNL     1      -3.449   2.431  -3.438  1.00  0.00    -0.027 A 
ATOM      3  C   UNL     1      -2.220   2.961  -3.864  1.00  0.00     0.008 A 
ATOM      4  C   UNL     1      -1.026   2.546  -3.274  1.00  0.00     0.026 A 
ATOM      5  C   UNL     1      -1.031   1.572  -2.268  1.00  0.00     0.043 A 
ATOM      6  C   UNL     1      -2.258   1.046  -1.829  1.00  0.00     0.052 A 
ATOM      7  C   UNL     1      -3.469   1.468  -2.406  1.00  0.00     0.046 A 
ENDROOT
BRANCH   7   8
ATOM      8  N   UNL     1      -4.712   0.886  -1.976  1.00  0.00    -0.324 N 
ATOM      9  H   UNL     1      -5.432   0.653  -2.697  1.00  0.00     0.170 HD
BRANCH   8  10
ATOM     10  C   UNL     1      -5.073   0.717  -0.598  1.00  0.00     0.227 A 
ATOM     11  N   UNL     1      -4.314   1.260   0.392  1.00  0.00    -0.221 NA
ATOM     12  N   UNL     1      -6.217   0.053  -0.281  1.00  0.00    -0.213 NA
ATOM     13  C   UNL     1      -4.671   1.134   1.695  1.00  0.00     0.117 A 
ATOM     14  C   UNL     1      -6.618  -0.107   1.011  1.00  0.00     0.077 A 
ATOM     15  C   UNL     1      -5.834   0.446   2.037  1.00  0.00     0.049 A 
BRANCH  14  16
ATOM     16  C   UNL     1      -7.881  -0.837   1.294  1.00  0.00     0.019 A 
ATOM     17  C   UNL     1      -8.903  -0.880   0.329  1.00  0.00     0.013 A 
ATOM     18  C   UNL     1      -8.087  -1.521   2.508  1.00  0.00     0.121 A 
ATOM     19  C   UNL     1     -10.089  -1.568   0.589  1.00  0.00     0.021 A 
ATOM     20  N   UNL     1      -9.251  -2.187   2.733  1.00  0.00    -0.264 NA
ATOM     21  C   UNL     1     -10.247  -2.221   1.810  1.00  0.00     0.111 A 
ENDBRANCH  14  16
ENDBRANCH   8  10
ENDBRANCH   7   8
BRANCH   5  22
ATOM     22  N   UNL     1       0.215   1.159  -1.680  1.00  0.00    -0.322 N 
ATOM     23  C   UNL     1       0.480  -0.182  -1.234  1.00  0.00     0.255 C 
ATOM     24  H   UNL     1       1.016   1.830  -1.716  1.00  0.00     0.170 HD
ATOM     25  O   UNL     1      -0.250  -1.130  -1.632  1.00  0.00    -0.269 OA
BRANCH  23  26
ATOM     26  C   UNL     1       1.634  -0.473  -0.350  1.00  0.00     0.040 A 
ATOM     27  C   UNL     1       2.168  -1.772  -0.289  1.00  0.00     0.014 A 
ATOM     28  C   UNL     1       2.197   0.530   0.458  1.00  0.00     0.014 A 
ATOM     29  C   UNL     1       3.251  -2.057   0.547  1.00  0.00     0.006 A 
ATOM     30  C   UNL     1       3.277   0.243   1.297  1.00  0.00     0.006 A 
ATOM     31  C   UNL     1       3.822  -1.050   1.341  1.00  0.00    -0.034 A 
BRANCH  31  32
ATOM     32  C   UNL     1       4.982  -1.367   2.262  1.00  0.00     0.120 C 
BRANCH  32  33
ATOM     33  N   UNL     1       6.310  -1.056   1.690  1.00  0.00    -0.297 NA
ATOM     34  C   UNL     1       6.520   0.372   1.417  1.00  0.00     0.100 C 
ATOM     35  C   UNL     1       6.661  -1.891   0.523  1.00  0.00     0.100 C 
ATOM     36  C   UNL     1       8.023   0.646   1.210  1.00  0.00     0.099 C 
ATOM     37  C   UNL     1       7.933  -1.377  -0.190  1.00  0.00     0.099 C 
ATOM     38  N   UNL     1       8.767  -0.522   0.677  1.00  0.00    -0.304 NA
ATOM     39  C   UNL     1       9.431  -1.296   1.741  1.00  0.00     0.105 C 
ENDBRANCH  32  33
ENDBRANCH  31  32
ENDBRANCH  23  26
ENDBRANCH   5  22
TORSDOF 7
```

**Comment by rwxayheee** [comment]
Hi @SabrinaMoffit, Vina user here and I usually protonate ligands prior to the prepare ligand step even though I believe Vina's scoring function does not account for explicit H.. The protonation of N may introduce new stereochemistry center that is not defined in canonical smiles, and that is why I protonate and write amine diastereomers if there are any. Your pdbqt seems reasonable for docking, the only difference I see is: 
1. The sample pdbqt has unique atom names which are convenient for analysis in some cases. 
The default of mk_prepare_ligand.py **won't assign unique atom names** (if I'm right), and I'm not so sure how the sample pdbqt was generated with unique atom names. For previous versions of AutoDock, prepare_ligand4.py has a -w option to do this. But -w in mk_prepare_ligand.py is to write hydrated pdbqt.. 
2. The sample pdbqt has the two tertiary amines protonated so there are two more Hs than yours. Depending on what geometry optimization method you use to preprocess the ligand, that might have an effect on the optimized geometry. But again, I don't see much difference other than that and your pdbqt should be ok for docking. But I agree that for more complicated cases than simple amines especially those with resonance structure (amidines?) protonation and 3D conformer generation can be crucial for ligand preparation.

**Comment by diogomart** [comment]
> Could you please advise on these two steps and include them in the tutorial?
At some point, we will release a tool that handles ligand hydrogens. Current options are OpenBabel with option `-p`, ChemAxon's `molconvert`, Schrodinger's LigPrep, and for sure there are more options out there.
