### ISSUE TITLE
meeko 0.4.0 fails to prepare sample ligand

### ISSUE THREAD

**Issue by AenBleidd** [ccsb-scripps/AutoDock-Vina#153]
Taking the sample ligand https://github.com/ccsb-scripps/AutoDock-Vina/blob/develop/example/basic_docking/data/1iep_ligand.sdf.
In docu https://github.com/ccsb-scripps/AutoDock-Vina/blob/develop/docs/source/docking_basic.rst it's said:
`mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt`
On Meeko 0.2.0 everything was fine.
After upgrade to Meeko 0.4.0 now I have this error:
```
mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt
/home/lawliet/.local/lib/python3.8/site-packages/meeko/preparation.py:109: RuntimeWarning: Skipping mol (name=STI): has implicit hydrogens
  warnings.warn("Skipping mol (name=%s): has implicit hydrogens" % name, RuntimeWarning)
Traceback (most recent call last):
  File "/home/lawliet/.local/bin/mk_prepare_ligand.py", line 303, in <module>
    pdbqt_string = preparator.write_pdbqt_string()
  File "/home/lawliet/.local/lib/python3.8/site-packages/meeko/preparation.py", line 205, in write_pdbqt_string
    raise RuntimeError("Molecule not OK, refusing to write PDBQT\n\nLOG:\n%s" % self.log)
RuntimeError: Molecule not OK, refusing to write PDBQT

LOG:
molecule has implicit hydrogens
```

Is this sample not correct anymore or am I missing any additional command like parameter that is required now?

**Comment by diogomart** [comment]
The sample is not correct anymore. Thank you for finding this.

Since `v0.3.0` meeko requires input molecules to have explicit hydrogens. We should have added this error message back then.

I've updated the sample in the Vina repository.

**Comment by AenBleidd** [comment]
@diogomart, thank you for the quick fix. I can confirm now `mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt` works successfully.
