### ISSUE TITLE
Dry.py error when running an hydrated docking (Autodock)

### ISSUE THREAD

**Issue by afsp22** [ccsb-scripps/AutoDock-Vina#157]
Hi everyone!
I'm trying to run an hydrated docking protocol. In the last step, I've to run dry.pt using the command:
$ python dry.py -c -r protein.pdbqt -m protein.W.map -i ligand_HYDRO_protein.dlg

 but I'm getting this error message:

 File "dry.py", line 1184, in <module>
    grid = getmap(grid)
  File "dry.py", line 690, in getmap
    data = array(data, 'f').reshape(pts[2], pts[1], pts[0])
TypeError: 'float' object cannot be interpreted as an index

I tried to replace the pts[i] by int(pts[i]), but now I have a different error message:

 File "dry.py", line 1194, in <module>
    harvest, affinity = getpoints(grid, coord(w), distance = 1.0) # angstroms
  File "dry.py", line 739, in getpoints
    harvesting.append( data[z,y,x] )
IndexError: index 41 is out of bounds for axis 0 with size 41

Can someone help me solve this issue? Thank you very much!

**Comment by domiko96** [comment]
Exactly the same problem here. Did you ever solve this?

**Comment by domiko96** [comment]
Seems like various people run into this, see https://github.com/ccsb-scripps/AutoDock-Vina/issues/82
Maybe it is a numpy / python environment issue.
Somebody reported to be able to run it via anaconda. I tried this as well with no luck

**Comment by diogomart** [comment]
Fixed in #202. Thanks @domiko96 :+1:
