### ISSUE TITLE
parse error for protein

### ISSUE THREAD

**Issue by futianfan** [ccsb-scripps/AutoDock-Vina#16]
Dear author, 

thanks for your great package, however, when i use vina, 

v = Vina(sf_name='vina')
v.set_receptor(rigid_pdbqt_filename=xxx)

it get the error 

"terminate called after throwing an instance of 'parse_error'
Aborted (core dumped)", 

do you know what is the reason? thanks

**Comment by jeeberhardt** [comment]
Hi Tianfan,

My best guess would be that there is an issue in your receptor PDBQT file. But hard to say without seeing it. Could you try the following example?

- Tutorial: https://autodock-vina.readthedocs.io/en/latest/docking_python.html
- Input files: https://github.com/ccsb-scripps/AutoDock-Vina/tree/develop/example/python_scripting
