### ISSUE TITLE
Ligand name not printed in batch mode

### ISSUE THREAD

**Issue by cpayal** [ccsb-scripps/AutoDock-Vina#161]
Hi 

I am using flex/rigid dock (both) with vina in batch mode. The command I am using is as follows:
`vina --receptor rigid_rec.pdbqt --flex flex_rec.pdbqt --batch ligands_pdbqt/*.pdbqt --config vina_dock.config --exhaustiveness 8 --dir  flex_test/ --cpu 16 --verbosity 2 >> flex_verbose.log`

The ligands names are not printed on top of results, but the number of ligands are. 

```
Scoring function : vina
Rigid receptor: jh2_wt_apo_equil_rigid.pdbqt
Flex receptor: jh2_wt_apo_equil_flex.pdbqt
**Ligands (batch mode): 22 molecules**
Grid center: X 45.528 Y 49.887 Z 54.092
Grid size  : X 24 Y 24 Z 24
Grid space : 0.375
Exhaustiveness: 8
CPU: 16
Verbosity: 2

Computing Vina grid ... done.
Performing docking (random seed: 1839840224) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
done.
```
Is this a bug or a known feature? How do I have the scores accountable by the ligand names ?

Thanks

**Comment by diogomart** [comment]
Hi, yes, the ligand name should be printed. Out of curiosity, do you have a specific use for the ligand names in the STDOUT?

**Comment by diogomart** [comment]
Sorry, I had missed this part:
> How do I have the scores accountable by the ligand names ?

The scores are in the output PDBQT files written to `--dir flex_test/`

**Comment by cpayal** [comment]
That makes sense, but still it would be good to have the ligand names printed out in the STDOUT for an overall comparision of the best scores/poses of all compounds in a set, especially when doing a high throughput virtual screening.

Thanks
