### ISSUE TITLE
`np.int` not supported by numpy

### ISSUE THREAD

**Issue by forrestjgq** [ccsb-scripps/AutoDock-Vina#166]
Hello:

In latest numpy versions, `np.int` is not supported, which will fail python examples:
https://github.com/ccsb-scripps/AutoDock-Vina/blob/develop/build/python/vina/vina.py#L260

Suggest using `np.int_` instead, or just `int`

see https://numpy.org/doc/1.22/reference/arrays.scalars.html#numpy.int_

**Comment by forrestjgq** [comment]
ok, there is a PR solving this issue:
https://github.com/ccsb-scripps/AutoDock-Vina/pull/165

close now.

**Comment by tiffanyhuff** [comment]
Hello,

I also ran into this issue. I found that using 'np.int_' instead of 'np.int' on line 260 resolved the error, as well as switching to an earlier version of NumPy.
