### ISSUE TITLE
parse error for the ligands

### ISSUE THREAD

**Issue by avnikonenko** [ccsb-scripps/AutoDock-Vina#17]
Dear author,
Thank you for the AutoDock Vina 1.2!
I've run docking for about 1700 ligands using your vina python module and most of them was successfully docked  but 9 had a problem with the command `v.set_ligand_from_file('someid.pdbqt')`, it gives  _"terminate called after throwing an instance of 'stream_parse_error' "._
The most inconvenient thing when it happens the error does not give traceback and interrupt program but just freezes it. 
_Version info:_
Python 3.7
Open Babel 3.1.0
vina 1.2.0.dev3
_The code is:_
```
v = Vina(sf_name='vina', cpu=32, seed=1024, no_refine=False, verbosity=1)
v.set_receptor(rigid_pdbqt_filename='receptor.pdbqt')
v.set_ligand_from_file('someid.pdbqt')
v.compute_vina_maps(center=[x, y, z], box_size=[x_size, y_size, z_size], spacing=1)
v.dock(exhaustiveness=32, n_poses=9)
v.write_poses(pdbqt_filename=output, overwrite=True)
```
 Also I tried to run this problem ligands using binaries and it gives error _"An unknown error occurred."_.
 Pdbqt convertation was done by the command  `mk_prepare_ligand.py -i someid.sdf -m -o someid.pdbqt`
 Additional question is - can I use _-m_ flag not only for the preparing the macrocyclic but for all ligands?
 Because I have a set of the ligands and only part of them are macrocyclic.
 Ligand files are attached in the pdbqt and sdf formats:
[pdbqt.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/6918468/pdbqt.zip)
[sdf.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/6918478/sdf.zip)

 Could you help me please?

**Comment by diogomart** [comment]
Hello,

Thanks for reporting this.

Yes, you can use the `-m` flag for preparing any ligand including non-macrocyclic ones.

I think you are using an older version of Meeko, which stills assigns "AG" types for macrocycle closure. Vina supports only CGn/Gn pairs, with n = 1, 2, 3, or 4. You can use the `dev` branch from here: https://github.com/ccsb-scripps/Meeko/tree/dev/meeko.

However, Vina support breaking of C-C bonds only (non-aromatic carbons). For opening the 7-membered rings in the molecules you posted we would need new atom types, like the "AG" for aromatic carbons from the older Meeko version. Unfortunately it is not possible to sample these 7-member rings with Vina. Thus, using the older Meeko without enabling macrocyce sampling will yield the same result as the latest Meeko version.

Best regards,
