### ISSUE TITLE
Amides in macrocycles

### ISSUE THREAD

**Issue by pwging13** [ccsb-scripps/AutoDock-Vina#170]
It seems as thought amides are not held to a planar geometry when they are part of a macrocycle.  6 and smaller member rings seem to be fine, but 7 and up give me rotated amide bonds unless I use --rigid_macrocycles while preparing ligand pdbqt files.

Is this a known issue?  I tried using the --rigidify_bonds_smarts flag while preparing ligands to rigidify all amides (which should be the default behavior I thought), but that flag gave me trouble.

Any work arounds?

**Comment by diogomart** [comment]
Amide bonds are made rotatable only when the amide nitrogen has two non-hydrogen substituents and those substituents are different. While this lead to non-planar amides, which is bad, it allows both planar conformers to be sampled. Whether or not the amide N-C bond is part of a macrocycle does not affect the rotatable/non-rotatable status. To always keep amides rigid, use:
`--rigidify_bonds_smarts "O=[CX3][NX3]" --rigidify_bonds_indices 2 3`
If this doesn't work, or if I misunderstood the problem, please provide an example so I can reproduce the issue.
