### ISSUE TITLE
Multi-ligand docking error according to the manual

### ISSUE THREAD

**Issue by jincanzuitongfeng** [ccsb-scripps/AutoDock-Vina#180]
![7bd05fae5f7d007428308b48c84277b](https://user-images.githubusercontent.com/89511871/221744764-c6131a9f-dc5c-4f65-8f48-b541200a764d.png)
![250bba11e2cd36f5569eeb3e468bb98](https://user-images.githubusercontent.com/89511871/221744782-ad71f97d-dc84-4222-8dea-32cd5591af47.png)
One picture is in the manual, and the other is what I entered in cmd, but it does report an error

**Comment by rwxayheee** [comment]
Hi, 
If your config file is named "config.txt", the way to use it is: 
`vina.exe --config config.txt`
