### ISSUE TITLE
An IndexError occurred after using dry.py in hydrated docking

### ISSUE THREAD

**Issue by ChemBioMax** [ccsb-scripps/AutoDock-Vina#182]
Hello, everyone.
I have used a standard protocol listed in this artical (doi: 10.1038/nprot.2016.051) to carry out docking with explict waters. When my docking finished, I used dry.py to extract and score my results. But it reminded me there were an error showed as below. As a result, I can't get the file called ligand_LELC_DRY_SCORED.pdbqt. How to solve this problem? 

Traceback (most recent call last):
  File "dry.py", line 1194, in <module>
    harvest, affinity = getpoints(grid, coord(w), distance = 1.0) # angstroms
  File "dry.py", line 739, in getpoints
    harvesting.append( data[z,y,x] )
IndexError: index 61 is out of bounds for axis 2 with size 61

**Comment by TANGLi83-star** [comment]
Yes, I encountered the same issue, please tell me your final solution, thanks!

**Comment by diogomart** [comment]
Fixed in #202. Thanks @domiko96 :+1:
