### ISSUE TITLE
Vinardo Scoring Function

### ISSUE THREAD

**Issue by GasparPinto** [ccsb-scripps/AutoDock-Vina#186]
Hi, 

I am getting this error:

ERROR: Cannot do the global search. Affinity maps were not initialized.

I am trying to run a batch job with the command 
vina --receptor rigid.pdbqt  --flex flex.pdbqt --scoring vinardo --batch ligands/*.pdbqt --config config.txt --exhaustiveness 64 --dir results

The same error occurs when I change "--receptor rigid.pdbqt" to "--maps rigid"

The first command works perfectly fine without the "--scoring vinardo". 

Thank you in advance for the help

**Comment by diogomart** [comment]
Thank you for reporting! Will post back when fixed :-)

**Comment by diogomart** [comment]
Fixed in 773f0fe01cb51db310ddc3d1754593ff9564039b

**Comment by RJ-Li** [comment]
> Hi,
> 
> I am getting this error:
> 
> ERROR: Cannot do the global search. Affinity maps were not initialized.
> 
> I am trying to run a batch job with the command vina --receptor rigid.pdbqt --flex flex.pdbqt --scoring vinardo --batch ligands/*.pdbqt --config config.txt --exhaustiveness 64 --dir results
> 
> The same error occurs when I change "--receptor rigid.pdbqt" to "--maps rigid"
> 
> The first command works perfectly fine without the "--scoring vinardo".
> 
> Thank you in advance for the help

Sorry to interrupt you, but I wonder why you use vinardo to do flexible docking jobs rather than vina socring funtion, is there any rule or experiences of this?

**Comment by GasparPinto** [comment]
I was 

> > Hi,
> > I am getting this error:
> > ERROR: Cannot do the global search. Affinity maps were not initialized.
> > I am trying to run a batch job with the command vina --receptor rigid.pdbqt --flex flex.pdbqt --scoring vinardo --batch ligands/*.pdbqt --config config.txt --exhaustiveness 64 --dir results
> > The same error occurs when I change "--receptor rigid.pdbqt" to "--maps rigid"
> > The first command works perfectly fine without the "--scoring vinardo".
> > Thank you in advance for the help
> 
> Sorry to interrupt you, but I wonder why you use vinardo to do flexible docking jobs rather than vina socring funtion, is there any rule or experiences of this?

Not really, I was just playing around to get acquainted with Vina and its offspring tools. No reason other than that...
