### ISSUE TITLE
Negative charge not being conserved in Auto Dock Vina

### ISSUE THREAD

**Issue by kjk462** [ccsb-scripps/AutoDock-Vina#188]
Hey everyone, I have been trying to dock purpurin into the protein I’m working with using auto dock vina. I have conferred a negative charge onto the C2 hydroxyl, to mimic and reproduce previously conducted wet lab experiments. However, when I input the modified purpurin into auto dock tools to prepare the pdbqt file, the software wants to put an OH where the negative oxygen should be. I have tried deleting the hydrogen manually, but auto dock tools still wants to treat it as a hydroxyl instead of a negative oxygen. Auto dock tools calculated the gasteiger charge of the molecule and it said it was 0, which is contrary to Pymol’s -1. So I was wondering if anyone here had a suggestion on how to fix it.

**Comment by diogomart** [comment]
Hi, You could try this: https://github.com/forlilab/Meeko

Note that the vina scoring function ignores partial charges, and hydrogens serve only to type their parent atoms as H-bond donors.
