### ISSUE TITLE
Which command line can work as the dockedtopdbq in Autodock3

### ISSUE THREAD

**Issue by DooYal** [ccsb-scripps/AutoDock-Vina#191]
I want to convert the docked dlg file into pdb format, however, the current approach is mostly based on GUI windows. Now I need the batch process, so the commandline is necessary, I google the commandline, the answer "dockedtopdbq xxx" is based on Autodock3, [,](http://www.csb.yale.edu/userguides/datamanip/autodock/html/Using_AutoDock_305.1c.html), which I can not find in the current version of Autodock and the releated software.
Maybe the function has a new name, so which command line can work as the dockedtopdbq in Autodock3?

**Comment by diogomart** [comment]
Strongly recommend `mk_export.py` from https://github.com/forlilab/meeko to convert to SDF instead of PDB. This will preserve bond orders.
