### ISSUE TITLE
Vina environment installation error in Conda "Invalid specifier: '>=3.5.*'"

### ISSUE THREAD

**Issue by dnago4** [ccsb-scripps/AutoDock-Vina#195]
Hello
Been trying to get the 'vina' env set up (Anaconda 2.4.0/Windows10/Ubuntu 20.04 on WSL) per instructions but keep erroring out with the following message:

Version found 1.2.3 (from __init__.py)
      error in vina setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'

The executable is fine (can get response with '--version') but can't get the Python package going. In a different package installation I had edited the '>=3.5*' for 'python_requires' to '>=3.5' (multiple scripts) and the installation went fine.

I downloaded the vina-1.2.3-py311hac087fc_2.tar.bz2 archive (that 'pip install' does not process anyway) to try to edit out the offending '>=3.5*' but there is no 'setup.py' file, and no occurrence of '>=3.5*' in any of the included Python scripts. Apparently, this may not be a fix.

Is there something else I need, or to can be done by editing the archive contents? I wouldn't know how to fix problematic scripts beside mere text editing.
Thanks much!

**Comment by LennartJaretzki** [comment]
I have the same problem with Google Colab, and Mint 20. Two weeks ago it did work, so maybe it is possible to fix it by downgrading.

**Comment by jiteshdoshi** [comment]
This seems to be related to Python version. For me, it installed easily in Python 3.9 but I got this similar error while trying to install vina on Python 3.10 or 3.11. After I downgraded the python to 3.9, it got installed properly.

**Comment by diogomart** [comment]
Fixed by #167

**Comment by diogomart** [comment]
Fixed in 7c8c6d7d4da254e8360490e02a412fbbdd8fdf60
