### ISSUE TITLE
Boost as git submodule in AutoDock-Vina

### ISSUE THREAD

**Issue by L30nardoSV** [ccsb-scripps/AutoDock-Vina#2]
Adding the required Boost projects from https://github.com/boostorg as git submodules would:

* Free the user from installing Boost himself
* Allow easy swap of Boost versions being used

**Comment by diogomart** [comment]
I see your point but I would prefer to keep Boost as an external dependency for the sake of keeping git as simple as possible and projects isolated. It would be a different story if we had to make changes to Boost. Closing, feel free to re-open if needed.
