### ISSUE TITLE
Issue when compiling python bindings

### ISSUE THREAD

**Issue by geozoc** [ccsb-scripps/AutoDock-Vina#20]
Dear AutoDock-vina developers,

Frist: Thank you very much for further improving the docking calculations by this new release. I'm very interested in running vina using the newly implemented python scripting possibilities and therefor tried to set it up (from source). Building the binary was not an issue at all but when it comes to compile the python bindings, I got an compile error:

```
creating build/lib.linux-x86_64-3.5/vina
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-ipWR6Y/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
build/temp.linux-x86_64-3.5/src/lib/utils.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:(.bss+0x0): first defined here
build/temp.linux-x86_64-3.5/src/lib/vina.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/quaternion.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/monte_carlo.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/non_cache.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/mutate.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/szv_grid.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/quasi_newton.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/parallel_progress.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/model.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/coords.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/ad4cache.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/grid.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/parallel_mc.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/conf_independent.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/parse_pdbqt.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/src/lib/cache.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
build/temp.linux-x86_64-3.5/vina/autodock_vina_wrap.o:(.bss+0x0): multiple definition of `boost::system::throws'
build/temp.linux-x86_64-3.5/src/lib/random.o:/usr/include/boost/system/detail/error_code.ipp:66: first defined here
collect2: error: ld returned 1 exit status
```

It would be amazing, if someone can point me to my mistakes.

Thank you very much,
Georg

**Comment by jeeberhardt** [comment]
Hi Georg,

Would it be possible to give us some details about your system (linux distribution, os version, etc...) and which instructions did you follow to install Boost, conda, etc,... and up to where you are right now?

Thanks!

**Comment by geozoc** [comment]
Dear Jerome,

thank you for the incredible fast reply. Sure, I will do my best:

The machine is a debian system:

$lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

I followed the installation procedure as described here:
https://autodock-vina.readthedocs.io/en/latest/installation.html

... for a debain based system. Compilation of the binary itself worked as it should. Problem results in executing:

python setup.py clean --all build install


As you can see, unfortunately this is a pretty old setup. I installed libboost-dev and swig from the repository which might be the issue resulting in my compiling problems. I found this thread,which has nothing to do with Autodock-vina but brings me to the conclusion that it might have to do with old versions of the boost library:
https://github.com/nekipelov/redisclient/issues/26

Unfortunately, I'm a C(++)  noob. But you you think try to setup the compilation on a more up to date system might help?

Thank you very much,
Georg

**Comment by geozoc** [comment]
OK, in the meantime we install vina via conda on a newer machine, which solves our issue. This would be fine for us.

Another completely different topic, where you might want to stop us for running stupid calcuations:
We are trying to dock a disaccharide (MurNAC-6P-GlcNAc) into a recently determined structure we did in our lab. As the substrate is not available for structure determination our hope is to get some ideas about catalysis by the docking poses. 

Docking the disaccharide so far is far from what we expect on the basis of structure homology. I speculate, that this might be a result of our limited experience regarding the docking calculations. Especially, I speculate that adjustments of the weightings (hbond, hydrophobic) might help when it comes to glycan docking. Therefore, our idea was to run some redocking calculations taking a set of glycan:protein complex structures and run redocking with different parameters to verify which results in closest PRMSDs to the published structure. Maybe there is a general weighting that can be applied for docking glycans. 

We also tried out vina_carb using CHI-scoring but to our very limited calculations it does not really improve the docking poses.

Do you think this is non-sense?

All the best and thank you for your comment,
Georg

**Comment by jeeberhardt** [comment]
Hi Georg,

[Before seeing your last comments]
One way to circumvent that would be to install [Miniconda](https://docs.conda.io/en/latest/miniconda.html) on your computer which would give you access to the latest version of Python, and the Boost library and SWIG. 

After installing and setup miniconda:
1. `conda create -n vina python=3`
2. `conda activate vina`
3. `conda install -c conda-forge numpy boost-cpp swig`
4. `cd <autodock-vina-dir>/build/python`
5. `rm -rf build dist *.egg-info`
6. `python setup.py build install`

This should work without issue.

[About docking glycans]
Sorry, but I am afraid to not be familiar at all with sugar docking and vina_carb. Your idea is not non-sense, but my guess is that Vina will not perform better than vina_carb, since the later was specialized designed for that purpose. If it is a search problem, one thing you could try is to increase the `exhaustiveness` parameter to 32. Maybe @diogomart or @mattholc will have better idea about that..

Best,

**Comment by geozoc** [comment]
Dear Jerome,

I would like to confirm your solution. Works perfect.
Regarding the docking: We will try it out and see what happens. 

Thank you again for your support!.

All the best,
Georg

**Comment by diogomart** [comment]
Hi Georg,

Trying different weights for H-bonds and hydrophobic may help. I'd also give it a try with the AD4 scoring function: https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#a-using-autodock4-forcefield
Also, waters may be missing.

Good luck!
