### ISSUE TITLE
prepare_gpf.py generates incorrect gridcenter and the affinity from docking result is positive

### ISSUE THREAD

**Issue by Forever8341** [ccsb-scripps/AutoDock-Vina#201]
I followed the tutorial on https://autodock-vina.readthedocs.io/en/latest/docking_basic.html. The problem I had was that the **prepare_gpf.py** script generated different **npts** and **gridcenter** values with respect to the tutorial.  I did what the tutorial taught: got the STI molecule from protein data bank and used the prepare_gpf.py to calculate the grid info. The gridcenter from the tutorial was: 15.190 53.903 16.917. However when I regenerated the gpf file with this code `pythonsh <script_directory>/prepare_gpf.py -l 1iep_ligand.pdbqt -r 1iep_receptor.pdbqt -y,` what I got was:-0.117 -0.053 0.216. 

With the new gridcenter value, the affinity value was positive. With the gridcenter value provided by the tutorial, I got the similar negative value as the tutorial shows.

**Comment by rwxayheee** [comment]
Hi @Forever8341 

I was able to reproduce your outcome by using the "ideal SDF" downloded from https://www.rcsb.org/ligand/STI as the original structure file for the ligand. 

The -y option in "prepare_gpf.py" sets the gridcenter to be the center of the ligand pdbqt file. 1iep_ligand.sdf, the provided ligand sdf in the tutorial, has the desired center to be the grid center. For your own work you can manually set the grid center for your receptor, before or after you run prepare_gpf.py.

**Comment by Forever8341** [comment]
> Hi @Forever8341
> 
> I was able to reproduce your outcome by using the "ideal SDF" downloded from https://www.rcsb.org/ligand/STI as the original structure file for the ligand.
> 
> The -y option in "prepare_gpf.py" sets the gridcenter to be the center of the ligand pdbqt file. 1iep_ligand.sdf, the provided ligand sdf in the tutorial, has the desired center to be the grid center. For your own work you can manually set the grid center for your receptor, before or after you run prepare_gpf.py.

The purpose of my post is  using **prepare_gpf.py ** to generate the correct grid center info.  If I need to find the grid center manually, i would use AMDock rather than Autodock Vina. 
However, thank you for your solution.

**Comment by rwxayheee** [comment]
Hi @Forever8341, 
The most appropriate choice of gridcenter depends on the objective of docking, as one receptor could have more than one meaningful binding sites. At this moment prepare_gpf.py doesn't have the ability to make the decision. If the auto option doesn't work for your receptor, you could use information from some pocket identification tools. If you are looking for one with Autodock, please try: 
https://ccsb.scripps.edu/agfr/

**Comment by diogomart** [comment]
Seems like this has settled, feel free to re-open if needed. Thanks @rwxayheee
