### ISSUE TITLE
Issue with Preparing Flexible Receptor

### ISSUE THREAD

**Issue by Sruthik22** [ccsb-scripps/AutoDock-Vina#21]
When running this command:

`pythonsh prepare_flexreceptor4.py -r 1fpu_receptor.pdbqt -s THR315` from [https://autodock-vina.readthedocs.io/en/latest/docking_flexible.html](tutorial), I get the `WARNING: no residue named THR315` and an empty `1fpu_receptor_flex.pdbqt` file.

I copied the `1fpu_receptor.pdbqt` file directly from `<autodock-vina_directory>/example/flexible_docking/solution` and I see the correct `1fpu_receptor_flex.pdbqt` in the directory that includes THR315 as flexible. Could you kindly assist me fixing this issue?

**Comment by jeeberhardt** [comment]
Hi Sruthi,

If you use the `prepare_flexreceptor.py` script from the [autodock_scripts directory](https://github.com/ccsb-scripps/AutoDock-Vina/tree/develop/example/autodock_scripts), it should work. ;)

(... sorry for the inconvenience, it should be stated more clearly in the documentation.)

Jérôme.

**Comment by Sruthik22** [comment]
Thanks, it worked!
