### ISSUE TITLE
preparing receptor with coenzyme

### ISSUE THREAD

**Issue by SoodabehGhaffari** [ccsb-scripps/AutoDock-Vina#215]
Hello,
The receptor that I am using has a coenzyme (NADPH) which I would like to keep it during docking. If I do not keep it, the small molecule might clash with it. When I prepare the receptor with the command below, it will delete the coenzyme residue even though I added the flag not to do that. I really appreciate your help.

Thank you

[sg6615@della-gpu binding]$ prepare_receptor -r mytarget.pdb -A 'checkhydrogens' -U 'nphs_lps_waters' -e 'False'

_Unable to assign HAD type to atom N
Unable to assign valence to atom mytarget:A:ALA2:N type = N
Unable to assign HAD type to atom N
Unable to assign valence to atom mytarget:A:LEU5:N type = N
Unable to assign HAD type to atom N
Unable to assign valence to atom mytarget:A:ALA6:N type = N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:MET1:O
Unable to assign MAP type to atom N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:ALA2:N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:ALA2:O
Sorry, there are no Gasteiger parameters available for atom mytarget:A:ARG3:O
Sorry, there are no Gasteiger parameters available for atom mytarget:A:PRO4:O
Unable to assign MAP type to atom N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:LEU5:N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:LEU5:O
Unable to assign MAP type to atom N
Sorry, there are no Gasteiger parameters available for atom mytarget:A:ALA6:N
'Deleting non-standard residues:ANAP0_ from mytarget_

**Comment by mamapapamoi22709004** [comment]
hi i have the same problem, did you solve it?

**Comment by rwxayheee** [comment]
Hi @mamapapamoi22709004 
Can you share your input file? It should be possible to keep cofactors like NADPH because prepare_receptor does not delete non-protein groups if the chain isn't entirely made of nonstandard residues.
