### ISSUE TITLE
Docking with Metal Ions

### ISSUE THREAD

**Issue by KSUN63** [ccsb-scripps/AutoDock-Vina#216]
Hi developers,

I am currently using vina for docking in a metal containing site. However, when I prepared the protein (PDB: 7MC6), I get the following message: 

```
Unable to assign HAD type to atom Mg
Unable to assign valence to atom one-Mg:A: MG311:MG type = Mg
Sorry, there are no Gasteiger parameters available for atom one-Mg:A: ZN301:ZN
Sorry, there are no Gasteiger parameters available for atom one-Mg:A: ZN302:ZN
Unable to assign MAP type to atom Mg
Sorry, there are no Gasteiger parameters available for atom one-Mg:A: MG311:MG
Sorry, there are no Gasteiger parameters available for atom one-Mg:M: ZN201:ZN
Sorry, there are no Gasteiger parameters available for atom one-Mg:M: ZN202:ZN
```
Should I be bothered by this message because the resulting pdbqt file also does not have any charges assigned to these metal ions. Also, I saw the page for zinc metalloprotein, but I am not sure if my ligand will form coordination with the Mg since we are still in early stage of drug development. Anyways, is there any way to get around this issue? Thanks in advance

**Comment by diogomart** [comment]
We are working on a [meeko script](https://github.com/forlilab/Meeko/pull/48) to prepare receptors. I would tell you test it out but it doesn't support metals yet, unfortunately.

**Comment by KSUN63** [comment]
Thanks for the quick update! I will check out meeko later
