### ISSUE TITLE
Conda

### ISSUE THREAD

**Issue by andersx** [ccsb-scripps/AutoDock-Vina#223]
Hi,

Is there any chance that 1.2.5 will make its way to conda-forge? https://github.com/conda-forge/vina-feedstock/pull/7

Thanks,
Anders

**Comment by diogomart** [comment]
Hi,

it's on PyPI, no plans to use also conda-forge.

`pip install vina` should install it in the active conda environment. Did you try this?

**Comment by andersx** [comment]
Thank you. I wanted to add vina as a dependency to another package, but I'll find another way if conda-forge is not maintained.
