### ISSUE TITLE
Procedure of treating Fe2+ Ion

### ISSUE THREAD

**Issue by biotechjs** [ccsb-scripps/AutoDock-Vina#229]
Thank you for this fantastic tool!

I'm trying to perform docking on a site with `Fe (II)`, what would the recommended procedure of doing so?

I have tried to
- manually change the charge of Fe to 0, 1.4, and 2 in the `pdbqt`, but the result doesn't seem to be dependent on that number
- I am not sure if https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html would be applicable here.
- The following link doesn't seem to work anymore
  - http://autodock.scripps.edu/faqs-help/faq/metal-charges
- I have read https://github.com/ccsb-scripps/AutoDock-Vina/issues/216 but https://github.com/forlilab/Meeko/pull/48 doesn't seem to be ready yet.
  - is there any makeshift method/instructions of doing so?

**Comment by diogomart** [comment]
Vina treats all metals as a H-bond donor, and partial charges are not used. The Vina scoring function is so simple that there's nothing special that needs to be done about metals.

**Comment by biotechjs** [comment]
thank you @diogomart ! Just curious, would it be worthwhile to try your other project autodock-gpu?

**Comment by diogomart** [comment]
It may be worth trying the AD4 scoring function, which can be done also from Vina with the `--scoring ad4` option. Often, one scoring function outperforms the other, and we don't really know why. Note that partial charges matter for AD4 scoring. If you have a lot of GPU power and want to dock a lot of molecules, then AD-GPU could be very valuable. AD-GPU also implements the AD4 scoring function.

**Comment by biotechjs** [comment]
thank you very much @diogomart !
