### ISSUE TITLE
different score values between score() vs energies() after docking

### ISSUE THREAD

**Issue by jaehongshin** [ccsb-scripps/AutoDock-Vina#231]
I use a python binding for docking. After a docking job, I calculated scores using v.energies(), v.score(), and v.optimize().  However v.energies and v.score turn different scores. Would any one explain this? 

Only I figured out is when no of poses set to 1, the v.energies and v.score turn the same value. 
But no of poses set to greater than 1, v.energies() and v.score() turn different values. If v.score() takes the best pose, it should be the same value to v.energies(). Any comments would be helpful. Thanks

**Comment by diogomart** [comment]
Intramolecular energy of the first pose is subtracted from all poses. Does that explain what you observe?

**Comment by jaehongshin** [comment]
Would you explain the meaning for that why the energy of the first pose is subtracted from all poses? Thanks!!

**Comment by diogomart** [comment]
It's to preserve the ranking of the scoring function used for optimization. The search optimizes intra+inter, if vina subtracted the intra of each pose from itself, like in the autodock4 (AD4) scoring function, the ranking of poses would change (it changes with AD4 scoring). Both approaches are questionable from a physics standpoint, it's a "pick your poison" situation.
