### ISSUE TITLE
Batch mode with vinardo scoring function

### ISSUE THREAD

**Issue by helen-power** [ccsb-scripps/AutoDock-Vina#233]
I have attempted to execute vina in batch mode with the vinardo scoring function using the following command:
vina --receptor vinardo_4M5T_rot/4M5T_rot_rigid.pdbqt --flex 4M5T_rot_flex.pdbqt --batch ${io}/all_ligands/ZINC_world/pdbqt/* --config 4M5T_config.txt --dir results/ZINC_world --exhaustiveness 16 --num_modes 10 --cpu 32 --scoring vinardo

I am getting the following error:
ERROR: Cannot do the global search. Affinity maps were not initialized.

Without batch mode, vina computes the maps internally. However, I would like to use batch mode so that maps do not need to be computed individually for each ligand. Is there a way to do this?

Thanks

**Comment by diogomart** [comment]
I think this is the same as in #186 and has been fixed, are you using the latest (v1.2.5) ?

**Comment by helen-power** [comment]
Sorry I missed #186. Will update to the latest version. Thanks!
