### ISSUE TITLE
Some confusion about how releases are made

### ISSUE THREAD

**Issue by Metaphorme** [ccsb-scripps/AutoDock-Vina#234]
Dear developors!

I would like to express my sincere gratitude for your hard work and dedication to the project.

Earlier this year, I created a [repository](https://github.com/Metaphorme/AutoDock-Vina-Docker) to enable vina to run natively on my ARM-based MacBook. It helped me to easily deploy vina and MGLTools without losing performance and installing dependencies.

In June, the original `release` branch was deleted. I would like to ask if there will be a `release` branch in the future, or if versions will be distinguished by tags on the `develop` branch? This will help me to better package Docker images.

Another point is that the existing way of installing MGLTools may cause PATH pollution and lead to some errors. Therefore, I have a suggestion: to provide official Docker images for Autodock and MGLTools. This will greatly reduce the trouble encountered during installation and use, and help Autodock run and use on the correct architecture. If you also think this suggestion is reasonable, we can continue to discuss it. I am very willing to take on this part of the work.

Finally, I wish you all the best in your life and career!

John

**Comment by diogomart** [comment]
Dear John!

No plans to have a `release` branch. Git tags indicate the commits associated with releases. The `release` branch was probably inspired by "gitflow" diagrams but then we realized that after merging two branches it is not possible to tell which branch was checked out when commits were made (because git branches point to a single commit), so the `release` branch was doing nothing more than being associated with the latest tag, which is useless because tags are serially numbered.

With meeko, ligand preparation is now independent of MGLTools, and receptor preparation is partially working. Eventually we won't need MGLTools anymore.
https://github.com/forlilab/Meeko

All the best in your life and career as well :)

**Comment by diogomart** [comment]
Was the `release` branch useful for you because then you don't need to check which release is the latest? If so we can restore it and call it `latest-release` or something like that.

**Comment by Metaphorme** [comment]
> Dear John!
> 
> No plans to have a `release` branch. Git tags indicate the commits associated with releases. The `release` branch was probably inspired by "gitflow" diagrams but then we realized that after merging two branches it is not possible to tell which branch was checked out when commits were made (because git branches point to a single commit), so the `release` branch was doing nothing more than being associated with the latest tag, which is useless because tags are serially numbered.
> 
> With meeko, ligand preparation is now independent of MGLTools, and receptor preparation is partially working. Eventually we won't need MGLTools anymore. https://github.com/forlilab/Meeko
> 
> All the best in your life and career as well :)

Dear Diogo!

Really appreciate your patient comment to explain how the branches works! I plan to publish Docker images based on `Tags` and the latest `develop branch`, replacing the previous method of publishing images through release and develop branches. Therefore, there is no need for a new `latest-release branch`. Thank you for your thoughtfulness.

Meeko is a great tool! It looks more advanced and easy to use than MGLTools. I am glad to include Meeko in my own image. I believe that one day Meeko will completely replace MGLTools.

I wonder if you have any plans to include the Docker installation method in the documentation and manage these images. Perhaps we could create a repository at [ccsb-scripps](https://github.com/ccsb-scripps/) or other place and publish official images for applications such as AutoDock-Vina, AutoDock-GPU, etc. That would be so cool! 😎

Have a nice day!

**Comment by diogomart** [comment]
Yes, we are planning to distribute our software with images (most likely Docker) but unfortunately I think it will be at least a year, maybe more, until we get to that.

Thanks :)

**Comment by Metaphorme** [comment]
Thanks! If there's anything I can do to help, please feel free to contact me.
