### ISSUE TITLE
Autodock 4 docking automation script

### ISSUE THREAD

**Issue by apaydinemre** [ccsb-scripps/AutoDock-Vina#235]
Hello,
I came across a shell script on the Autodock Vina manual page under the "Virtual Screening" section (https://vina.scripps.edu/manual/#screening) that allows us to dock multiple ligands sequentially to a single receptor. The script is as follows:
```
#! /bin/bash
for f in ligand_*.pdbqt; do
    b=`basename $f .pdbqt`
    echo Processing ligand $b
    mkdir -p $b
    vina --config conf.txt --ligand $f --out ${b}/out.pdbqt --log ${b}/log.txt
done
```
My question is, is it possible to perform the same operation with Autodock4? Can a script be written to automate this process for Autodock4? I would greatly appreciate any assistance on this matter.
Best regards.

**Comment by diogomart** [comment]
Hello,

Yes. That script is written in BASH, you can use BASH to automate things in general.

**Comment by RJ-Li** [comment]
I have an important question to ask you: How did you process the numerous pdb files which have ions such as Zn in the dataset in to pdbqt? I find they cannot be converted into PDBQT files, but I DON'T wanna deal with them with AutoDockZn(this method might use different scoring function than vina scoring funtion, so I cannot categorize them into vina)

**Comment by apaydinemre** [comment]
I downloaded my ligands from the ZINC20 library. I converted the sdf files I downloaded to pdbqt files with openbabel, but since some ligands in my ligand set contain Boron atoms, I get an "undefined atom type" warning. I still haven't solved this problem, I am trying to solve it.

**Comment by Dadiao-shuai** [comment]
I find that metals can be trans into pdbqt after you delete some lines
