### ISSUE TITLE
Hydrated docking

### ISSUE THREAD

**Issue by mirjr** [ccsb-scripps/AutoDock-Vina#248]
I'm getting an error with this exact process. What could be the reason?

Return message: `Command line parse error: unknown option maps`

https://github.com/ccsb-scripps/AutoDock-Vina/blob/d13f9e93e253573b01ffbb28cfd1e2dd26ff9002/docs/source/docking_hydrated.rst?plain=1#L131

**Comment by rwxayheee** [comment]
Hi @mirjr, could you check: 
```
vina --version
```
If you possibly have multiple versions of vina like i do, `--maps` should work for the latest version 1.2.5, and you can get it from [here](https://github.com/ccsb-scripps/AutoDock-Vina/releases). I got the same error when i tried to run the command using AutoDock Vina 1.1.2.

**Comment by mirjr** [comment]
> Hi @mirjr, could you check:
> 
> ```
> vina --version
> ```
> 
> If you possibly have multiple versions of vina like i do, `--maps` should work for the latest version 1.2.5, and you can get it from [here](https://github.com/ccsb-scripps/AutoDock-Vina/releases). I got the same error when i tried to run the command using AutoDock Vina 1.1.2.

Thanks a lot, it worked!
