### ISSUE TITLE
multiple ligands error

### ISSUE THREAD

**Issue by sailseem** [ccsb-scripps/AutoDock-Vina#25]
Dear,
    when i tried to run the example $ vina --receptor 5x72_receptor.pdbqt --ligand 5x72_ligand_p59.pdbqt 5x72_ligand_p69.pdbqt \
       --config 5x72_receptor_vina_box.txt \
       --exhaustiveness 32 --out 5x72_ligand_vina_out.pdbqt

turned out as Command line parse error: too many positional options have been specified on the command line

but when I just run the single ligand, that's totally fine

can you help me with it? thanks

**Comment by sailseem** [comment]
besides, assume that we have 100 ligands, we cannot type each one in the script, right? is there any other way to do that?

**Comment by diogomart** [comment]
Hello,

What does this print?
```
vina --version
```

With vina 1.2, `--ligand a.pdbqt b.pdbqt` docks both ligands simultaneously, and `--batch a.pdbqt b.pdbqt --dir results_dir` docks one and then the other and writes output files to "results_dir".

**Comment by sailseem** [comment]
return   AutoDock Vina 1.1.2 (May 11, 2011)

**Comment by diogomart** [comment]
Binaries for 1.2: https://github.com/ccsb-scripps/AutoDock-Vina/releases/tag/v1.2.2

**Comment by sailseem** [comment]
i dont know why i installed vina by pip install,    but when I tap in vina --version, it returns  no command, and to be honest, I am kind of newer to this, I have no idea how to install this vina_1.2.1_macos_x86_64 file.

**Comment by diogomart** [comment]
I think `pip install` is for the Python version only. @jeeberhardt please correct me if I'm wrong.

By typing `vina` you are running a binary somewhere in your PATH. Typing `which vina` will tell you which binary exactly. Searching online for "PATH environment variable" will give you more information.

You can download the binary and execute it, see details at the top of the page: https://autodock-vina.readthedocs.io/en/latest/installation.html

**Comment by sailseem** [comment]
i see your point, thank you very much,man, you saved my life!!!!   Appreciated it !!!

**Comment by sailseem** [comment]
--batch a.pdbqt b.pdbqt --dir results_dir  
 so batch function still return to one output file, right?  I thought that would be two out files as I input two ligands there. but seems like there is no difference with --ligand a.pdbqt b.pdbqt

**Comment by diogomart** [comment]
Glad I helped!

There should be multiple output files with batch mode, I'll look into it.

**Comment by diogomart** [comment]
fixed in PR #28, will update binaries soon

**Comment by diogomart** [comment]
We will update binaries soon, but meanwhile the --batch mode works if the ligands are inside a folder:
```
--batch ligs/a.pdbqt ligs/b.pdbqt --dir results
```
or even
```
--batch ligs/*.pdbqt --dir results
```

**Comment by sailseem** [comment]
all right ， this way works well

**Comment by sailseem** [comment]
well，how to batch export the log files or txt file including affinity and rmsd for each mode？

**Comment by diogomart** [comment]
There's currently no way to do that but the same information is stored in the output .pdbqt files, in lines starting with "REMARK VINA RESULT".

For example, the information in this standard output:
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -1.078          0          0
   2       -1.051       1.37      1.909
   3      -0.9496      2.045      3.154
   4      -0.9443      7.465      7.746
   5      -0.9419      1.801      2.593
   6      -0.9386      7.508      7.918
   7      -0.9269      1.466      2.427
   8      -0.9234      1.152      2.207
   9      -0.8401      7.002      7.224
```

could be retrieved with `grep`:
```console
$ grep RESULT results/imidazole_out.pdbqt 
REMARK VINA RESULT:    -1.078      0.000      0.000
REMARK VINA RESULT:    -1.051      1.370      1.909
REMARK VINA RESULT:    -0.950      2.045      3.154
REMARK VINA RESULT:    -0.944      7.465      7.746
REMARK VINA RESULT:    -0.942      1.801      2.593
REMARK VINA RESULT:    -0.939      7.508      7.918
REMARK VINA RESULT:    -0.927      1.466      2.427
REMARK VINA RESULT:    -0.923      1.152      2.207
REMARK VINA RESULT:    -0.840      7.002      7.224
```

**Comment by sailseem** [comment]
Well, the thing is,  if i am planning to dock 5000 compounds with one receptor, I don't need to check every single mode. I just check maybe over -7 affinity docking results. That's why I need to get a list ranking with affinity, so I can check the top ones only.

**Comment by diogomart** [comment]
You could do that with `grep` and `sort`
```
grep RESULT -m 1 results/* | sort -g -k 4
```

**Comment by diogomart** [comment]
Are you referring to `mk_prepare_ligand.py` in https://github.com/ccsb-scripps/Meeko?

If yes, the current `develop` branch supports multiple molecule inputs, and outputs individual PDBQT files to an output directory:
```
mk_prepare_ligand.py -i molecules.sdf --multimol_outdir outputfolder/
```
