### ISSUE TITLE
How to generate Vina forcefield grid space?

### ISSUE THREAD

**Issue by maximilianpress** [ccsb-scripps/AutoDock-Vina#251]
In the section on using [Vina forcefield](https://autodock-vina.readthedocs.io/en/latest/docking_basic.html#b-using-vina-forcefield) in the tutorial, it notes that it is easy to use Vina forcefield but you have to generate a file that looks like this:

("Content of the config file 1iep_receptor_vina_box.txt for AutoDock Vina")
```
center_x = 15.190
center_y = 53.903
center_z = 16.917
size_x = 20.0
size_y = 20.0
size_z = 20.0
```
From the tutorial:
> you still need to specify the center and dimensions (in Angstrom) of the grid space, as well as the receptor. Here, instead of specifying each parameters for the grid box using the arguments --center_x, --center_y, --center_z and --size_x, --size_y, --size_z, we will store all those informations in a text file 1iep_receptor_vina_box.txt.

How can I generate that grid space for some arbitrary receptor `pdbqt` file? Obviously I am not super familiar with the structural biology toolkit, but this seems a bit mysterious how to magically know the right grid space.

**Comment by alissonws** [comment]
The docs still have a lot of gaps and flaws by considering important steps as common knowledge, so you might feel a bit lost in it. You can use pretty much any 3D molecule viewer tool that supports arbitrary box placing without messing with your file coordinates, such as AutoDock Tools or Pymol. I personally like the old version of UCSF Chimera (the new one, Chimera X, doesn't seem to implement it out of the box). Each software has its own way of doing it, but it's all about making it easier for you to see what coordinates you are picking, so there are a lot of different options. If you need a starting point, most of Vina's docking tutorials on YouTube cover that during the preparation part. Even though the rest of the protocol might seem to be outdated, the grid selection remains the same. So you just need to find one that uses a tool that suits you better.

Also, keep in mind that the smaller the better for that case.

**Comment by rwxayheee** [comment]
Hi @maximilianpress, 
If you have an arbitrary receptor with no prior knowledge where the binding site(s) might be, you will likely need a pocket identification tool to identify the binding site first. There are many web servers and tools with GUI for you to do this with visual inspection (and even dynamical or conformational sampling) for the druggable site of the receptor. 
For easy batch processing and compatibility with docking calculations that use the AD4 scoring function, please consider the following program: 
https://ccsb.scripps.edu/agfr/documentation/

**Comment by maximilianpress** [comment]
Understood, thanks so much for the detailed explanation @alissonws and @rwxayheee!
