### ISSUE TITLE
An internal error occurred in ../../../src/lib/tree.h(101)

### ISSUE THREAD

**Issue by YvetteJxy** [ccsb-scripps/AutoDock-Vina#264]
I have posted the protein file (20.pdbqt) and the ligand file(2.pdbqt).
When I run './DOCKING/vina_1.2.5_linux_x86_64 --receptor ./20.pdbqt --ligand ./2.pdbqt --size_x 20 --size_y 20 --size_z 20 --autobox', I encountered an error: An internal error occurred in ../../../src/lib/tree.h(101)

I have tried many groups of protein files and ligand files, and this error occurred too many times.
[files.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/13872122/files.zip)

**Comment by rwxayheee** [comment]
Hi @YvetteJxy, Your upload appears as a HTML file (it looks very like the login page of Jupyter server). Let us know if you reshare the files. 

One more thing about `--autobox`, in this scenario (a docking search), `--autobox` doesn't actually set the grid size or the grid center (?). `--size_x --size_y --size_z` are necessary even with `--autobox`, and if not specified the center seems to be 0,0,0. Not sure if this is related to the error.

**Comment by YvetteJxy** [comment]
Thank you for your help! I am very grateful for that!
I have uploaded the file again and I hope this time it will work!
[files.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/13920655/files.zip)

**Comment by rwxayheee** [comment]
Hi @YvetteJxy, the problem was caused by your ligand PDBQT file, which doesn't have valid 3D coordinates but all 0s. You might want to review your procedure for ligand preparation. 

[If I guessed your ligand right] (https://en.wikipedia.org/wiki/Dimethylsulfoniopropionate), here's how you could generate a PDBQT with coordinates and charges (although not necessary for vina) with obabel: 
```shell
./obabel -:"C[S+](C)CCC(=O)[O-]" -o pdbqt --gen3d
REMARK  Name = 
REMARK  5 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_1  and  S_2
REMARK    2  A    between atoms: S_2  and  C_3
REMARK    3  A    between atoms: S_2  and  C_4
REMARK    4  A    between atoms: C_4  and  C_5
REMARK    5  A    between atoms: C_5  and  C_6
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ROOT
ATOM      1  C   UNL     1       3.420  -1.521   0.625  0.00  0.00    +0.283 C 
ENDROOT
BRANCH   1   3
ATOM      2  C   UNL     1       1.153  -0.143   0.096  0.00  0.00    +0.340 C 
ATOM      3  S   UNL     1       2.913  -0.014  -0.300  0.00  0.00    -0.016 S 
ATOM      4  C   UNL     1       3.321   1.174   1.001  0.00  0.00    +0.340 C 
ENDBRANCH   1   3
BRANCH   1   5
ATOM      5  C   UNL     1       4.918  -1.736   0.537  0.00  0.00    +0.106 C 
BRANCH   5   6
ATOM      6  C   UNL     1       5.385  -2.974   1.303  0.00  0.00    +0.046 C 
ATOM      7  O   UNL     1       6.631  -3.182   1.245  0.00  0.00    -0.550 OA
ATOM      8  O   UNL     1       4.496  -3.633   1.911  0.00  0.00    -0.550 OA
ENDBRANCH   5   6
ENDBRANCH   1   5
TORSDOF 3
```

**Comment by YvetteJxy** [comment]
@rwxayheee Thank you for your help! I think I know what the problem is! I didn't generate valid 3D coordinates of my ligand and now I have corrected my error! Thank you very much!
