### ISSUE TITLE
Vina not producing complex structures after running  

### ISSUE THREAD

**Issue by AlexisGGk** [ccsb-scripps/AutoDock-Vina#266]
Hiya, 

So I have run vina ver 1.1.2 on heme group binding to a protein. I managed to get it to work and got a delta G output that was roughly what I expected. However, when I look at the structure that is produced only the ligand is visible not the ligand-protein complex. 

I have included the line: 

```
out="results.pdb"
```

Which should be all that is required from the documentation I have read. The results are below. on checking the file its definitely only the ligand. 
[results.pdb.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/13951898/results.pdb.txt)

full script is below (heads up this is on a HPC cluster). Any suggestions are welcome! 

```
# The following section relates to the job scheduling for the HPC) 

#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

# Loads the vina module 
module load use.dev
module load autodock-vina/1.1.2

# Specifies file names 
ligand="validation_output.pdbqt"
receptor="receptor_7.pdbqt"

# Specifies co ordinates 
center_x=0
center_y=0
center_z=0

# Specifies box size 
size_x=20
size_y=20
size_z=20

# Gives number of binding orientations. Only want one 
num_modes=1

# Outputs complex structure 
out="results.pdb"

exhaustiveness=8

log="be.txt"

# Add the vina command
# This section was added by chatgpt along with revisions to the code and made it work
# Unsure why it wasn't working before 
vina --cpu $NSLOTS --ligand "$ligand" --receptor "$receptor" --center_x $center_x --center_y $center_y --center_z $center_z --size_x $size_x --size_y $size_y --size_z $size_z --num_modes $num_modes --out "$out" --exhaustiveness $exhaustiveness --log "$log"
```

**Comment by diogomart** [comment]
That's expected, vina writes only the ligand and flexible sidechains if these were specified. The receptor doesn't move during docking, so just open the input receptor alongside the docks ligand to visualize the complex.

**Comment by AlexisGGk** [comment]
Ahhh I see... do you happen to know how to turn it into a combined file after visualisation then? I want to run further docking on the complex

**Comment by rwxayheee** [comment]
Hi @AlexisGGk I was watching [openbabel/openbabel#2665](https://github.com/openbabel/openbabel/issues/2665). There are various ways to combine receptor and docking outputs. Here are two examples and you can substitute with your preferred commands: 

1. Append the content of receptor.pdbqt by the end of each ligand model

`sed '/ENDMDL/e cat receptor_input.pdbqt' docking_output.pdbqt > sed_combined.pdbqt`

This produces a multi-model pdbqt file where the content of receptor.pdbqt is pasted before every ENDMDL. You could then use [vina_split](https://github.com/ccsb-scripps/AutoDock-Vina/releases) on the combined pdbqt if you want single-model pdbqt files

2. Split the docking output, then merge each model with receptor.pdbqt

`vina_split --input docking_output.pdbqt`
In the first step, vina_split produces a serial of single-model ligand pdbqt named `<name of input file>_ligand_01.pdbqt`, `<name of input file>_ligand_02.pdbqt` ...

`cat docking_output_ligand_01.pdbqt receptor.pdbqt > cat_combine_01.pdbqt`
You can write a loop in the second step for all poses (or the top N poses you'd be most interested in)

Depending on what your next step is, you might want to post-process the combined file(s).

**Comment by AlexisGGk** [comment]
Is there any harm in just opening both in pymol then exporting them in .pdb format? Just tried that and it appears to work!

**Comment by rwxayheee** [comment]
Yeah it's fine. After saving as a PDB file, the charge column will be gone and the AD atom type column will be overridden by elements. So it really depends on what you want to reuse the combined structure for. If you want to run further docking on the complex, merging the pdbqt files (not saving as a pdb) might be more efficient in my opinion

**Comment by AlexisGGk** [comment]
Hmmm okay but the output is in pdb format not pdbqt format so surely Id need to convert it anyway ?

**Comment by rwxayheee** [comment]
No, the output is pdbqt. You named it as pdb but it doesn’t actually change the format if I’m right..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexisGGk** [comment]
Ah @rwxayheee you appear to be correct thank you!
