### ISSUE TITLE
Error- Insufficient memory 

### ISSUE THREAD

**Issue by Soumyadutta03** [ccsb-scripps/AutoDock-Vina#269]
I have been trying to run autodock vina for exhaustivness of 10000 . How is it possible. I have tried by reducing the grid size. Its still giving this error. This is the code i am using and the config file is also attached. 
[conf_vs.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/14083672/conf_vs.txt)

![Screenshot 2024-01-29 165834](https://github.com/ccsb-scripps/AutoDock-Vina/assets/104270423/f20500f7-bd17-4162-8d37-79f8dedf905a)

command --> vina.exe --receptor protein.pdbqt --ligand peptide00wt.pdbqt --config conf_vs.txt --log peptide00wt.txt --out peptide00wt_out.pdbqt --cpu 15
How do i resolve this issue and run this on 10000 exhaustiveness ?

**Comment by diogomart** [comment]
Does it run with smaller values for exhaustiveness?

**Comment by rwxayheee** [comment]
Hi @Soumyadutta03, user here. According to the outputs, you seemed to be using autodock_vina_1_1_2. Given the same grid size and exhaustiveness, we found that the new version (from this github repository) uses less virtual memory, if that might help resolve your issue.. You can also divide the grid into a few smaller boxes and run docking individually

**Comment by Soumyadutta03** [comment]
Yes It was running for smaller values of exhaustiveness. I have installed the latest version of autodock vina from github and now for this 10000 exhaustiveness it is working with the same grid size. Thank you so much for helping.
