### ISSUE TITLE
[Question/Information] Explain about forcefield.cpp

### ISSUE THREAD

**Issue by talregev** [ccsb-scripps/AutoDock-Vina#27]
Why you put `forcefield.cpp` in the lib if you don't want to compile it? Is it part of the lib?

**Comment by diogomart** [comment]
If I remember correctly we compiled it at some point, and we may still do something with it. Maybe we will delete it eventually.

**Comment by talregev** [comment]
For v1.2.2 I compile it with vcpkg as part of the lib. 
I suggested some small minor fix for compile it on windows.
Will you consider compile it as part of your lib until you delete it? 
Also consider again my small fix for compile it on windows?
https://github.com/ccsb-scripps/AutoDock-Vina/pull/23

**Comment by diogomart** [comment]
@talregev seems like the issue is with the compile script on vcpkg. Probably you can change it to compile only the files needed. You can find this list of source files at the top of `build/makefile_common`.

**Comment by talregev** [comment]
You miss my point.
