### ISSUE TITLE
Tips for docking performance

### ISSUE THREAD

**Issue by TVect** [ccsb-scripps/AutoDock-Vina#279]
Hello, could you give me some advice on how to improve the performance of Autodock Vina on a certain class of target sites? 

We previously performed docking with Autodock Vina, Schrodinger, and Discovery Studio for a specific protein. By observing the interactions of certain amino acid residues, we found that Schrodinger and Discovery Studio performed better because their docking results preserved these interactions, while Autodock Vina gave conformations in the opposite direction. 

Can you provide some suggestions on how to improve the performance of Autodock Vina on a certain class of target sites?

**Comment by diogomart** [comment]
Moved to #280
