### ISSUE TITLE
What is the difference between ADFR and flexible docking using vina?

### ISSUE THREAD

**Issue by eunos-1128** [ccsb-scripps/AutoDock-Vina#282]
Dear all,

Upon reading a tutorial on partially protein-flexible docking using Vina, I couldn’t understand how it differs from ADFR.

I’ve read both of the papers on Vina v1.2.0 and ADFR, but I still don’t understand the difference.

Are Vina’s flexible docking and ADFR the same thing or not?

As of 2024 which method is better to run docking for rigid-ligand/partially flexible protein? 

Best Regards,

**Comment by rwxayheee** [comment]
Hi @eunos-1128 

> I’ve read both of the papers on Vina v1.2.0 and ADFR, but I still don’t understand the difference.
> 
> Are Vina’s flexible docking and ADFR the same thing or not?

They are different in many ways. The receptor sidechain sampling features described in the ADFR paper are exclusive to ADFR. Vina samples sidechain torsions the same way as if they were ligand torsions 

> As of 2024 which method is better to run docking for rigid-ligand/partially flexible protein? 

Try both and let us know what you think :)

**Comment by eunos-1128** [comment]
@rwxayheee 

I understand. Thank you!
