### ISSUE TITLE
Charges in Vina

### ISSUE THREAD

**Issue by Anujkumarp** [ccsb-scripps/AutoDock-Vina#286]
Which kind of charges are used in Vina1.2.x. And how to use add them through command line in prepare_receptor.

**Comment by rwxayheee** [comment]
Hi @Anujkumarp 
The Vina scoring function doesn't include a term that uses atomic charges (therefore, either gasteiger or kollman works the same). If unspecified, the default charge model in prepare_receptor is gasteiger.
