### ISSUE TITLE
Can Autodock Vina perform Constraint Docking?

### ISSUE THREAD

**Issue by shienliu** [ccsb-scripps/AutoDock-Vina#288]
I am attempting to use Autodock Vina for molecular docking, and I would like to constrain a core of a small molecule within a binding pocket while allowing the rest of the molecule to undergo conformational search. Does Autodock Vina have a feature or method to achieve this?

**Comment by rwxayheee** [comment]
Hi @shienliu
According to #280 , #152 and #121 , you can perform [Anchored docking](https://github.com/ccsb-scripps/AutoDock-GPU/wiki/Anchored-docking) with [AutoDock-GPU](https://github.com/ccsb-scripps/AutoDock-GPU)

**Comment by shienliu** [comment]
Thanks, Amy. I will try.
