### ISSUE TITLE
Problems with Ruthenium

### ISSUE THREAD

**Issue by sdevita7** [ccsb-scripps/AutoDock-Vina#291]
Hello!

I am trying to perform a docking with a molecule containing Ruthenium using AutoDock Vina (v. 1.2.3) and the vina scoring function but, despite adding the corresponding parameters in the AD4_parameters.dat file, it still returns the following error:

> AutoDock Vina v1.2.3

> Scoring function : vina
> Rigid receptor: 5mwq_clean_total_site_1.pdbqt
> Ligand: aziru.pdbqt
> Grid center: X 0.4 Y 6.45 Z -7.6
> Grid size  : X 13 Y 13 Z 13
> Grid space : 0.375
> Exhaustiveness: 64
> CPU: 0
> Verbosity: 2
> 
> 
> PDBQT parsing error: Atom type Ru is not a valid AutoDock type (atom types are case-sensitive).

 > HETATM    7 RU1  UNK   900      -0.139   0.241  -0.320  1.00  0.00     0.380 Ru

Can you help me understand what I am missing?

**Comment by diogomart** [comment]
Hello,
Vina doesn't read the .dat file, the only thing that can be done is changing the type to something vina recognizes, such as Fe. Vina treats all metals the same. By the way, bugs have been fixed since v1.2.3, you should use v1.2.5.

**Comment by sdevita7** [comment]
Thank you!
