### ISSUE TITLE
Can't install 1.2.5 on Win11

### ISSUE THREAD

**Issue by Evert-Homan** [ccsb-scripps/AutoDock-Vina#294]
When running the vina_1.2.5_win installer on Windows 11 a Window flashes briefly, and that's it, nothing happens after that.

Please advise/Evert

**Comment by rwxayheee** [comment]
Hi @Evert-Homan 
[vina_1.2.5_win.exe](https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.5/vina_1.2.5_win.exe) is the program itself, an executable that is ready to be used, no further installation. The app closing immediately might be a normal behavior for a command line .exe such as vina if you start it by a double click. You can use it through an open command line prompt on Windows, [here are some ways to open it](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)
If you have WSL you could also choose [vina_1.2.5_linux_x86_64](https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.5/vina_1.2.5_linux_x86_64)

**Comment by P4j45** [comment]
Sorry, my bad. Thanks for your quick reply.

**Comment by Preeticube** [comment]
Hey @rwxayheee 
what if I need the GUI for generating the files and grid (needs visualization). In the cmd line I won't be able to do that ? Right or I am doing something wrong?

**Comment by Evert-Homan** [comment]
There is no GUI...

**Comment by Preeticube** [comment]
how are you selecting where to place your grid

**Comment by rwxayheee** [comment]
Hi @Preeticube 
You can do a quick search and there are a couple official and unofficial GUI that provide docking setup with a grid box. 

For consistency and reproducibility, it might be better to do it programmatically, with some visualization (using any visualization program you would prefer) for assistance. The box is rectangular and you can simply draw it with your receptor structure. 

We have some guides for grid setup programmatically: 
(Command line) https://meeko.readthedocs.io/en/release-doc/tutorial1.html#receptor-preparation
(Python API) https://meeko.readthedocs.io/en/release-doc/tutorial4a.html#receptor-preparation

**Comment by Preeticube** [comment]
@rwxayheee Thanks
