### ISSUE TITLE
Autogrid4 raise error "dyld: Library not loaded:"

### ISSUE THREAD

**Issue by farmaceut** [ccsb-scripps/AutoDock-Vina#299]
Hello,
 I have successfully installed ADFR on my computer (MacOS Catalina) but cannot run Autogrid4. When I try, the errors is yielded:
```
iMac:Bcl-2 maciek$ autogrid4 -p 4-4lxd_prepared_rigid.gpf 4-4lxd_prepared_rigid.glg
dyld: Library not loaded: /Users/Shared/mgltoolsDev/src/homebrew/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /Users/maciek/ADFR/bin/autogrid4
  Reason: image not found
Abort trap: 6
```

What's wrong? How to fix it. Thanks in advance.

**Comment by diogomart** [comment]
We compiled a new version but haven't properly published it yet. Not sure it will solve your problem but it's here if you want to give it a try: https://github.com/forlilab/tutorials/tree/main/executables

**Comment by farmaceut** [comment]
Unfortunately, the error persists

**Comment by diogomart** [comment]
You could try installing Xcode command line tools:
https://github.com/forlilab/tutorials/tree/main/installation-mac

I guess autogrid was compiled dynamically and needs some library files that are installed with the compiler.

**Comment by farmaceut** [comment]
Got installed XCode and Xcode Command Line Tools

**Comment by rwxayheee** [comment]
Hi @farmaceut 
Not sure how helpful this is just in case your mac has M1/2/3, another possible reason for this dylib not openning is unsupported architecture. According to the following post from the community, installing gcc 8 amd64 could be a solution: 
https://web.navan.dev/posts/2024-03-28-Running-ADFRSuite-on-arm64-Macs.html

**Comment by diogomart** [comment]
@farmaceut and does either autogrid binary run now?

**Comment by farmaceut** [comment]
Hello @rwxayheee . I try this right now.
@diogomart  No, still struggling.

**Comment by farmaceut** [comment]
Find the issue. I had to pick specific version of vina to make it run. That's the drawback of old computer - searching for the working version.
