### ISSUE TITLE
Enormous free energy of binding

### ISSUE THREAD

**Issue by farmaceut** [ccsb-scripps/AutoDock-Vina#300]
Hello,

I followed [this tutorial](https://autodock-vina.readthedocs.io/en/latest/docking_basic.html) to dock my new ligand into another protein. However, in the end, I obtained extremely high affinity values:

```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1    1.107e+07          0          0
   2    1.115e+07       1.84      3.158
   3    1.155e+07      1.568      6.297
   4    1.833e+07      1.961       2.21
   5    1.987e+07       2.17      3.457
   6    2.265e+07      1.591      2.251
   7    2.525e+07      1.821      2.733
   8    2.624e+07      2.066      3.882
   9     3.51e+07       2.49      4.033

```

Here are the steps I followed:

1) I downloaded the 4lxd receptor from the PDB, removed everything except the protein, protonated it using Propka as implemented on the PDB2PQR webpage; then manually converted the resulting PQR format to PDB, and ran:
 `prepare_receptor -r 4lxd.pdb -o 4lxd.pdbqt`

[4lxd.pdb](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963470/4lxd.pdb.txt)
[4lxd.pdbqt](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963457/4lxd.pdbqt.txt)

2) Then, I prepared the ligand (H4Fst) using:
`mk_prepare_ligand.py -i H4Fst.mol -o H4Fst.pdbqt`

[H4Fst.mol](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963462/H4Fst.mol.txt)
[H4Fst.pdbqt](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963465/H4Fst.pdbqt.txt)

3) I generated affinity maps for the AutoDock force field using:
`pythonsh ./prepare_gpf.py -l H4Fst.pdbqt  -r 4lxd.pdbqt -y` 
and obtained the 4lxd.gpf file, which I modified using Chimera visualization:

![Chimera](https://github.com/ccsb-scripps/AutoDock-Vina/assets/37613856/2c2c777b-b46b-487b-ad50-38e19d85023c)

I set  `npts 22 12 11` and `gridcenter 21.3455 31.4093 8.11142` leaving the remaining parameters as they were.
[4lxd.gpf](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963491/4lxd.gpf.txt)

4) I ran AutoGrid4 using:
 `autogrid4 -p 4lxd.gpf -l 4lxd.glg`
[4lxd.glg](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963499/4lxd.glg.txt)

and obtained all the maps enclosed in this file:
[maps.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963512/maps.zip)

5) Finally, I started Vina using the command:
 `vina --ligand H4Fst.pdbqt --maps 4lxd --scoring ad4 --exhaustiveness 32 --out output.pdbqt`
and the output can be found here:
[output.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963515/output.pdbqt.txt)

Appreciate advice where I made the issue.
[Full_Archive.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/14963533/Full_Archive.zip)

**Comment by rwxayheee** [comment]
Hi @farmaceut 
In PyMOL, the dimension of the box is displayed in Å
`npts 22 12 11` will generate a small box of
0.375 * 22 = 8.25 Å
0.375 * 12 = 4.5 Å
0.375 * 11 = 4.125 Å
where 0.375 Å is the spacing of the grid

**Comment by farmaceut** [comment]
Hi again @rwxayheee  :)  Thanks for quick response. So the solution would be either shifting spacing to 1 or change enpts following the equations
```
0.375 * X = 22
0.375 * Y = 12
0.375 * Z = 11
```
so  `npts  60 32 30` in that case?

**Comment by rwxayheee** [comment]
Hi @farmaceut Yes `npts  60 32 30` will give you the defined box in PyMOL without changing the spacing :>

**Comment by farmaceut** [comment]
@rwxayheee 
Albeit, `4lxd.gpf` looks now like that:

```
npts 60 32 30                        # num.grid points in xyz
gridfld 4lxd.maps.fld                # grid_data_file
spacing 0.375                        # spacing(A)
receptor_types A C NA OA N SA HD     # receptor atom types
ligand_types A HD OA                 # ligand atom types
receptor 4lxd.pdbqt                  # macromolecule
gridcenter 21.3455 31.4093 8.11142   # xyz-coordinates or auto
smooth 0.5                           # store minimum energy w/in rad(A)
map 4lxd.A.map                       # atom-specific affinity map
map 4lxd.HD.map                      # atom-specific affinity map
map 4lxd.OA.map                      # atom-specific affinity map
elecmap 4lxd.e.map                   # electrostatic potential map
dsolvmap 4lxd.d.map              # desolvation potential map
dielectric -0.1465                   # <0, AD4 distance-dep.diel;>0, constant
```

docking yielded same incorrect values:

```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1    1.048e+07          0          0
   2    1.055e+07       2.02      3.311
   3    1.073e+07      1.719      6.845
   4    1.097e+07      1.944      2.312
   5      1.1e+07      1.262      6.415
   6    1.112e+07      2.075      6.526
   7    1.123e+07       2.08      6.958
   8    1.203e+07      1.709      2.266
   9    1.208e+07      1.882       2.61
   ```

**Comment by rwxayheee** [comment]
@farmaceut 
I got something like
```
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -4.222          0          0
```
Did you run autogrid with the new gpf file?

**Comment by farmaceut** [comment]
@rwxayheee 
Yes, I used `4lxd.gpf` displayed above.  
[output.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/14965451/output.pdbqt.txt)

Comparing with yours, it seems the issue is in  INTER part... Wondering why
```
REMARK ITER + INTRA:     10991577.225
REMARK INTER:            10991577.548
REMARK INTRA:                  -0.324
REMARK CONF_INDEPENDENT:        1.492
REMARK UNBOUND:                 0.324
```

**Comment by farmaceut** [comment]
@rwxayheee 
My issue! Forgot to run `autogrid4` . Now it is more than good. Thank you! 
'''
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -4.208          0          0
   2       -4.072      1.765      6.758
   3       -3.961      1.832      2.393
   4       -3.942      2.095      2.551
   5       -3.857       2.16      6.683
   6       -3.636      4.113      7.674
   7       -3.548      2.621      3.775
   8       -3.291      4.181      6.308
   9       -3.019      3.248      7.181
   '''
