### ISSUE TITLE
Docking to zinc atoms in a non-3,1 tetrahedral conformation

### ISSUE THREAD

**Issue by Klaborator** [ccsb-scripps/AutoDock-Vina#303]
Hello,
I have been trying to set up some docking analyses using the AutoDock4Zn protocol, but the receptor I am working on has a rarer conformation type (with an adjacent Mg atom; image attached). @diogomart, I read your AutoDock4Zn paper, but since this case doesn’t conform to 3,1 tetrahedral geometry, I'm unsure how to proceed. Do you have any advice?

-K

![image](https://github.com/ccsb-scripps/AutoDock-Vina/assets/129033583/699dff3c-8a0d-4c40-9026-21b445272202)

**Comment by rwxayheee** [comment]
Hi @Klaborator Is this a phosphodiesterase? Your ligands may or may not displace all (3?) waters around Zn and Mg, if they don't contain or mimic a phosphate group. If they do, anchored docking or scoring conformers that are generated under restraints could be a way to provide some kind of ranking (relative binding energies) and potentially useful poses for further optimization. 
It would be nice to hear a little bit more from you about this receptor and ligands of interest, and what you wanted to accomplish through the docking analyses. :> @diogomart might have better advice for this. 
hope this is mildly helpful!

**Comment by Klaborator** [comment]
@rwxayheee Yes, you're correct. :-) I take it you're familiar with PDEs?
I was thinking about manually declaring a bond between Zn and my ligands in Rosetta, but this requires specific knowledge that a bond would be formed. I hoped there would be a more systematic way to conduct the docking because that wouldn't be ideal for screening large numbers of diverse ligands. In which case there might be problems with knowing whether the waters were displaced or not, which is an added complication.

**Comment by diogomart** [comment]
Hi @Klaborator

The only way the coordination geometries affect the scoring is by the addition of a TZ pseudo-atoms to (3,1) geometries. The AD4Zn potentials for oxygen and sulfur H-bond acceptors (types OA and SA) are implemented for the Zn atom itself, not the TZ pseudo atom, and therefore they are independent of the coordination geometry. It is only for nitrogen H-bond acceptors (type NA) that the TZ pseudo atom is important. Without a (3,1) geometry, there is no TZ pseudo-atom, and therefore no AD4Zn interaction for NA atoms.
  
Here are the relevant lines from the script. Note that only the first line is for TZ, all other for Zn. The supporting information of the AD4Zn paper provides more context.
https://github.com/ccsb-scripps/AutoDock-Vina/blob/350bb7f28d65265f1c86fa2362d0e469cad8b8fc/example/autodock_scripts/prepare_gpf4zn.py#L157-L162

**Comment by Klaborator** [comment]
Thanks. I need to think about how this will affect the modeling of the standard/non-canonical side chains to these metals.
