### ISSUE TITLE
Load maps for vina

### ISSUE THREAD

**Issue by linfranksong** [ccsb-scripps/AutoDock-Vina#31]
Hi,
 
I'm trying to load existing maps for vina and only score the pose with the following code, but it terminated with "Reading Vina maps ... Segmentation fault".

~/vina_1.2.2_linux_x86_64 --ligand 3ozt_105.pdbqt --maps 3ozt_protein --scoring vina --score_only

The maps were previously generated by command: 

/opt/software/MGLTools/1.5.6/MGLTools-1.5.6/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_gpf4.py -l 3ozt_105.pdbqt -r 3ozt_protein.pdbqt -o 3ozt_protein.gpf -y
autogrid4 -p 3ozt_protein.gpf -l grid.log

Could you help to debug?

Thanks!
Best,
Lin

**Comment by diogomart** [comment]
Segfault fixed in #38, closing.
