### ISSUE TITLE
Differences between `*_rigid.pdbqt` and `*.pdbqt` files of receptors

### ISSUE THREAD

**Issue by eunos-1128** [ccsb-scripps/AutoDock-Vina#313]
Hi,

I prepared `*_rigid.pdbqt` and _`*_flex.pdbqt` files using prepare_flexreceptor.py for flexible docking with vina scoring function.

Beforehand, I executed ordinary dockings (only receptors rigid) and on that time I prepared usual `*.pdbqt` files of receptors using the ADFRsuite script.

I'm not sure of differences between usual `*.pdbqt` and `*_rigid.pdbqt` files.

Can I use `*.pdbqt` files for flexible docking instead of using `*_rigid.pdbqt` if they are regarded as actually same ones(because `*.pdbqt` files are supposed to be rigid)?

if `*_rigid.pdbqt` files have differences from `*.pdbqt` ones, I'd like to know what is different from. 

Regards,

**Comment by rwxayheee** [comment]
hi @eunos-1128 
The two files are different. The PDBQT with “rigid” in its name doesn’t contain the sidechain of the modified residue. If you use a file comparison tool you can get a better look how they differ. 

For grid map computing (autogrid) and for docking, it makes more sense to use the “rigid” PDBQT as the receptor. Doing this excludes the sidechain from being doubly counted in receptor and flexible residue (which is essentially part of the mobile “ligand” in flexible docking)

**Comment by eunos-1128** [comment]
@rwxayheee 

Thank you! I understand :)
