### ISSUE TITLE
Method to capture receptor structure state after flexible docking

### ISSUE THREAD

**Issue by eunos-1128** [ccsb-scripps/AutoDock-Vina#319]
Hi, 

I'm interested in capturing the exact state of the receptor after flexible docking.

It seems there is no description about that on docs, but is there any way to do that with vina?

If not, does any other methods possible exist? 

Regards,

**Comment by rwxayheee** [comment]
Hi @eunos-1128 
What are some specific metrics you would be interested in using? Sidechain RMSD? Dihedral angles (and clustering by rotamers)? Many would use these to analyze MD trajectories of proteins. If you are able to export the after-docking structures, programs like pytraj, ProDy, or MDAnalysis have built-in functions for these measurements. Otherwise, you can also compute them by yourself using the output coordinates. 
(I personally think it's a very good idea to regroup results by distinct receptor conformations. I just don't know a very straightforward way to go from AutoDock right now

**Comment by eunos-1128** [comment]
@rwxayheee 
> What are some specific metrics you would be interested in using? Sidechain RMSD? Dihedral angles (and clustering by rotamers)?

Both of them. 

Besides calculating them, I want to take closer look at differences among conformers using molecule viewer in detail.

**Comment by diogomart** [comment]
With `mk_export.py` the sidechains are written as additional molecules to the output SDF file (they are together with the ligand).

Meeko v0.6 will be able to write a PDB of the entire protein with the updated positions of the sidechain. This is better for visualization and for integrating with other software, such as starting an MD simulation from docked poses.

@eunos-1128 is this the feature/information you were looking for?

**Comment by eunos-1128** [comment]
> With `mk_export.py` the sidechains are written as additional molecules to the output SDF file (they are together with the ligand).
> 
> Meeko v0.6 will be able to write a PDB of the entire protein with the updated positions of the sidechain. This is better for visualization and for integrating with other software, such as starting an MD simulation from docked poses.
> 
> @eunos-1128 is this the feature/information you were looking for?

@diogomart 
Yes, this is what I was looking for.

I'll try the feature of meeko :)

**Comment by eunos-1128** [comment]
@diogomart 

I could confirm sidechains in SDFs using `mk_export.py`
Thank you.

> Meeko v0.6 will be able to write a PDB of the entire protein with the updated positions of the sidechain. This is better for visualization and for integrating with other software, such as starting an MD simulation from docked poses.

I want the structure of the entire protein right now.

In Meeko's repo, there is a tag, v0.6.0-alpha.3. 
Has it had that feature already?

**Comment by diogomart** [comment]
The alpha versions do not have that feature. Only v0.6 (non-alpha) will. The alpha were created to make some receptor preparation features more easily available before the a stable v0.6 is released.

**Comment by eunos-1128** [comment]
@diogomart 

OK, Thank you. Until the feature is published, I'll manage with current version's meeko.

**Comment by diogomart** [comment]
Implemented in https://github.com/forlilab/Meeko/pull/200

**Comment by eunos-1128** [comment]
Congratulations on the completion of v0.6!

By the way, which version should I use?

I see `develop`, `v0.6.0-alpha.3`, `v0.6.0-alpha.2`, `v0.6.0-alpha.1` and `v0.6.0-alpha`. Which one is most suitable for the purpose of capturing receptor structures after flexible docking? Which one is the most suitable for capturing the receptor structure after flexible docking?

Also, `develop` seems to be much more developed than the other branches, should I use it?

**Comment by rwxayheee** [comment]
Hello @eunos-1128 

`develop` will be the official v0.6.0 (upcoming version) very very soon. Please checkout the develop branch and give it a try, and don't hesitate to reach out to us if you have any questions! 

> Which one is most suitable for the purpose of capturing receptor structures after flexible docking? 

The implementation to export entire receptor with updated residue sidechains is currently in `develop`.  We're still working on the documentation, here's the example usage to export from flexible docking: 

https://meeko.readthedocs.io/en/readthedocs/tutorial1.html#from-flexible-receptor-docking-with-autodock-vina

It requires a receptor JSON file, which can be generated from `mk_prepare_receptor.py` when other receptor files were generated. But if you don't have it, just rerun `mk_prepare_receptor.py` with the same flexible residues you used receptor preparation. There are also some syntax changes, and you could find an example usage to prepare flexible docking here: 

https://meeko.readthedocs.io/en/readthedocs/tutorial1.html#save-a-receptor-json-file-for-docking-with-flexible-and-or-reactive-residues

**Comment by eunos-1128** [comment]
@rwxayheee 
Thank you for your detailed explanation!

**Comment by eunos-1128** [comment]
@rwxayheee 
I have a question.

I use `AutoDock-Vina/example/autodock_scripts/prepare_flexreceptor.py` to prepare receptor PDBQT files for flexible docking, but I need to use `mk_prepare_receptor` instead for the new feature?

Since the past data has been put out using `prepare_flexreceptor` in the autodock vina repository, it is possible to prepare the receptor PDBQT with `prepare_flexreceptor` and use mk_export.py after docking if possible I am hoping to get a receptor PDBQT file with all side chains of the flexible docking result, but is it difficult?

**Comment by rwxayheee** [comment]
@eunos-1128 

> but I need to use mk_prepare_receptor instead for the new feature?

Yes because right now this function needs the receptor JSON file, but you only need to rerun mk_prepare_receptor.py with the `-o <basename> -j` writing option. You don't need to rerun the docking calculation

> prepare the receptor PDBQT with prepare_flexreceptor and use mk_export.py after docking?  In result, I am hoping to get a receptor PDBQT file with all side chains of the flexible docking result, but is it difficult?

No it's not difficult, in a similar case to yours I might just use a script in python or bash that manipulates the contents of PDBQT files directory. `mk_export.py` handles this in a more sophisticated way and always exports the atomistic structures (with all hydrogens) to PDB. 
There might be some subtle difference (charge and handling of incomplete residues) between the Meeko receptor and the receptor you generated from `prepare_flexreceptor`.

**Comment by eunos-1128** [comment]
@rwxayheee 

It looks like I was able to create PDBQTs for rigid and flex using `mk_prepare_receptor.py` while reading your document.

Thank you.

**Comment by eunos-1128** [comment]
@rwxayheee @diogomart 

When specifying a residue to be flexible in `mk_prepare_receptor.py`, I got an error if the chain ID is not given.

The help says `skip chain ID if it is unspecified`, but in fact it appears that the chain ID is required.

```
  -f FLEXRES, --flexres FLEXRES
                        specify the flexible residues by the chain ID and residue number, e.g. -f ":42,B:23" is equivalent to -f ":42" -f "B:23" (skip chain ID if it is unspecified)
```

Does this mean that the help is written this way in advance so that it will not be necessary to specify the chain ID in the future?

**Comment by rwxayheee** [comment]
Hi @eunos-1128 
Currently a chain ID is always required. There's no default or assumed chain ID. The only exception is when input PDB's chain ID column is empty, then the chain ID needs to be skipped in the selection language like `:42`

**Comment by eunos-1128** [comment]
@rwxayheee 
I misunderstood the meaning of `unspecified`.

Personally, I think it would be better to mention in the help message that the chain ID is mandatory.

**Comment by rwxayheee** [comment]
@eunos-1128 Got it! We can clarify that in the help message. Thanks again for the feedback, and please feel free to reach out if you have any other questions!

**Comment by eunos-1128** [comment]
@rwxayheee 

By the way, why do meeko commands have file extensions?

Usually, the commands that can be run from the terminal for packages that can be installed by pip are in the format `mk_prepare_receptor`, `mk_prepare_ligand`, or `mk_export` in the `setup.py` or `pyproject.toml`. In meeko, the file extension is `mk_prepare_receptor.py`, `mk_prepare_ligand.py`, and `mk_export.py`.

I don't have any problem with it, but I have been wondering about it for a while, so I decided to ask.

Translated with DeepL.com (free version)

**Comment by rwxayheee** [comment]
Hi @eunos-1128 
Yes, it's currently this way because of the `entry_points` in `setup.py`: 
https://github.com/forlilab/Meeko/blob/ba31e10f7a8987ae08441234e1b747301eb37642/setup.py#L55-L59
```py
    entry_points={
        'console_scripts': [
            'mk_export.py=meeko.cli.mk_export:main',
            'mk_prepare_ligand.py=meeko.cli.mk_prepare_ligand:main',
            'mk_prepare_receptor.py=meeko.cli.mk_prepare_receptor:main'
```
I don't have a very strong preference, but I like them to be `.py` to clarify that they're Python scripts, not other languages

**Comment by eunos-1128** [comment]
@rwxayheee 

Thank you for explaining:)
