### ISSUE TITLE
Zn docking-Chelation issue

### ISSUE THREAD

**Issue by Bosri-Rabeya** [ccsb-scripps/AutoDock-Vina#324]
I was trying to perform docking between HDAC enzymes and HDACi. HDACi are supposed to chelate or form two bonds with the zinc present in the HDAC enzymes. However, once I perform Docking using autodock Zn following the protocol the ligand seems to form only one bond with the zinc. How do I solve this problem?

**Comment by diogomart** [comment]
Can you send a structure with the problem?

**Comment by Bosri-Rabeya** [comment]
Thank you for your response. I have attached both the crystal structure  of HDAC6 enzyme with vorinostat (pdb=5edu) and docking result. 
![5edu-Docking](https://github.com/ccsb-scripps/AutoDock-Vina/assets/172929920/c540533c-61ab-419d-b34f-29adb747f35f)
![Crystal structure-5edu](https://github.com/ccsb-scripps/AutoDock-Vina/assets/172929920/8e4c693d-4d46-44e3-8457-c7a411cd4f0c)

**Comment by diogomart** [comment]
Interesting. If, and only if, the type in the nitrogen in NA and there's a TZ pseudo atom on the zinc, I'd try removing the TZ

**Comment by Bosri-Rabeya** [comment]
Thank you so much. I will try that and let you know if that works.

**Comment by Bosri-Rabeya** [comment]
I removed the TZ and seems like the other oxygen is now forming bond with the zinc. However, the H of the OH group seems to be in the middle. Is there any way I can cause bond rotation here. Please see the attached picture. 
![image](https://github.com/ccsb-scripps/AutoDock-Vina/assets/172929920/d5cf41b4-85a1-41e4-ae30-f60cc5199519)

**Comment by diogomart** [comment]
In 5edu both oxygens are pretty close to Zn. I wouldn't say that one is forming a bond and the other one isn't.

The ligand density isn't perfect and the ligand has higher b-factors than the surrounding protein.

The ligand has conjugated double bonds that are out of plane.

Hydroxamic acid is almost surely in hydroxamate form when chelating Zn. Ideally it would have been deprotonated before docking. AD4Zn mitigates this by removing the interaction between Zn and HD.

**Comment by Bosri-Rabeya** [comment]
After your suggestion to remove the TZ, both oxygens are close to Zn and seemed like both of them were forming bond. My apologies for any confusions from my previous text. Based on your reply, should I expect the hydrogen still attched to the oxygen  or the ligand should be in hydroxamate form? What do you mean by "AD4Zn mitigates this by removing the interaction between Zn and HD".

Do you have any other suggestions to make this docking better. 
I appreciate your help. 
Thanks a lot.

**Comment by diogomart** [comment]
The protonation state doesn't change during docking. To model the hydroxamate state (negatively charged), the H must be removed from the ligand before docking.

From the paper:
>Finally, the zinc–hydrogen pairwise interaction was eliminated to prevent clashes that would interfere with the proper interaction between groups like sulfonamide −NH2, or hydroxyl, with zinc. This allows ligands to establish the proper coordination interaction independent of the orientation of the hydrogen with respect to the heavy atom.

Ideally, autodock would sample protonation states and score their relative energies, and predict that in these metal chelation situations the most stable state is the ion state, not the acid.

**Comment by diogomart** [comment]
Closing, feel free to reopen if needed.
