### ISSUE TITLE
What kind of file is the Linux download?

### ISSUE THREAD

**Issue by johnwkeller54** [ccsb-scripps/AutoDock-Vina#328]
There is no file extension. Is it .tgz ?

**Comment by rwxayheee** [comment]
It's an executable, you may [check](https://www.geeksforgeeks.org/file-command-in-linux-with-examples/) with the `file` command

**Comment by johnwkeller54** [comment]
HI, Thank you. I had tried that, but the permissions were set wrong. Now it
works.
John Keller
