### ISSUE TITLE
unknown option protein

### ISSUE THREAD

**Issue by dnapolren** [ccsb-scripps/AutoDock-Vina#333]
Hi,

The following (attachment error is obtained when I attempt to dock:

![image](https://github.com/user-attachments/assets/9357b83e-14fe-4a46-877b-577891d3cae0)

I am a novice. Kindly help resolve the error. Thank you.

**Comment by diogomart** [comment]
Hi, that unknown option in the config.txt file

**Comment by dnapolren** [comment]
@diogomart thanks for the reply. So this is how my config file looks like:
![image](https://github.com/user-attachments/assets/89149188-54c7-4630-af11-e2571cd28181)
is there something that I am missing here which requires rectification?

**Comment by rwxayheee** [comment]
Hi @dnapolren 
The words you use in config file need to match exactly with the given names in the help message (protein -> receptor, centre -> center)

**Comment by dnapolren** [comment]
@rwxayheee thank you so much. will work on it.

**Comment by dnapolren** [comment]
Thank you all. The suggestions worked. :)
