### ISSUE TITLE
Randomize ligand conformation - results include starting pose

### ISSUE THREAD

**Issue by and-tos** [ccsb-scripps/AutoDock-Vina#336]
I want to randomize the starting pose of my ligand to remove bias from the initial pose, but it seems that the original conformation is still included when I run the following lines. Is there an error in my code? Or am I misinterpreting the meaning of the `randomize` method?

```
n_poses = 20
v = Vina()
v.set_receptor(str(rec_pdbqt))
v.set_ligand_from_file(str(lig_pdbqt))
v.compute_vina_maps([0.0, 0, 0], [30, 30, 30])
v.randomize()
v.dock(exhaustiveness=16)
```

**Comment by diogomart** [comment]
The randomization affects only rotatable bonds and the overall orientation of the ligand. Bond lengths and angles are not changed. Does this explain what you observe?

Our usual protocol for removing bias from the x-ray positions of the ligand is to create 3D coordinates from smiles with https://github.com/forlilab/scrubber

**Comment by and-tos** [comment]
Thanks for clarifying, is there a way to export the randomized structure?

**Comment by diogomart** [comment]
Unfortunately, we overlooked that and didn't expose it to Python. Only from command line. Sorry about that..
