### ISSUE TITLE
Replace non-bonded interactions of specified atom pairs

### ISSUE THREAD

**Issue by YGuangye** [ccsb-scripps/AutoDock-Vina#342]
Is it possible to cancel non-bonded interactions between specified atom pairs and introduce custom potential instead?

**Comment by diogomart** [comment]
Unfortunately no. You could try smina (not developed by us) or the `--modpair` option in autodock-gpu, which doesn't allows limited customization, but maybe is enough for your purposes. You can also use meeko to customize the atom typing with smarts.
https://github.com/ccsb-scripps/autoDock-gpu
https://github.com/forlilab/meeko

**Comment by YGuangye** [comment]
Thank you very much for your reply. Modifying parameters based on atom types might not be sufficient for my needs, as I intend to replace interactions between specific atoms identified by their indices, regardless of their atom types. To achieve this, would it be necessary to modify the source code?

**Comment by diogomart** [comment]
Yes, it would be necessary to modify the source.

**Comment by YGuangye** [comment]
Thank you!
