### ISSUE TITLE
May I add the executables for mac_aarch64 to release 

### ISSUE THREAD

**Issue by rwxayheee** [ccsb-scripps/AutoDock-Vina#343]
The binaries for mac_aarch64 were generated in the workflow runs via Actions as artifacts from a recent PR: 
https://github.com/ccsb-scripps/AutoDock-Vina/actions/runs/10747528706

May I include them in [release](https://github.com/ccsb-scripps/AutoDock-Vina/releases)? Someone asked for the executables, and I pointed them to download the artifacts. But the artifacts will soon expire after the retention time. 

Compared to the existing release, the only difference is a minor change in boost usage I introduced in #340. Many others, like [this fork](https://github.com/ccsb-scripps/AutoDock-Vina/commit/65679888164d49e7b20f6f2b77546c24ab8b5a81), have made similar efforts to adapt to newer boost versions)

**Comment by diogomart** [comment]
For sure! Thanks for looking into this.

**Comment by rwxayheee** [comment]
Thanks @diogomart ! I have made the updates to release
