### ISSUE TITLE
Question about the Rii in AD4.1_bound.dat

### ISSUE THREAD

**Issue by Aochzh** [ccsb-scripps/AutoDock-Vina#346]
Dear Autodock community,

I have a question regarding the official atomic parameter file AD4.1_bound.dat (https://autodock.scripps.edu/wp-content/uploads/sites/31/2019/03/AD4.1_bound.dat).

For the column of Rii, it says it stands for the "sum of vdW radii of two like atoms (in Angstrom)". For atoms like H and C, the data (H: 2.00 and C: 4.00) look normal. However, in the cases of Mg, Ca, Zn and so on, the Rii (Mg: 1.30,  Ca: 1.98, Zn: 1.48) look like the single atom vdW radii. 

And in Vina's source code, the atom_constants.h file, the radius of Mg, Ca and Zn is 0.65, 0.99 and 0.74, respectively, which is half of the value in comparison to AD4.1_bound.dat.

I was wondering how these data are determined. Thank you very much in advance!

**Comment by rwxayheee** [comment]
Hi @Aochzh 

I don’t know the origin of the data.. But I think the values are based on the radii of the cations, which would be much smaller than the vdw radii of the neutral atom. 

In AD4.1_bound.dat, the Rii values are 2x the single-atom radius.
 
You’re right that the radii in Vina’s source code (https://github.com/ccsb-scripps/AutoDock-Vina/blob/develop/src/lib/atom_constants.h) is single-atom radius.

**Comment by rwxayheee** [comment]
Thanks for writing back by email. I will close the issue for now, but please feel free to reopen and leave a comment if you have any further questions about this.

**Comment by diogomart** [comment]
The AD4 vdW radii are based on old Amber forcefields as far as I know. Based on the values on this website, cations do indeed have relatively smaller radii: https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/vdwtables.html

**Comment by rwxayheee** [comment]
Hi @Aochzh 
Just a note on the same file I showed the other day: 
https://github.com/phenix-project/geostd/blob/3ab6c85fe18352fb61256207b63e311ac41b8695/ener_lib.cif#L125-L130
These parameters are used by Phenix (and maybe some peripheral tool packages like cctbx

**Comment by Aochzh** [comment]
Thank you for taking care of this! @rwxayheee

The VdW radii of the metal elements in the file for Phenix you shared also reminds me of the column of "vol = atomic solvation volume (in Angstrom^3)  (4/3*pi*(Rii/2)**3))" for metal atoms in AD4.1_bound.dat. 

I felt a bit strange about the volume column for metal atoms before.
For example, Mg and Mn have the same Rii values (1.30) in AD4.1_bound.dat, but they have different volume values (1.5600 and 2.1400):
```
atom_par Mg     **1.30**  0.875   **1.5600**  -0.00110  0.0  0.0  0  -1  -1  4	# Non H-bonding Magnesium
atom_par Mn     **1.30**  0.875   **2.1400**  -0.00110  0.0  0.0  0  -1  -1  4	# Non H-bonding Manganese
```
Now I guess, the Rii used to calculate the volume may not be the exact Rii values in AD4.1_bound.dat (should be closer to the VdW radii in the Phenix file you shared). This makes more sense since the atom size of Mg and Mn should be different. :-)
