### ISSUE TITLE
Update docs for meeko v0.6 which includes receptor prep

### ISSUE THREAD

**Issue by diogomart** [ccsb-scripps/AutoDock-Vina#353]

**Comment by rwxayheee** [comment]
This branch has work in progress: 
https://github.com/rwxayheee/AutoDock-Vina/tree/update_doc

- I updated basic and flexible docking tutorials. A preview: 
[https://rwxayheee-autodock-vina.readthedocs.io/en/latest/](https://rwxayheee-autodock-vina.readthedocs.io/en/latest/)

- I also updated the example files. Renamed folder solution to output.
