### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by ivnsch** [ccsb-scripps/AutoDock-Vina#364]
Following the [instructions](https://autodock-vina.readthedocs.io/en/latest/installation.html) to build from source. Made sure that the command line tools are installed, ran `brew install boost swig` and cloned the repo. Then:
```
cd AutoDock-Vina/build/mac/release
make
```
Which produces an error:

```
g++ -static -pthread -ansi -Wno-long-long -O3 -DNDEBUG -std=c++11 -DVERSION=\"v1.2.5-50-g986e7b6\" -I /usr/include  -I ../../../src/lib -o main.o -c ../../../src/main/main.cpp 
In file included from ../../../src/main/main.cpp:28:
In file included from ../../../src/lib/parse_error.h:26:
../../../src/lib/common.h:39:10: fatal error: 'boost/serialization/vector.hpp' file not found
   39 | #include <boost/serialization/vector.hpp> // can't come before the above two - wart fixed in upcoming Boost versions
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [main.o] Error 1
```

it might not be finding boost? maybe missing an environment variable? thanks!

Mac M1

**Comment by rwxayheee** [comment]
Hi @ivnsch 
vector.hpp is available via brew install. On my Mac M2 it locates at: 
`/opt/homebrew/Cellar/boost/1.86.0_2/include/boost/serialization/vector.hpp`
[Currently in the develop branch, the provided default Makefile](https://github.com/ccsb-scripps/AutoDock-Vina/blob/986e7b684d6cf9807a13fc701756381760ea00cf/build/mac/release/Makefile) attempts to find it under the brew install prefix. It seemed to work (???) for me but now I'm unsure if it's correct.. Maybe it should be looking up the boost prefix instead? 

In the Makefile, could you try: 

```
BASE := $(shell brew --prefix boost)
```

Thanks!

**Comment by ivnsch** [comment]
Reinstallation fixed it, thanks!
