### ISSUE TITLE
Batch docking error: could not open "ligands\*.pdbqt" for reading.

### ISSUE THREAD

**Issue by bug-blaster** [ccsb-scripps/AutoDock-Vina#366]
I'm running Vina straight from cmd as admin on Windows 11. While trying to dock multiple ligands at once using `vina_1.2.5_win.exe --config config.txt --batch ligands\*.pdbqt` I eventually always encounter the same error: `Error: could not open "ligands\*.pdbqt" for reading.`
If instead of using a wildcard I specify one ligand, as in `vina_1.2.5_win.exe --config config.txt --batch ligands\ligand1.pdbqt`, Vina works just fine and outputs a file of my docked ligand poses. I have tried to do this using different ligands and receptors and different methods of ligand and receptor preparation, but the results remain the same.
If anyone could point out what exactly is the issue here or suggest an alternative procedure for batched docking, I would greatly appreciate it.  Feel free to point out the obvious, I'm new to Windows 11 as well as to Vina and Github.

Here is my config.txt file:
```
receptor = receptor.pdbqt
dir = Output

cpu = 16
 
center_x =  0
center_y =  0
center_z =  0
 
size_x = 13
size_y = 13
size_z = 13
```

**Comment by diogomart** [comment]
I think the wildcards just don't expand on Windows: https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths?rq=1

A bit of a random suggestion: try powershell (if you are not using it already).

**Comment by diogomart** [comment]
Thank you for sharing that command!
