### ISSUE TITLE
ubuntu 20.04 crashes

### ISSUE THREAD

**Issue by sherwoodyao** [ccsb-scripps/AutoDock-Vina#39]
I downloaded the 1.2.2 release binary to Ubuntu 20.04, and it crashed very quickly after I launched the program with the message "killed", while I set verbosity=2, I still didn't see much command output.

````
Center: X 209.65 Y 192.37 Z 296.58
Size: X 10 Y 18 Z 24
Grid space: 0.375
Exhaustiveness: 8
CPU: 12
Verbosity: 2

Killed
````

When I used the 1.1.2 (the windows version), the same command runs fine for 4 hours. (~50%), I have hoped to the 1.2.2 version would allow us get results faster.

**Comment by jeeberhardt** [comment]
Hi,

Sorry for the inconvenience, Vina 1.2 can still suffer from its young age sometimes. In order to narrow down the issue, could you try the [basic docking](https://autodock-vina.readthedocs.io/en/latest/docking_basic.html) example and see if it works?

Thanks!

Jerome.

**Comment by sherwoodyao** [comment]
Will try the basic docking example today.

Is there a way to turn on more tracing for the v1.2 program so that we know where it crashes?

How much memory does the program require? could it be out of memory error? I noticed when I asked the program to use 12 CPU cores, it only used 1-2 cores, but the memory seems maxed out on the 24GB system

![image](https://user-images.githubusercontent.com/842068/134183717-9ce03b7d-1b8e-4308-8560-6ed2ac002e23.png)

**Comment by jeeberhardt** [comment]
Hi,

Unfortunately no, Vina cannot be more verbose than the highest verbosity mode (2).

Fore sure, 24 GB seems to be a lot but it all depends on the size of your grid and the ligand. Without details from your side I cannot be conclusive on the situation you are experiencing. 

Running the basic docking example from the documentation, Vina 1.2.x takes about 570 MB and use all the available cores on my machine (24 cores, Ubuntu 20.04.3 LTS). In comparison, Vina 1.1.2 (without recompiling it) takes about 775 MB in total.

**Comment by sherwoodyao** [comment]
Hi Jerome, Thanks for the help, I sent you in email the protein and our ligand pdb file, and maybe you can evaluate the memory consumption. Our ligand is an ssDNA aptamer folded via mFold+RNAComposer, and it has ~1500 atom lines. Are you aware of any Aptamer based ligand simulation best practice?

**Comment by diogomart** [comment]
If the ligand was an aptamer, it may have been too large. Vina is designed for docking small organic molecules. Closing, feel free to re-open if needed.
