### ISSUE TITLE
Vina 

### ISSUE THREAD

**Issue by ShwetaSC** [ccsb-scripps/AutoDock-Vina#4]
Hello
I have started working on multiple ligands docking while running sample data provided here. On Step Running autodock vina using autodock4 forcefield (--ligand 5x72_ligand_p59.pdbqt 5x72_ligand_p69.pdbqt --maps 5x72_receptor) 
 I got the error mentioned below
Command line parse error: unknown option maps
Please help, what is wrong

**Comment by jeeberhardt** [comment]
Hi SchwetaSC,

Could you tell me which version of Vina are using? Executing the following command: `vina --version` should output something like this `AutoDock Vina 1.2.0 (September 11, 2020)`. The `--maps` argument is only available for Vina >= 1.2.0.

Best,
Jerome.

**Comment by ShwetaSC** [comment]
Hey


Thank you for the response, I have checked the older version (1.1.2) is
installed on my PC. Please help from where I can install the latest version
of vina.



One more query I have while running command

"vina --receptor 5x72_receptor.pdbqt --ligand 5x72_ligand_p59.pdbqt
5x72_ligand_p69.pdbqt"

Error : Command line parse error: too many positional options

Is this error is also associated with the older version?



Thank you

**Comment by ShwetaSC** [comment]
Is it possible to run the program on the Windows system?

**Comment by jeeberhardt** [comment]
Hi,

You can get the latest version of the Vina binaries (linux and macOS) from here: https://github.com/ccsb-scripps/AutoDock-Vina/releases/tag/v1.2.0.dev3.

Yes, the previous version (1.1.2) does not handle multiple ligands.

We didn't plan to release a version for Windows in the near future, sorry.

**Comment by ShwetaSC** [comment]
Jérôme Eberhardt thank you so much

**Comment by jeeberhardt** [comment]
You are welcome. Enjoy! ;-)
