### ISSUE TITLE
Report docking scores with more significant figures 

### ISSUE THREAD

**Issue by yunhuige** [ccsb-scripps/AutoDock-Vina#40]
Hi,

Is there a way to output docking scores with more sig figs? In the previous version (v1.1.2), we used "--score_only " flag with top docked poses. We tried to use this flag in this new version (v1.2.2) but we couldn't get more sig figs.

I attached our input files and protocol we used. 

Thanks!

[score_only.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/7270371/score_only.zip)

**Comment by diogomart** [comment]
Hi,

We will consider increasing the value of `setprecision()` in [this block](https://github.com/ccsb-scripps/AutoDock-Vina/blob/de753ccc2514b8ad46dfaf38f1956c9b2a1f50e6/src/lib/vina.cpp#L685-L700). The drawback to that it makes it look like docking scores are very accurate.

Meanwhile, I increased the precision of the output here: https://github.com/diogomart/AutoDock-Vina/releases/tag/six_sigfigs

**Comment by yunhuige** [comment]
Thank you! I think we are good for now with the six sigfigs patch. I still think more sig figs are helpful in the case of ranking analysis. Especially when we work with a large library, it is more possible to have the same score for multiple compounds with only 4 sig figs.
