### ISSUE TITLE
Can I dock a ligand to Zn binding protein using vina not autodock4?

### ISSUE THREAD

**Issue by hima111997** [ccsb-scripps/AutoDock-Vina#42]
Can I dock a ligand to Zn binding protein using vina not autodock4? and how?

**Comment by diogomart** [comment]
Yes. Since Vina has parameters for zinc, it's just like any regular docking.

**Comment by hima111997** [comment]
so i just convert the receptor to pdbqt as shown on the documentation then perform the docking directly without generating the affinity maps?

**Comment by hima111997** [comment]
the file I sent is the pdb file downloaded from the protein data bank after removing some atoms only. can you tell me how is it unusual, please?
