### ISSUE TITLE
how can I save all of the 10 dock poses after dock in the code write_poses("vinaout.pdbqt",n_poses=10)?

### ISSUE THREAD

**Issue by xxy90** [ccsb-scripps/AutoDock-Vina#44]

**Comment by jeeberhardt** [comment]
Hi, 

There is another parameter to take also in account. The `energy_range` parameter is set to 3.0 kcal/mol, so if the energy difference between the top pose and the 10 th pose is higher than 3.0 kcal/mol, then it won't be written. This is likely the case in your situation, could you check please (by increasing the `energy_range` to 5.0 for example)?

`write_poses("vinaout.pdbqt", n_poses=10, energy_range=5.0, overwrite=True)`

Jérôme.

**Comment by xxy90** [comment]
Thank you very much!
