### ISSUE TITLE
Result with seed is not reproducible using the python version vina, and also differ from the one shown in the tutorial document

### ISSUE THREAD

**Issue by chiwwong** [ccsb-scripps/AutoDock-Vina#47]
I was using the input files provided in the repository (basic docking), and got the following result:
Scoring function : vina
Rigid receptor: receptors/1iep_receptor.pdbqt
Ligand: ligands/1iep_ligand.pdbqt
Center: X 15.19 Y 53.903 Z 16.917
Size: X 20 Y 20 Z 20
Grid space: 0.375
Exhaustiveness: 32
CPU: 0
Verbosity: 1

Computing Vina grid ... done.
Performing docking (random seed: -131415392) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -13.62          0          0
   2       -12.77      1.136      1.451
   3       -9.877      2.853      13.45
   4       -9.808      1.766      13.59
   5       -9.453       1.86      13.33
   6       -8.454      1.317      1.902
   7       -8.367      3.759      6.488
   8       -8.291      1.864       13.6
   9       -8.054      3.032      5.982

At the same time, the pdbqt file generated by the python package has the best docking score (using the same seed) as -14.628

**Comment by DarthSaddest** [comment]
Even if you incorporate the same seed, [the result will vary from one _system_ to another](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4801993).
