### ISSUE TITLE
Positive scores with AD4 scoring function

### ISSUE THREAD

**Issue by msteklac** [ccsb-scripps/AutoDock-Vina#48]
Hi Autodock Vina forum,
We are trying to switch from original Autodock 4.2.6 version to new Autodock Vina 1.2.2 version. To preserve continuity of our calculations, we have chosen to employ AD4 scoring function as implemented in Autodock Vina 1.2.2 with the following command. 

"$Vina"/build/linux/release/vina --ligand $ligand.pdbqt --maps ${protein} --scoring ad4 --exhaustiveness 40  --out ${ligand}_${protein}_ad4_total.pdbqt >> ${ligand}_${protein}_ad4_log.txt
(where variables ligand and protein are substitutes for the working structures).

However, upon test runs of 48 randomly selected compounds from an external database with various settings of exhaustiveness, we have arrived at somewhat confusing results. For each “docking run” there were several compounds with positive docking score whose predicted binding poses were as expected, that is, compound was found in the active site cavity without any overlap of ligand/protein atoms. Furthermore, these positive scores appear to be completely randomized as they can occur at certain exhaustiveness settings, only to disappear for others (see attached file Vina_AD4_scoring_results.xls). We have tried the docking with increased grid box size without any specific improvement. All ligands contain standard atom types that are recognized by the forcefield as evidenced by the fact that no compound has failed at all exhaustiveness settings.
Is there something that we are doing wrong? Or is this perhaps an issue that has already been raised/encountered by someone else?
Thank you for your answer.
##########
Autodock vina version:
1.2.2 
downloaded 16 of August 2021, built from source according to installation.rst present in the downloaded file
Operating system and version:
Debian GNU/linux 9
##########
Attached files:
Vina_AD4_scoring_results.xls (results in question are highlighted for your convenience)
[Vina_AD4_docking_results.xlsx](https://github.com/ccsb-scripps/AutoDock-Vina/files/7418312/Vina_AD4_docking_results.xlsx)

**Comment by msteklac** [comment]
Hi, 

thank you for your response. I have attached all files corresponding to one of the examples of such behaviour. Upon close inspection it appears that the problem is caused by empty potential maps.  However, as this problem occurs for different compounds at different level of variance I am not sure if it
[10462221_6WQF.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/7482008/10462221_6WQF.zip)
 originates in the compounds' structures.

Thank you for your answer.

**Comment by jeeberhardt** [comment]
Hi,

Could you tell us which version of autogrid4 are you using? I tried with version 4.2.6 and it worked just fine using your PDBQT and gpf files. 

Also just by curiosity, is there any particular reason why you are using a grid spacing of 0.275 and not the default 0.375?

Best,
Jerome.

**Comment by msteklac** [comment]
Hi,

we have used AutoGrid 4.2.7.x.2019-07-11 from ADFR suite that came in with this new Vina version.
The grid spacing setting is part of the test setups (spacing/exhaustivness). Alright, I'll try to do clean reinstall to see if something changes.

Thank you.

**Comment by diogomart** [comment]
Vina should check that the number of values read in from .map files matches the header. In the zip file from @msteklac, the header says `NELEMENTS = 90, 90, 90` but zero values exist.

**Comment by msteklac** [comment]
I have determined the problem is in fact with the AutoGrid4.2.7 that I had been using.
Unfortunately uninstall did not help, so I have decided to go back to using AutoGrid4.2.6, which appears to be working fine.

Thank you for all your help.
