### ISSUE TITLE
About prepare_receptor error

### ISSUE THREAD

**Issue by kch38896** [ccsb-scripps/AutoDock-Vina#51]
Hi,

I have issues with "prepare_receptor".
When I read 1iep.pdb in the audock vina document, it worked fine.

But, In5tgz.pdb, It worked with the following warning message.
"""
WARNING! 5tgz has 16  atoms with alternate locations named ['A', 'B']!

WARNING! using alternate location A
"""

Also, when I read 5e8m.pdb, 1p0i.pdb, 5e97.pdb, 5e98.pdb, and etc, it failed with the following error message.
ex) About 1p0i.pdb
"""
WARNING! 1p0i has 66  atoms with alternate locations named ['A', 'B']!

WARNING! using alternate location A
'B ' apparently composed of not std residues. Deleting
'C ' apparently composed of not std residues. Deleting

AttributeError: member babel_type not found
"""

Why the error occurs and how to fix it?

Best,
kyudam

**Comment by diogomart** [comment]
Hi,

This is just a suggestion as I don't know for sure that it works: to clean up the PDB file with an external tool for sanitizing PDB files for molecular dynamics simulations. For example: https://ambermd.org/tutorials/basic/tutorial9/index.php

For mgltools issues the mailing list may be a better forum: https://autodocksuite.scripps.edu/support/

Good luck,
