### ISSUE TITLE
Vina installation

### ISSUE THREAD

**Issue by jmechua-itsrdc** [ccsb-scripps/AutoDock-Vina#54]
I am experiencing a problem installing Vina 1.2 in Ubuntu 20.04 LTS. After the step where in I need to input "python setup.py build install", this error showed.

File "setup.py", line 280
    sep='\n')
       ^
SyntaxError: invalid syntax

Upon checking the entire code it says os.path.sep but it also did not work either.

I will appreciate your help. Thanks.

Joanna

**Comment by diogomart** [comment]
Hi,

Vina only works with python3, not with python2.
See here for more information: https://autodock-vina.readthedocs.io/en/latest/installation.html#python-bindings

**Comment by jmechua-itsrdc** [comment]
Hi, 

My python version is 3.7.11.

**Comment by jmechua-itsrdc** [comment]
So should I use python3 setup.py install instead?

**Comment by diogomart** [comment]
The error you posted occurs because the `sep` argument is unknown to the `print` function in python 2. If by typing `python` you get python 3, there should be no need to type `python3`.

**Comment by jmechua-itsrdc** [comment]
When I type python --version I get the Python 3 version. Even the conda environment where vina directory is located is using Python 3. I am not exactly where what went wrong along the way.

**Comment by diogomart** [comment]
I have no idea about what might be happening. Please post here when you find out, I'm curious about the mysterious ways of conda/python :-)

**Comment by jmechua-itsrdc** [comment]
The installation went successfully after I used python3 instead of python (equivalent to python2). However, when I tried calling vina, there was no vina.

**Comment by jeeberhardt** [comment]
Hi,

Yes, this is normal. The python bindings and binary installations are still two separate processes..

Best,

**Comment by diogomart** [comment]
@jmechua-itsrdc the command line executables are available here for download: https://github.com/ccsb-scripps/AutoDock-Vina/releases
