### ISSUE TITLE
Download Autodock Vina on website

### ISSUE THREAD

**Issue by Yao-himekaido** [ccsb-scripps/AutoDock-Vina#55]
I tried to download the Setup.exe through this website https://vina.scripps.edu/downloads/
but the download page shows nothing except a test.exe which is not executive anyway.

**Comment by diogomart** [comment]
You can download from here: https://github.com/ccsb-scripps/AutoDock-Vina/releases

**Comment by Yao-himekaido** [comment]
Thanks but what should I do to these files? I'm a Win10 user but the vina_1.2.3_windows_x86_64 file doesn't have a .exe extension. The Installation chapter in the manual also mentions nothing about Windows OS.

**Comment by diogomart** [comment]
It's meant to be run from the command prompt. Use the `cd` command to navigate to the directory where the file is located, for example `cd Downloads`, and then type the name of the file to run it.

**Comment by stowelle** [comment]
I am having an issue with this also. When I try to run the vina_1.2 file on command line I get an error that says "is not recognized as an internal or external command, operable program or batch file."

**Comment by diogomart** [comment]
I'm not a windows expert, but this may help: https://stackoverflow.com/questions/48321639/is-not-recognized-as-an-internal-or-external-command-operable-program-or-bat
