### ISSUE TITLE
Permission Denied when trying to run AutoDock Vina

### ISSUE THREAD

**Issue by Cventura10** [ccsb-scripps/AutoDock-Vina#56]
When doing the tutorial everything works until I try to run Vina. Every time I try to run Vina I get zsh: permission denied: ./vina_1.2.2_macos_x86_64. Is there something I did wrong with the installation?

**Comment by diogomart** [comment]
Look up the `chmod` command. Looks like you need to give permission for that file to be executed.

**Comment by Cventura10** [comment]
I tried doing that which I saw from a previous issue but it didn't work. I did brew install boost and it now fully works.

**Comment by diogomart** [comment]
That's interesting. Thank you for reporting what worked for you.
