### ISSUE TITLE
Mac OS download

### ISSUE THREAD

**Issue by stowelle** [ccsb-scripps/AutoDock-Vina#57]
When I download the Mac OS file and try to open, I get an error that says I don't have any applications to open this type of file. I've tried following online tutorials for installation but they're older so the files are different (from before the Vina website changed) and I'm not sure where to go from here

**Comment by diogomart** [comment]
This may help: https://github.com/ccsb-scripps/AutoDock-Vina/issues/55

**Comment by diogomart** [comment]
Also: https://ubuntu.com/tutorials/command-line-for-beginners#9-conclusion
Even though this was written for linux, probably all of it applies to mac os.
