### ISSUE TITLE
ERROR: The ligand is outside the grid box

### ISSUE THREAD

**Issue by sarisabban** [ccsb-scripps/AutoDock-Vina#58]
In the latest vina version for python 3.9.7 there seems to be an issue with the v.optimize() function or the v.compute_vina_maps() or something in between. It seems vina is not aligning or moving the ligand into the search box before running the minimisation or scoring steps. Here is more explanation:

From the tutorial, 1iep_ligand.pdbqt is found within the search space of 1iep_receptor.pdbqt by default causing no errors. But using the same ligand (from the zinc15 database) with a different starting coordinate location gives "ERROR: The ligand is outside the grid box". This problem does not seem to be present in vina's python 3.8 version, but it is present in vina's python 3.9 version.

Here is how to replicate the error in python 3.9.7 ([link to the zinc.pdbqt file](https://paste.debian.net/plain/1220633) - everything else is from vina's github and tutorial):

**Python script:**
from vina import Vina
v = Vina(sf_name='vina', seed=-1630626792)
v.set_receptor('1iep_receptor.pdbqt') # also replace with zinc.pdbqt
v.set_ligand_from_file('1iep_ligand.pdbqt')
v.compute_vina_maps(center=[15.190, 53.903, 16.917], box_size=[20, 20, 20])
v.optimize()
v.dock(exhaustiveness=32, n_poses=5)

**Operating system:**
Linux Mint for python 3.8.5
Linux Ubuntu for python 3.9.7

**Running on python 3.8.5:**
1iep_receptor.pdbqt
Computing Vina grid ... done.
Number of local optimization steps: 22
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1     -13.4415     0.0000     0.0000
   2     -11.4492     3.0314    12.4120
   3     -11.3302     3.8301    12.2556
   4     -10.9768     1.6118    13.5530
   5     -10.6253     2.4966    12.5517

zinc.pdbqt
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1     -11.3168     0.0000     0.0000
   2     -10.0187     2.4323    13.5227
   3      -9.2159     7.9696    12.5398
   4      -9.0732     3.7733     8.0975
   5      -8.9076     2.6083    12.7736

**In python 3.9.7:**
1iep_receptor.pdbqt
Computing Vina grid ... done.
Number of local optimization steps: 22
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1     -13.1556     0.0000     0.0000
   2     -12.6289     0.8226     1.1902
   3     -11.9645     1.0407     1.5865
   4     -11.1891     2.9827    12.4195
   5     -11.0036     3.7423    12.2485

zinc.pdbqt
Computing Vina grid ... done.
ERROR: The ligand is outside the grid box. Increase the size of the grid box or center it accordingly around the ligand.

**Temporary solution:**
Commenting out the v.optimize() line stops the Error from happening and the script continues to the docking step, but then no minimisation is taking place before docking.

**Question:**
1. Is v.optimize() required for virtual screening?
2. Is there a way to fix the code (if this is a bug)?
3. Is there a way to forcefully or manually re-position the ligand within the search space to overcome this error?
4. If the analysis of the error is incorrect, then how to correctly overcome this error?

**Comment by diogomart** [comment]
Hi,

It's not necessary to call `v.optimize` before docking. The `v.optimize` call does local search, but docking consists of a long series of Monte-Carlo moves combined with local search, so doing one extra local search prior to docking has no effect. Additionally, the ligand is fully randomized at the start of the docking.

In case you were expecting an improvement in 3D geometry with `v.optimize`, that's unfortunately not the case, as bond angles and distances are kept rigid.

Seems like you have different vina versions installed in different environments (with python 3.8 and 3.9), but i'll try to reproduce that at a later date.
