### ISSUE TITLE
MacOS executable not working

### ISSUE THREAD

**Issue by shradheyagupta** [ccsb-scripps/AutoDock-Vina#59]
I have MacBook Air (M1,2020)
macOS Monterey 12.0.1

I downloaded vina_1.2.3_mac_x86_64 and tried to run it from the terminal with "./vina_1.2.3_mac_x86_64", but it is not running. Same with vina_1.2.2_macos_arm64. When I extracted the info, it showed that it was a document file. I'm guessing it should show " Unix Executable File " but it doesn't. I tried all of the other releases available on github and encountered the same problem.

I also followed solution by @atillack issue #14 but no success. Below is the screenshot.

<img width="1256" alt="Screenshot 2021-11-24 at 11 36 06 PM" src="https://user-images.githubusercontent.com/61943583/143292161-d054c730-73b5-46c7-a60a-9ab50388184b.png">

**I downloaded Vina for Mac from the old site a few months ago, and it works perfectly.** How to resolve it?

<img width="583" alt="Screenshot 2021-11-24 at 11 42 05 PM" src="https://user-images.githubusercontent.com/61943583/143292725-01ccf539-302f-48a0-8a12-c580f7ab5827.png">

**Comment by navanchauhan** [comment]
Install Homebrew and then install boost

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install boost
```
