### ISSUE TITLE
Vina pip installation issue

### ISSUE THREAD

**Issue by mandar5335** [ccsb-scripps/AutoDock-Vina#60]
Hi,
I am trying to install vina by creating an environment on Ubuntu 20.04. 

conda create -n vina python=3
conda activate vina
python -m pip install --upgrade pip
pip install vina

However, I am facing some installation errors with pip. A complete error file is attached here.

Failed to build vina
ERROR: Could not build wheels for vina, which is required to install pyproject.toml-based projects

[error.log](https://github.com/ccsb-scripps/AutoDock-Vina/files/7609872/error.log)

**Comment by jeeberhardt** [comment]
Hi Mandar,

It looks like you are using python 3.10, however there are no python wheels for that version yet. As a fallback, it is attempting to compile Vina from the source. But for that, swig and boost-cpp need to be installed.

Do `conda install -c conda-forge swig boost-cpp numpy`.

Best,

**Comment by mandar5335** [comment]
Hi Jérôme,
Thanks for your answer and for pointing out the issue with the Python version.
I have successfully installed vina by choosing Python=3.7 while setting the environment as:

conda create -n vina python=3.7

Thanks,

**Comment by DrHasitha** [comment]
To install python 3.7

## create empty environment
conda create -n vina

## activate
conda activate vina

## use x86_64 architecture channel(s)
conda config --env --set subdir osx-64

## install python, numpy, etc. (add more packages here...)
conda install python=3.7 numpy
