### ISSUE TITLE
pip install issue on Windows

### ISSUE THREAD

**Issue by jiteshdoshi** [ccsb-scripps/AutoDock-Vina#61]
While vina python library gets easily installed on linux and on WSL, facing issues installing it for Windows. 

[error.log](https://github.com/ccsb-scripps/AutoDock-Vina/files/7613040/error.log)
 
Prior to `pip install vina` command, installed boost, boost-cpp, py-boost and swig as well. Error still persists saying

`Boost library is not installed in this conda environment`
and `ERROR: No matching distribution found for vina`

(Env was created with both python 3.7 and 3.8)

Complete error is attached

**Comment by blakperlz** [comment]
+1 for version 1.2. Also the [pypi documentation]([https://pypi.org/project/vina/]) has not been updated for windows support.  If windows will not be supported, please let us know so the department can switch to macOS

**Comment by diogomart** [comment]
At the moment we can't guarantee support for the python bindings on Windows. Sorry about that!
