### ISSUE TITLE
MAC M1 OS, AutoDock Vina installation in a Conda environment is not working 

### ISSUE THREAD

**Issue by ADarkleg** [ccsb-scripps/AutoDock-Vina#62]
I'm Mac M1, Monterey 12.0.1 user

I try to install auto dock vina using Conda environment refer to installation guide

$ conda create -n vina python=3
$ conda activate vina
$ conda config --env --add channels conda-forge

$ conda install numpy
$ pip install vina

but I thin install vina was fail and I could only see the this massage
<img width="1925" alt="스크린샷 2021-12-04 오후 7 58 24" src="https://user-images.githubusercontent.com/95416624/144707103-5ddd5c00-da26-489e-8476-687e7c198cc2.png">

<img width="1934" alt="스크린샷 2021-12-04 오후 8 01 46" src="https://user-images.githubusercontent.com/95416624/144707108-d7101a01-fa8b-469b-9665-158509b113d3.png">

I'm so glad If you let me know how I can solve it

**Comment by diogomart** [comment]
Hi, 

It seems that you need to install Boost in that conda environment. However, we have tested the vina python bindings for Linux and Mac Intel, so it's possible that it won't work anyway.
