### ISSUE TITLE
Batch mode on windows command prompt

### ISSUE THREAD

**Issue by jiteshdoshi** [ccsb-scripps/AutoDock-Vina#63]
When batch mode is used on Linux terminal with a pattern with wild card, it works perfectly file. For example, If I have multiple ligands like ligand1.pdbqt, ligand2.pdbqt ligand3.pdbqt etc, just giving `--batch ligand*.pdbqt` does the job, but when same is used in windows command prompt, it looks for a file named ligand*.pdbqt and fails to run. How can this be done in windows without having to type names of all the ligands?

**Comment by diogomart** [comment]
This may help: https://stackoverflow.com/questions/15537616/how-to-use-windows-command-line-regular-expressions

**Comment by jiteshdoshi** [comment]
> This may help: https://stackoverflow.com/questions/15537616/how-to-use-windows-command-line-regular-expressions

Yes thank you. That works.

**Comment by atultiwari** [comment]
> > This may help: https://stackoverflow.com/questions/15537616/how-to-use-windows-command-line-regular-expressions
> 
> Yes thank you. That works.

Hi,
Have you found any solution to make the batch mode work in Windows. I tried various combinations from the link mentioned above but unable to use the batch mode.
Thank you
Atul
