### ISSUE TITLE
python script results in unexpected very negative affinity score

### ISSUE THREAD

**Issue by gkxiao** [ccsb-scripps/AutoDock-Vina#68]
<p>I believe this to be a bug with Vina 1.2</p>
<h2>Environment Information</h2>
<p>Vina: 1.2.3</p>
<p>OS: Centos 7.6</p>
<p>Data set: <a href="https://github.com/gkxiao/very-negative-vina-score">https://github.com/gkxiao/very-negative-vina-score</a></p>
<h2>Expected Behavior</h2>
<p>pose_1.pdbqt is a docking pose from a command line calculation, the expected affinity score is -7.925 as following:</p>
<pre line="1" lang="python">
from vina import Vina
#create docking object
receptor = 'receptor.pdbqt'
ligand = 'pose_1.pdbqt'
output = 'pose_1_out.pdbqt'
dock = Vina(sf_name='vina',seed=-1280817548,verbosity=2)
dock.set_receptor(receptor)
center =  [5.061, 2.751, 17.703]
box_size = [15, 15, 15]
dock.compute_vina_maps(center=center, box_size=box_size)
dock.set_ligand_from_file(ligand)
#dock.dock()
energy = dock.score()
print('Score before minimization: %.3f (kcal/mol)' % energy[0])
</pre>
<pre>
Score before minimization: -7.925 (kcal/mol)
</pre>
<p>Vina Binary version gives the same results.</p>
<pre line="1" lang="python">
vina_1.2 --config docking.conf --ligand pose_1.pdbqt --score_only --verbosity 2
</pre>
<pre line="1" lang="python">
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see http://vina.scripps.edu for more information.      #
#################################################################

Scoring function : vina
Rigid receptor: receptor.pdbqt
Ligand: pose_1.pdbqt
Center: X 5.061 Y 2.751 Z 17.703
Size: X 15 Y 15 Z 15
Grid space: 0.375
Exhaustiveness: 8
CPU: 0
Verbosity: 2

Computing Vina grid ... done.
Estimated Free Energy of Binding   : -7.925 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -10.241 (kcal/mol)
    Ligand - Receptor              : -10.241 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.693 (kcal/mol)
    Ligand                         : -0.693 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 2.316 (kcal/mol)
(4) Unbound System's Energy        : -0.693 (kcal/mol)
</pre>
<h2>Actual Behavior</h2>
<p>Howerver, the python script in cammond line gives total differnt results: -149kcal/mol: </p>
<pre line="1" lang="python">
python docking.py
</pre>
<pre line="1" lang="python">
Computing Vina grid ... done.
WARNING: At low exhaustiveness, it may be impossible to utilize all CPUs.
Performing docking (random seed: -1280817548) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
done.
ENERGY FROM SEARCH: -10.9406
FINAL ENERGY: 
Estimated Free Energy of Binding   : -149.841 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -10.251 (kcal/mol)
    Ligand - Receptor              : -10.251 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.689 (kcal/mol)
    Ligand                         : -0.689 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.799 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -10.619
FINAL ENERGY: 
Estimated Free Energy of Binding   : -149.589 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -10.422 (kcal/mol)
    Ligand - Receptor              : -10.422 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.192 (kcal/mol)
    Ligand                         : -0.192 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.725 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -9.823
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.981 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.748 (kcal/mol)
    Ligand - Receptor              : -8.748 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -1.080 (kcal/mol)
    Ligand                         : -1.080 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.547 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -9.808
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.968 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -9.376 (kcal/mol)
    Ligand - Receptor              : -9.376 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.435 (kcal/mol)
    Ligand                         : -0.435 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.543 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -9.693
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.878 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.934 (kcal/mol)
    Ligand - Receptor              : -8.934 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.762 (kcal/mol)
    Ligand                         : -0.762 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.517 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -9.053
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.377 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.214 (kcal/mol)
    Ligand - Receptor              : -8.214 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.834 (kcal/mol)
    Ligand                         : -0.834 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.371 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -9.180
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.483 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -9.501 (kcal/mol)
    Ligand - Receptor              : -9.501 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : 0.316 (kcal/mol)
    Ligand                         : 0.316 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.402 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.835
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.213 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.022 (kcal/mol)
    Ligand - Receptor              : -8.022 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.813 (kcal/mol)
    Ligand                         : -0.813 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.323 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.624
FINAL ENERGY: 
Estimated Free Energy of Binding   : -148.057 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.141 (kcal/mol)
    Ligand - Receptor              : -8.141 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.493 (kcal/mol)
    Ligand                         : -0.493 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.277 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.157
FINAL ENERGY: 
Estimated Free Energy of Binding   : -147.690 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -7.094 (kcal/mol)
    Ligand - Receptor              : -7.094 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -1.066 (kcal/mol)
    Ligand                         : -1.066 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.170 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.324
FINAL ENERGY: 
Estimated Free Energy of Binding   : -138.088 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : 4.966 (kcal/mol)
    Ligand - Receptor              : 4.966 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.718 (kcal/mol)
    Ligand                         : -0.718 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 40.363 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.091
FINAL ENERGY: 
Estimated Free Energy of Binding   : -141.540 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : 0.372 (kcal/mol)
    Ligand - Receptor              : 0.372 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.584 (kcal/mol)
    Ligand                         : -0.584 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 41.372 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -8.126
FINAL ENERGY: 
Estimated Free Energy of Binding   : -147.664 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -7.620 (kcal/mol)
    Ligand - Receptor              : -7.620 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.507 (kcal/mol)
    Ligand                         : -0.507 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 43.162 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -6.997
FINAL ENERGY: 
Estimated Free Energy of Binding   : -146.795 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -8.043 (kcal/mol)
    Ligand - Receptor              : -8.043 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : 1.040 (kcal/mol)
    Ligand                         : 1.040 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 42.908 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -5.683
FINAL ENERGY: 
Estimated Free Energy of Binding   : -145.777 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -4.769 (kcal/mol)
    Ligand - Receptor              : -4.769 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.919 (kcal/mol)
    Ligand                         : -0.919 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 42.611 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -5.912
FINAL ENERGY: 
Estimated Free Energy of Binding   : -135.714 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : 7.984 (kcal/mol)
    Ligand - Receptor              : 7.984 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.667 (kcal/mol)
    Ligand                         : -0.667 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 39.669 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -5.692
FINAL ENERGY: 
Estimated Free Energy of Binding   : -143.846 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -4.257 (kcal/mol)
    Ligand - Receptor              : -4.257 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : 1.065 (kcal/mol)
    Ligand                         : 1.065 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 42.046 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -5.537
FINAL ENERGY: 
Estimated Free Energy of Binding   : -145.661 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : -4.676 (kcal/mol)
    Ligand - Receptor              : -4.676 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.863 (kcal/mol)
    Ligand                         : -0.863 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 42.577 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: -5.444
FINAL ENERGY: 
Estimated Free Energy of Binding   : -141.908 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : 0.098 (kcal/mol)
    Ligand - Receptor              : 0.098 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : -0.785 (kcal/mol)
    Ligand                         : -0.785 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 41.480 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)
ENERGY FROM SEARCH: 247.478
FINAL ENERGY: 
Estimated Free Energy of Binding   : 50.180 (kcal/mol) [=(1)+(2)+(3)+(4)]
(1) Final Intermolecular Energy    : 64.848 (kcal/mol)
    Ligand - Receptor              : 64.848 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : 182.700 (kcal/mol)
    Ligand                         : 182.700 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : -14.668 (kcal/mol)
(4) Unbound System's Energy        : 182.700 (kcal/mol)

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1    -149.8414     0.0000     0.0000
   2    -149.5893     0.7274     2.3684
   3    -148.9809     3.2994     6.4348
   4    -148.9676     1.8543     3.0350
   5    -148.8782     1.8490     2.8579
   6    -148.4830     2.4573     3.6517
   7    -148.3769     3.8287     7.5138
   8    -148.2126     3.8224     7.4557
   9    -148.0573     2.2618     3.7545
  10    -147.6903     3.6454     6.9867
  11    -147.6641     1.5086     2.4942
  12    -146.7947     1.8645     2.2871
  13    -145.7771     2.9325     6.8320
  14    -145.6614     3.3765     7.2577
  15    -143.8460     3.3936     4.4782
  16    -141.9077     2.0037     3.0612
  17    -141.5400     1.9712     3.4042
  18    -138.0882     1.6318     2.4177
  19    -135.7138     3.4993     7.2856
  20      50.1802     6.6452     8.4232
</pre>
<p>Obviously, Very high term 3 and 4 results in the very negative affinity score. By the way, the actual affinity is (1)+(2)+(3)-(4) instead of (1)+(2)+(3)+(4).</p>

<h2>Steps to Reproduce</h2>
<p>The materials to reproduce the results can be available from: <a href="https://github.com/gkxiao/very-negative-vina-score">https://github.com/gkxiao/very-negative-vina-score</a></p>

**Comment by diogomart** [comment]
Thanks for the report and for the steps to reproduce. I can reproduce on CentOS.

**Comment by diogomart** [comment]
Fixed by #81.
