### ISSUE TITLE
Please make a batch submission example.

### ISSUE THREAD

**Issue by jpmfc6** [ccsb-scripps/AutoDock-Vina#71]
Please make a batch submission example.

**Comment by jfair32** [comment]
contents of config file below:

receptor= receptor_rigid.pdbqt
flex= receptor_flexible.pdbqt
batch= ligand1.pdbqt
batch= ligand2.pdbqt
batch= ligand3.pdbqt
dir= flex_results
center_x= 0
center_y= 0
center_z= 0
size_x= 24
size_y= 24
size_z= 24

**Comment by sajad-stack** [comment]
what if I am dealing with several hundred ligands in pdbqt format stored in a directory?
How can I do the docking in the batch mode?
Thank you in advance,
Sajjad

**Comment by missuse** [comment]
> what if I am dealing with several hundred ligands in pdbqt format stored in a directory? How can I do the docking in the batch mode? Thank you in advance, Sajjad

here is an example:

`vina --receptor rec.pdbqt --batch folder_with_ligands/*.pdbqt --config vina.conf --exhaustiveness 64 --dir vina_64 --cpu 10 >> vina_64/log`

**Comment by jpmfc6** [comment]
The above examples work when --scoring is set to "vina", but doesn't seem to work when --scoring is set to "vinardo". The error says the affinity maps were not initialized. I know how to make maps, however I can't figure out syntax that does the job. Is batch submission possible while specifying --scoring vinardo? I know a for loop can be used, but that's not using the batch submission functionality.

**Comment by diogomart** [comment]
Will follow up on the vinardo/batch incompatibility in issue #186
