### ISSUE TITLE
windows_x86_64 msi is incompatible naming convention 

### ISSUE THREAD

**Issue by greel70** [ccsb-scripps/AutoDock-Vina#73]
The current naming convention vina_1.2.3_windows_x86_64 causes issues when downloading. I recommend rebuilding the msi using vina_1_2_3_windows_x86_64.msi to correct this issue. I'm unable to install it as it is.

**Comment by diogomart** [comment]
Hi, the file is an executable, not an installer. You can rename it to have a `.exe` extension.
