### ISSUE TITLE
python setup.py build failure in anaconda using windows (version 1.2.3)

### ISSUE THREAD

**Issue by jfair32** [ccsb-scripps/AutoDock-Vina#76]
setup.py failed to compile using anaconda on windows

Here is the result from running:

(vina) C:\Users\jfair\AutoDock-Vina\build\python>python setup.py build install
Version found 1.2.3 (from __init__.py)
running build
running build_ext
Boost library location automatically determined in this conda environment.
Boost library location was automatically guessed at C:\Users\jfair\anaconda3\envs\vina\include.
- include_dirs: ['C:\\Users\\jfair\\anaconda3\\envs\\vina\\include', 'C:\\Users\\jfair\\anaconda3\\envs\\vina\\Include', 'C:\\Users\\jfair\\anaconda3\\envs\\vina\\include', 'src/lib']
- library_dirs: ['C:\\Users\\jfair\\anaconda3\\envs\\vina\\libs', 'C:\\Users\\jfair\\anaconda3\\envs\\vina', 'C:\\Users\\jfair\\anaconda3\\envs\\vina\\PCbuild\\amd64', 'C:\\Users\\jfair\\anaconda3\\envs\\vina\\lib']
- swig options: ['-c++', '-small', '-naturalvar', '-fastdispatch', '-shadow', '-py3', '-IC:\\Users\\jfair\\anaconda3\\envs\\vina\\include', '-IC:\\Users\\jfair\\anaconda3\\envs\\vina\\Include', '-IC:\\Users\\jfair\\anaconda3\\envs\\vina\\include', '-Isrc/lib']
- libraries: []
- extra link args: ['-lboost_thread', '-lboost_serialization', '-lboost_filesystem', '-lboost_program_options']
Traceback (most recent call last):
  File "C:\Users\jfair\AutoDock-Vina\build\python\setup.py", line 346, in <module>
    setup(
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\jfair\AutoDock-Vina\build\python\setup.py", line 196, in run
    self.run_command('build_ext')
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\jfair\anaconda3\envs\vina\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\jfair\AutoDock-Vina\build\python\setup.py", line 301, in build_extensions
    self.compiler.compiler_so[0] = "g++"
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

**Comment by diogomart** [comment]
Python bindings work only on Linux and Mac Intel. Sorry about that.

**Comment by jfair32** [comment]
Thank you for the quick reply. I have attempted to install vina-1.2.3 on windows using the executable and by building from source.  Do you know anyone who has been able to get it to run on Windows? If so, can you share how they accomplished it?
Thanks,
Justin

From: Diogo ***@***.***>
Reply-To: ccsb-scripps/AutoDock-Vina ***@***.***>
Date: Tuesday, January 18, 2022 at 7:41 PM
To: ccsb-scripps/AutoDock-Vina ***@***.***>
Cc: Justin Fair ***@***.***>, Author ***@***.***>
Subject: Re: [ccsb-scripps/AutoDock-Vina] python setup.py build failure in anaconda using windows (version 1.2.3) (Issue #76)


Python bindings work only on Linux and Mac Intel. Sorry about that.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccsb-scripps%2FAutoDock-Vina%2Fissues%2F76%23issuecomment-1015964577&data=04%7C01%7Cjfair%40iup.edu%7C8f02563e007842bfad9a08d9dae45b4a%7C96704ed7a3e14bb8ba918b63ee16883e%7C0%7C0%7C637781496617381175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4FXnj57BzwykYRe6s6E8UCoYvo24TYBV0xku6t%2BZ0C0%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXLTSC3AGA2FTYDDWXJ54Y3UWYCBRANCNFSM5MII2V6A&data=04%7C01%7Cjfair%40iup.edu%7C8f02563e007842bfad9a08d9dae45b4a%7C96704ed7a3e14bb8ba918b63ee16883e%7C0%7C0%7C637781496617381175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ko96kNv%2Byj1YjyFbBdaLnMHtOzjSJadqxSKuDk2p4zc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjfair%40iup.edu%7C8f02563e007842bfad9a08d9dae45b4a%7C96704ed7a3e14bb8ba918b63ee16883e%7C0%7C0%7C637781496617391119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y6IdAdaqS00dvl0rpjkcACc9pBmYCznTbNFO8Q1l%2FOs%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjfair%40iup.edu%7C8f02563e007842bfad9a08d9dae45b4a%7C96704ed7a3e14bb8ba918b63ee16883e%7C0%7C0%7C637781496617391119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EjS8xNYA42i77oA2yDe1Wd33ZO2HStVIxI04TqgeG6I%3D&reserved=0>.

**Comment by diogomart** [comment]
The easiest is to download the [executable](https://github.com/ccsb-scripps/AutoDock-Vina/releases) and run it from the command prompt. I just added the `.exe` extension to the executable to clarify that it is not an installer.

**Comment by jfair32** [comment]
Thank you so very much for clarifying that the file is an executable.  So much easier than what I was making it out to be.  I was able to get the new version to run.

Thank you again!!
