### ISSUE TITLE
using --batch option to dock several hundred molecules

### ISSUE THREAD

**Issue by sajad-stack** [ccsb-scripps/AutoDock-Vina#89]
I am dealing with several hundred ligands in pdbqt format stored in a directory.
Could you please give me a clue on how can I do the docking in the batch mode?
Thank you in advance,
Sajad

**Comment by DarthSaddest** [comment]
Create a for loop in Python?

**Comment by diogomart** [comment]
Also `--batch` option when using the command line executable.
