### ISSUE TITLE
Grid spacing when using Vina

### ISSUE THREAD

**Issue by ghscheiffer** [ccsb-scripps/AutoDock-Vina#91]
Hello!
I've noticed that the program shows a grid spacing of 0.375 when I run a docking, although I always assumed (in the older versions of Vina) that there's only a default grid spacing of 1 angstrom, since there isn't a way of changing this parameter. So, when I'm defining a gridbox on AutoDock Tools, should I consider a 0.375A spacing? (Therefore defining a larger box)

**Comment by diogomart** [comment]
Hi,

In older versions, such as v1.1.2, and in v1.2.0 and newer, the grid spacing is 0.375. However, the size of the box is specified in angstroms, not in number of grid points.

If you are calculating autodock4 maps with autogrid4 and passing them to vina, you can use any value for the spacing. Values larger than 0.375 are a bad idea.

**Comment by BruciiZ** [comment]
Dear Developer,

Thank you for the amazing program. I am actually still a bit confused by this explanation. Should I interpret your words as indicating that we should not try to adjust the grid spacing parameter even though we can specify out own value? Also, I am wondering if my conversion from AD4 to Vina is right:

suppose in AD4, I have a grid box with 40 grid points at each dimension, and spacing is set to 0.5. That should give me : (40-1) * 0.5 = 19.5 A for each dimension ([reference](http://www.csb.yale.edu/userguides/datamanip/autodock/html/Using_AutoDock_305.9.html)). And if I specify 19.5 in Vina as the size parameter, I should get the same grid box?

**Comment by diogomart** [comment]
Nothing wrong with smaller spacing. But larger than the default is just too coarse. Even at 0.375 there's a often a difference of a few tenths of a kcal/mol after refinement with receptor atoms.

Autogrid always uses odd numbers of grid points, so if you ask for 40 in the .gpf, you actually get 41. That would be 20 Angstrom at 0.5 spacing. You can write grids from vina to make sure they have the expected number of grid points.

In Vina, the size of the box is specified in Angstrom, not number of grid points.

**Comment by BruciiZ** [comment]
Thank you so much for the reply. And I appreciate it that you pointed out that in AD4 grid points are always odd number which I’ve ignored for long.

I noticed that the size parameter in Vina is specified in Angstrom, not number of grid points. May I still know, if this is the case, what exactly does the spacing in Vina control? In AD4, this is the “distance” between two grid points. But in Vina, given that the size parameter is in Angstrom already, I’m lost as to what the spacing parameter means.

I’ll make sure to use the Python binding to check the number of grid points to verify. Thanks again for the new release. This has been really great work.

**Comment by diogomart** [comment]
The spacing in Vina also controls the distance between grid points. It's just that autogrid takes as argument the number of grid points directly, while vina takes as argument the size of the box in Angstrom and then converts internally to number of grid points.
