### ISSUE TITLE
vina1.2.3 for mac binary file error with no "libboost_system.dylib"

### ISSUE THREAD

**Issue by jaehongshin** [ccsb-scripps/AutoDock-Vina#92]
Hello,
I tried to execute "vina_1.2.3_mac_x86_64" file on my mac. But there is an error message:
"Library not loaded: /usr/local/opt/boost/lib/libboost_system.dylib"

How to solve this error?
Thanks

**Comment by diogomart** [comment]
You probably need the boost libraries. I don't know much about macs, but you may find relevant information in the issues by searching for "mac" or "homebrew": https://github.com/ccsb-scripps/AutoDock-Vina/issues?q=mac+OR+homebrew

**Comment by jaehongshin** [comment]
After installing homebrew followed by boost based on the link: https://github.com/ccsb-scripps/AutoDock-Vina/issues/59 
Vina worked fine on Mac 12.2.1, Thanks

**Comment by diogomart** [comment]
That's great to hear, thanks!
