### ISSUE TITLE
Exhaustibility, box size, and consistency

### ISSUE THREAD

**Issue by DarthSaddest** [ccsb-scripps/AutoDock-Vina#98]
In an off-the-cuff remark, the official documentation advises setting exhaustibility at `32`, rather than the default `8`, for a `20*20*20` box but there's nothing more on these aspects. Certain bioinformaticists have [advised](https://www.researchgate.net/post/How_can_I_increase_the_reproducibility_of_a_docking_program/5410a248d3df3eab1f8b462b/citation/download) in RGate to set exhaustibility as high as `1024` to ensure reproducibility, independent of seed value.

There ought to be some guidance provided on how `exhaustibility` must be varied with `box_size` etc. Some statistical testing on a standard database ought to be interesting.

**Comment by diogomart** [comment]
Yes, we should run such tests and write a guide to inform users how to deviate from the defaults. For autodock-gpu, the number of evaluations (a.k.a scored poses) needed to reach convergence increases exponentially with the number of rotatable bonds. Vina automatically increases the number of evaluations based on the number of movable atoms and the number of rotatable bonds, but that increase is not as steep as an exponential function, and the size of the search space is not factored in. For an "average small molecule" with about 20 heavy atoms and maybe 6 rotatable bonds, and a 20x20x20 search space, the default exhaustiveness=8 should find the best solution most of the time, maybe 80% or 90% of the time, but I don't know the exact numbers. For larger than "average" molecules, I don't really know how much the exhaustiveness should be increased.

**Comment by DarthSaddest** [comment]
Thanks! Does there exist any particular reason why Vina's increase in `n(evaluations)` is not exponentially steep? 

Btw, an off-topic query: How do I raise issues with ADFR? It seems to be not hosted in Github.

**Comment by diogomart** [comment]
These are excellent questions, and I don't know the answer :)
